# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Codex runtime installation helpers.

This module is intentionally conservative: it updates only the keys it owns and
tries to preserve unrelated user configuration.
"""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .safety import resolve_within_root


@dataclass(frozen=True)
class RuntimeFileCopy:
    source: Path
    relative_target: Path


@dataclass(frozen=True)
class RuntimeFileWrite:
    relative_target: Path
    content: str


@dataclass(frozen=True)
class RuntimeInstallPlan:
    files: list[RuntimeFileCopy] = field(default_factory=list)
    writes: list[RuntimeFileWrite] = field(default_factory=list)
    hook_commands: list[str] = field(default_factory=list)
    config_plugins: dict[str, dict[str, object]] = field(default_factory=dict)


def _read_json(path: Path) -> object | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except OSError:
        return None
    except json.JSONDecodeError:
        return None


def _write_json(path: Path, payload: object) -> None:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _ensure_hooks_payload(payload: object | None) -> dict[str, Any]:
    if isinstance(payload, dict):
        return dict(payload)
    return {}


def merge_hook_commands(payload: object | None, commands: list[str]) -> dict[str, Any]:
    """Merge hook commands into a generic `hooks.json` payload.

    The validator walks for any nested `{"command": ...}` keys, so we keep a simple
    top-level `hooks: [{command: ...}]` structure.
    """

    merged = _ensure_hooks_payload(payload)
    hooks = merged.get("hooks")
    if not isinstance(hooks, list):
        hooks = []

    existing = {
        item.get("command")
        for item in hooks
        if isinstance(item, dict) and isinstance(item.get("command"), str)
    }
    for command in commands:
        if command in existing:
            continue
        hooks.append({"command": command})
        existing.add(command)

    merged["hooks"] = hooks
    return merged


_PLUGINS_HEADER_RE = re.compile(r'^\[plugins\.(?:"([^"]+)"|([A-Za-z0-9_-]+))\]\s*$')
_TOML_KEY_RE = re.compile(r"^([A-Za-z0-9_.-]+)\s*=")


def _toml_scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    raise TypeError(f"Unsupported TOML scalar value: {value!r}")


def _ensure_trailing_newline(text: str) -> str:
    if not text:
        return ""
    return text if text.endswith("\n") else text + "\n"


def _update_plugin_section_lines(
    lines: list[str],
    *,
    header_index: int,
    updates: dict[str, object],
) -> list[str]:
    end = header_index + 1
    while end < len(lines) and not lines[end].startswith("["):
        end += 1

    section_lines = lines[header_index + 1 : end]
    key_to_index: dict[str, int] = {}
    for idx, line in enumerate(section_lines):
        match = _TOML_KEY_RE.match(line.strip())
        if match:
            key_to_index[match.group(1)] = idx

    for key, value in updates.items():
        rendered = f"{key} = {_toml_scalar(value)}\n"
        if key in key_to_index:
            section_lines[key_to_index[key]] = rendered
        else:
            section_lines.append(rendered)

    return lines[: header_index + 1] + section_lines + lines[end:]


def merge_plugin_config_toml(text: str, plugin_updates: dict[str, dict[str, object]]) -> str:
    """Merge plugin updates into a config.toml string (best-effort, idempotent)."""

    lines = _ensure_trailing_newline(text).splitlines(keepends=True)
    if not lines:
        lines = []

    def find_section(plugin: str) -> int | None:
        for idx, line in enumerate(lines):
            match = _PLUGINS_HEADER_RE.match(line.strip())
            if not match:
                continue
            name = match.group(1) or match.group(2) or ""
            if name == plugin:
                return idx
        return None

    for plugin, updates in plugin_updates.items():
        if not isinstance(updates, dict) or not updates:
            continue
        header_idx = find_section(plugin)
        header_line = f'[plugins."{plugin}"]\n'
        if header_idx is None:
            if lines and not lines[-1].endswith("\n"):
                lines[-1] += "\n"
            if lines and lines[-1].strip():
                lines.append("\n")
            lines.append(header_line)
            header_idx = len(lines) - 1
        lines = _update_plugin_section_lines(lines, header_index=header_idx, updates=updates)

    return "".join(lines)


def install_runtime_assets(
    plan: RuntimeInstallPlan,
    *,
    codex_home: Path,
    dry_run: bool,
) -> None:
    if dry_run:
        return

    codex_home = codex_home.expanduser().resolve()
    codex_home.mkdir(parents=True, exist_ok=True)

    for write in plan.writes:
        target = resolve_within_root(
            codex_home,
            codex_home / write.relative_target,
            kind="runtime asset target",
        )
        target.parent.mkdir(parents=True, exist_ok=True)
        content = write.content
        if content and not content.endswith("\n"):
            content += "\n"
        target.write_text(content, encoding="utf-8")

    for file_copy in plan.files:
        source = file_copy.source.expanduser().resolve()
        if not source.exists():
            raise FileNotFoundError(f"Runtime asset source does not exist: {source}")
        target = resolve_within_root(
            codex_home,
            codex_home / file_copy.relative_target,
            kind="runtime asset target",
        )
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)

    hooks_path = codex_home / "hooks.json"
    hooks_payload = _read_json(hooks_path) if hooks_path.exists() else None
    merged_hooks = merge_hook_commands(hooks_payload, plan.hook_commands)
    _write_json(hooks_path, merged_hooks)

    config_path = codex_home / "config.toml"
    existing = ""
    if config_path.exists():
        try:
            existing = config_path.read_text(encoding="utf-8")
        except OSError:
            existing = ""
    merged_config = merge_plugin_config_toml(existing, plan.config_plugins)
    config_path.write_text(merged_config, encoding="utf-8")
