#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Shared nativeness-review handoff helpers for migration workflows."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


def run_tracker_write(repo_root: Path, tracker_script: Path) -> tuple[bool, str]:
    """Refresh the migration tracker for a live workflow."""
    if not tracker_script.exists():
        return (False, f"Tracker script not found: {tracker_script}")
    proc = subprocess.run(
        [sys.executable, str(tracker_script), "--write"],
        cwd=str(repo_root),
        capture_output=True,
        text=True,
    )
    output = (proc.stdout + proc.stderr).strip()
    return (proc.returncode == 0, output)


def build_nativeness_review_handoff(
    artifact_ids: list[str],
    *,
    preview: bool,
    validation_failed: bool = False,
    tracker_updated: bool = True,
    tracker_command: str,
) -> dict[str, object]:
    """Return a structured nativeness-review handoff payload.

    The migration wrappers stop after deterministic write + structural
    validation. Nativeness review is a separate interactive Verify phase.
    """
    if preview:
        return {
            "required": False,
            "can_record_review": False,
            "state": "preview_only",
            "auto_record_native_on_no_findings": False,
            "default_native_review_summary": "No findings after convergence",
            "artifact_ids": artifact_ids,
            "tracker_refresh_command": f"{tracker_command} --write",
            "instructions": [
                "Preview mode writes generated output only into the preview tree.",
                "Inspect the preview output first; nativeness review starts only after a live write.",
            ],
            "record_review_examples": [],
        }

    if not artifact_ids:
        return {
            "required": False,
            "can_record_review": False,
            "state": "not_applicable",
            "auto_record_native_on_no_findings": False,
            "default_native_review_summary": "No findings after convergence",
            "artifact_ids": [],
            "tracker_refresh_command": f"{tracker_command} --write",
            "instructions": [
                "No new migrated artifacts were written, so no nativeness-review handoff is required."
            ],
            "record_review_examples": [],
        }

    if validation_failed:
        return {
            "required": True,
            "can_record_review": False,
            "state": "validation_failed",
            "auto_record_native_on_no_findings": False,
            "default_native_review_summary": "No findings after convergence",
            "artifact_ids": artifact_ids,
            "tracker_refresh_command": f"{tracker_command} --write",
            "instructions": [
                "Fix the post-write validation failures first; these artifacts are not ready for nativeness review.",
                "Do not refresh the migration tracker or record nativeness outcomes until validation passes.",
                "After fixing the artifact and rerunning the workflow, continue with the normal nativeness-review handoff.",
            ],
            "record_review_examples": [],
        }

    if not tracker_updated:
        return {
            "required": True,
            "can_record_review": False,
            "state": "tracker_refresh_required",
            "auto_record_native_on_no_findings": False,
            "default_native_review_summary": "No findings after convergence",
            "artifact_ids": artifact_ids,
            "tracker_refresh_command": f"{tracker_command} --write",
            "instructions": [
                "Refresh the migration tracker first so the persisted state records `pending_native_review`.",
                "Do not record nativeness outcomes until the tracker refresh succeeds.",
                "After tracker refresh, rerun the nativeness-review audit handoff or record outcomes manually with evidence.",
            ],
            "record_review_examples": [],
        }

    examples = []
    for artifact_id in artifact_ids:
        examples.append(
            {
                "artifact_id": artifact_id,
                "native": (
                    f"{tracker_command} --write "
                    f"--record-review {artifact_id}=native "
                    f"--review-evidence {artifact_id}=<nativeness-review-review-report-path> "
                    f'--review-summary {artifact_id}="No findings after convergence"'
                ),
                "codex_compatible_but_not_native": (
                    f"{tracker_command} --write "
                    f"--record-review {artifact_id}=codex_compatible_but_not_native "
                    f"--review-evidence {artifact_id}=<nativeness-review-review-report-path> "
                    f'--review-summary {artifact_id}="Medium-only issues remain after review"'
                ),
            }
        )

    return {
        "required": True,
        "can_record_review": True,
        "state": "pending_native_review",
        "auto_record_native_on_no_findings": True,
        "default_native_review_summary": "No findings after convergence",
        "artifact_ids": artifact_ids,
        "tracker_refresh_command": f"{tracker_command} --write",
        "instructions": [
            "Run the nativeness-review audit as a separate interactive Verify phase.",
            "Prefer entering that review from `migration-dashboard` queue commands when the artifact is already pending review.",
            "Keep the nativeness auditor read-only; apply any fixes in the parent workflow.",
            (
                "Return only a compact verdict summary in the parent thread; "
                "keep the full audit in a review-report or the delegated reviewer transcript."
            ),
            (
                "If the final audit or convergence result is `NO_FINDINGS`, record "
                "`native` by default through the tracker CLI with summary "
                "`No findings after convergence` unless the user explicitly "
                "requested audit-only behavior."
            ),
            "If only MEDIUM issues remain, record an outcome only with explicit user confirmation or workflow-specific judgment guidance.",
        ],
        "record_review_examples": examples,
    }
