# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Path helpers for Codex migration-family support tooling."""

from __future__ import annotations

from pathlib import Path


def find_repo_root(start: Path | None = None) -> Path:
    """Walk upward from ``start`` to find the example repository root."""
    p = (start or Path(__file__).resolve().parent).resolve()
    if p.is_file():
        p = p.parent

    while p != p.parent:
        git_sentinel = p / ".git"
        if git_sentinel.is_dir() or git_sentinel.is_file():
            return p
        if (p / "package.json").is_file():
            return p
        p = p.parent

    raise RuntimeError("Repository root not found")


def tracker_file_path(repo_root: Path | None = None) -> Path:
    """Return the live migration tracker JSON path."""
    root = repo_root or find_repo_root()
    return root / "migration-state.json"


def archived_tracker_file_path(repo_root: Path | None = None) -> Path:
    """Return the archived migration tracker JSON path."""
    root = repo_root or find_repo_root()
    return root / "migration-state.archived.json"
