# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Shared primitive and MCP namespace helpers for public migration scripts."""

from __future__ import annotations

import re

PRIMITIVE_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    ("AskUserQuestion", "# RUNTIME_DEPENDENT: request_user_input or approval workflow"),
    ("TaskCreate", "spawn_agent"),
    ("TaskUpdate", "update_plan"),
    ("TaskList", "# NO_CODEX_EQUIVALENT: track locally or via update_plan"),
    ("TaskGet", "wait_agent"),
    ("TaskOutput", "wait_agent"),
    ("TaskStop", "close_agent"),
    ("TeamCreate", "spawn_agent"),
    ("EnterPlanMode", "# NO_CODEX_EQUIVALENT: use inline planning"),
    ("ExitPlanMode", "# NO_CODEX_EQUIVALENT: use inline planning"),
    ("TodoWrite", "update_plan"),
    ("NotebookEdit", "# NO_CODEX_EQUIVALENT: not supported"),
    ("SendMessage", "send_input"),
    ("CronCreate", "# NO_CODEX_EQUIVALENT: use external scheduler"),
    ("CronDelete", "# NO_CODEX_EQUIVALENT: use external scheduler"),
    ("CronList", "# NO_CODEX_EQUIVALENT: use external scheduler"),
)

MAPPING_TABLE_PATTERN = re.compile(
    r"(→|->|NO_CODEX_EQUIVALENT|RUNTIME_DEPENDENT|Codex Equivalent|"
    r"Claude Primitive|fabricated|Previously|Does not exist)"
)


def normalize_mcp_namespaces(text: str) -> str:
    """Normalize server segments in callable MCP namespaces."""

    def repl(match: re.Match[str]) -> str:
        segment = match.group(1)
        return f"mcp__{segment.replace('-', '_')}__"

    return re.sub(r"mcp__([a-z0-9][a-z0-9\-]*)__", repl, text)


def apply_primitive_mappings(text: str) -> str:
    """Replace source primitives only in executable-like contexts."""

    lines = text.splitlines(keepends=True)
    result: list[str] = []
    for line in lines:
        if MAPPING_TABLE_PATTERN.search(line):
            result.append(line)
            continue
        modified = line
        for old, new in PRIMITIVE_REPLACEMENTS:
            modified = re.sub(rf"\b{re.escape(old)}\b", new, modified)
        result.append(modified)
    return "".join(result)
