# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Shared safety helpers for migration-family tooling."""

from __future__ import annotations

import re
from pathlib import Path


SAFE_IDENTIFIER_RE = re.compile(r"[a-z0-9][a-z0-9_-]*\Z")


def is_safe_identifier(value: str) -> bool:
    """Return True when the value matches the repo's slug policy."""
    return bool(SAFE_IDENTIFIER_RE.fullmatch(value))


def validate_identifier(value: str, *, kind: str) -> str | None:
    """Validate a user- or source-provided identifier."""
    if is_safe_identifier(value):
        return None
    return (
        f"Invalid {kind} identifier: {value!r}. Expected a lowercase slug using "
        "letters, digits, hyphens, or underscores."
    )


def resolve_within_root(root: Path, candidate: Path, *, kind: str) -> Path:
    """Resolve a path and require that it stays under the given root."""
    resolved_root = root.resolve(strict=False)
    resolved_candidate = candidate.resolve(strict=False)
    try:
        resolved_candidate.relative_to(resolved_root)
    except ValueError as exc:
        raise ValueError(
            f"{kind} escapes its root: {candidate} is not under {root}"
        ) from exc
    return resolved_candidate


def safe_provenance_value(value: str) -> str:
    """Escape untrusted values before embedding them into generated comments."""
    return (
        value.replace("\\", "\\\\")
        .replace("\r", "\\r")
        .replace("\n", "\\n")
        .replace("-->", "--\\>")
    )


def _resolve_display_relative(path: Path, root: Path) -> str | None:
    try:
        relative = path.relative_to(root.resolve(strict=False))
    except ValueError:
        return None
    text = relative.as_posix()
    return text or "."


def describe_path_for_display(
    path: Path,
    *,
    repo_root: Path,
    named_roots: tuple[tuple[str, Path], ...] = (),
) -> str:
    """Render a path without leaking host-specific absolute filesystem details."""
    if not path.is_absolute():
        return path.as_posix() or "."

    normalized = path.resolve(strict=False)
    repo_relative = _resolve_display_relative(normalized, repo_root)
    if repo_relative is not None:
        return repo_relative

    for label, root in named_roots:
        named_relative = _resolve_display_relative(normalized, root)
        if named_relative is not None:
            if named_relative == ".":
                return f"<{label}>"
            return f"<{label}>/{named_relative}"

    if normalized.name:
        return f"<absolute-path>/{normalized.name}"
    return "<absolute-path>"
