# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Shared skill dependency planning helpers for migration-family tooling."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BatchPlan:
    requested_skills: list[str]
    expanded_skills: list[str]
    blocked_skills: list[str]
    cycles: list[list[str]]
    execution_groups: list[list[str]]


def _expand_skill_batch(
    requested_skills: list[str],
    *,
    source_skill_names: set[str],
    dependency_edges: dict[str, set[str]],
    available_codex_skills: set[str],
) -> list[str]:
    queue = [skill for skill in requested_skills if skill in source_skill_names]
    seen = set(queue)

    while queue:
        skill = queue.pop(0)
        for dependency in sorted(dependency_edges.get(skill, set())):
            if dependency not in source_skill_names:
                continue
            if dependency in available_codex_skills:
                continue
            if dependency in seen:
                continue
            seen.add(dependency)
            queue.append(dependency)

    return sorted(seen)


def strongly_connected_components(edges: dict[str, set[str]]) -> list[list[str]]:
    """Compute SCCs using a deterministic Kosaraju pass."""
    order: list[str] = []
    visited: set[str] = set()

    reverse_edges: dict[str, set[str]] = {node: set() for node in edges}
    for node, neighbors in edges.items():
        for neighbor in neighbors:
            reverse_edges.setdefault(neighbor, set()).add(node)

    def visit(node: str) -> None:
        if node in visited:
            return
        visited.add(node)
        for neighbor in sorted(edges.get(node, set())):
            visit(neighbor)
        order.append(node)

    for node in sorted(edges):
        visit(node)

    assigned: set[str] = set()
    components: list[list[str]] = []

    def collect(node: str, component: list[str]) -> None:
        if node in assigned:
            return
        assigned.add(node)
        component.append(node)
        for neighbor in sorted(reverse_edges.get(node, set())):
            collect(neighbor, component)

    for node in reversed(order):
        if node in assigned:
            continue
        component: list[str] = []
        collect(node, component)
        components.append(sorted(component))

    return components


def _compute_cycles(
    nodes: set[str], edges: dict[str, set[str]], components: list[list[str]]
) -> list[list[str]]:
    cycles: list[list[str]] = []
    for component in components:
        if len(component) > 1:
            cycles.append(component)
            continue
        node = component[0]
        if node in nodes and node in edges.get(node, set()):
            cycles.append(component)
    return cycles


def build_skill_batch_plan(
    *,
    requested_skills: list[str],
    source_skill_names: set[str],
    dependency_edges: dict[str, set[str]],
    available_codex_skills: set[str],
) -> BatchPlan:
    blocked = sorted(skill for skill in requested_skills if skill not in source_skill_names)
    expanded = _expand_skill_batch(
        requested_skills,
        source_skill_names=source_skill_names,
        dependency_edges=dependency_edges,
        available_codex_skills=available_codex_skills,
    )

    induced_edges: dict[str, set[str]] = {
        node: {neighbor for neighbor in dependency_edges.get(node, set()) if neighbor in expanded}
        for node in expanded
    }
    components = strongly_connected_components(induced_edges)
    cycles = _compute_cycles(set(expanded), induced_edges, components)

    execution_groups = _topologically_order_scc_groups(components, induced_edges)

    return BatchPlan(
        requested_skills=list(requested_skills),
        expanded_skills=expanded,
        blocked_skills=blocked,
        cycles=cycles,
        execution_groups=execution_groups,
    )


def _topologically_order_scc_groups(
    components: list[list[str]],
    edges: dict[str, set[str]],
) -> list[list[str]]:
    """Return SCC components in deterministic topological order.

    ``edges`` are dependency edges in the form ``skill -> dependency``.

    Execution order must run dependencies first, so we topologically sort the reversed
    condensation graph (``dependency -> dependent``).
    """

    if not components:
        return []

    # Map each node to its SCC index.
    node_to_component: dict[str, int] = {}
    for idx, component in enumerate(components):
        for node in component:
            node_to_component[node] = idx

    # Build condensation graph between SCCs.
    component_edges: dict[int, set[int]] = {idx: set() for idx in range(len(components))}
    indegree: dict[int, int] = {idx: 0 for idx in range(len(components))}

    for node, neighbors in edges.items():
        dependent = node_to_component.get(node)
        if dependent is None:
            continue
        for neighbor in neighbors:
            dependency = node_to_component.get(neighbor)
            if dependency is None or dependency == dependent:
                continue
            # Reverse edge: dependency component must precede dependent component.
            if dependent in component_edges[dependency]:
                continue
            component_edges[dependency].add(dependent)
            indegree[dependent] += 1

    # Deterministic Kahn: break ties by component's first skill name (components are sorted).
    def key(idx: int) -> str:
        component = components[idx]
        return component[0] if component else ""

    ready = sorted([idx for idx, deg in indegree.items() if deg == 0], key=key)
    ordered: list[int] = []

    while ready:
        idx = ready.pop(0)
        ordered.append(idx)
        for dst in sorted(component_edges.get(idx, set()), key=key):
            indegree[dst] -= 1
            if indegree[dst] == 0:
                ready.append(dst)
        ready.sort(key=key)

    if len(ordered) != len(components):
        # Should not happen in SCC condensation DAG; fall back to deterministic order.
        return sorted(components, key=lambda component: component[0] if component else "")

    return [components[idx] for idx in ordered]
