#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Track migration status of Claude skills/agents to Codex."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from datetime import date, datetime, timezone
from pathlib import Path

from .paths import find_repo_root, tracker_file_path
from .tracker_state import (
    ARCHIVED_STATE_FILE,
    build_effective_tracker_state,
    explicit_event_review_state,
    load_tracker_json,
)

REPO_ROOT = find_repo_root()
SOURCE_SKILLS_DIR = REPO_ROOT / ".claude" / "skills"
SOURCE_AGENTS_DIR = REPO_ROOT / ".claude" / "agents"
TARGET_SKILLS_DIR = REPO_ROOT / ".codex" / "skills"
TARGET_AGENTS_DIR = REPO_ROOT / ".codex" / "agents"
STATE_FILE = tracker_file_path(REPO_ROOT)
PUBLIC_STATE_FORMAT_VERSION = "1.0"
REVIEW_RECENCY_START_DATE = date.min
REVIEW_STATES = (
    "not_applicable",
    "pending_native_review",
    "codex_compatible_but_not_native",
    "native",
)

# Example migration-policy overrides for artifacts that should remain visible
# in reports but intentionally stay outside the generated Codex target.
PUBLIC_IGNORE_OVERRIDES = {
    "skill:legacy-source-only-example": (
        "example ignore: source-only workflow intentionally left outside the "
        "generated target"
    ),
    "skill:legacy-maintenance-example": (
        "example ignore: maintenance workflow documented but not migrated"
    ),
}

# Off-limits directory names — mirror check_skill_integrity.py line 63
EXCLUDED_DIR_NAMES = frozenset({".agent", ".agents"})

# Status markers — checked in the first 500-byte header of SKILL.md
ARCHIVED_RE = re.compile(r"\bARCHIVED\b", re.IGNORECASE)
REDIRECTED_RE = re.compile(r"\bREDIRECTED\b", re.IGNORECASE)

# Banner marker written by migrate_claude_workflows_to_codex.py
AUTO_GENERATED_MARKER = "AUTO-GENERATED"
CONDENSED_COUNTERPART_MARKER = "condensed dependency counterpart"


# ── Data model ────────────────────────────────────────────────────────────────


@dataclass
class ArtifactEvidence:
    has_codex_file: bool
    has_source_file: bool
    has_migration_banner: bool
    has_condensed_counterpart_marker: bool
    validator_pass: bool | None  # None until set by external validator


@dataclass
class ArtifactVersion:
    content_sha256: str
    git_commit: str  # fallback: "unknown"


@dataclass
class ArtifactReview:
    state: str  # not_applicable|pending_native_review|codex_compatible_but_not_native|native
    reason: str
    reviewed_at: str | None
    reviewed_by: str | None
    reviewed_content_sha256: str | None
    review_evidence_path: str | None = None
    review_summary: str | None = None


@dataclass
class Artifact:
    artifact_id: str  # "{type}:{name}" e.g. "skill:example-skill"
    artifact_type: str  # "skill" or "agent"
    name: str
    status: (
        str  # pending|blocked|ignored|migrated|native_codex|archived|redirected|removed
    )
    status_reason: str  # deterministic description
    trust_level: str  # trusted_recent|legacy_unverified|not_applicable
    trust_reason: str  # deterministic description of trust classification
    version: ArtifactVersion
    evidence: ArtifactEvidence
    review: ArtifactReview


@dataclass
class Event:
    event_id: str  # sha256(artifact_id + event_type + timestamp)
    artifact_id: str
    event_type: str  # discovered|status_changed|version_changed|reviewed|removed
    timestamp: str  # ISO 8601 UTC
    from_status: str | None
    to_status: str | None
    from_version: str | None
    to_version: str | None
    from_review_state: str | None
    to_review_state: str | None
    review_actor: str | None
    review_evidence_path: str | None = None
    review_summary: str | None = None


@dataclass
class TrackerState:
    schema_version: str
    generated_at: str
    source_system: str  # ".claude"
    target_system: str  # ".codex"
    summary: dict  # {"skill": {"pending": N, "migrated": N, ...}, "agent": {...}}
    artifacts: list  # List[Artifact]
    events: list  # List[Event] — append-only history


# ── Directory scanner ─────────────────────────────────────────────────────────


def _is_excluded(path: Path) -> bool:
    """Return True if any path component is in EXCLUDED_DIR_NAMES.

    Mirrors the is_excluded() helper in check_skill_integrity.py (line 66-67).
    """
    return bool(EXCLUDED_DIR_NAMES & set(path.parts))


def make_event(artifact_id: str, event_type: str, **kwargs) -> Event:
    """Create a deterministic event envelope with a fresh timestamp."""
    timestamp = datetime.now(timezone.utc).isoformat()
    raw = f"{artifact_id}:{event_type}:{timestamp}"
    event_id = hashlib.sha256(raw.encode()).hexdigest()[:16]
    return Event(
        event_id=event_id,
        artifact_id=artifact_id,
        event_type=event_type,
        timestamp=timestamp,
        from_status=kwargs.get("from_status"),
        to_status=kwargs.get("to_status"),
        from_version=kwargs.get("from_version"),
        to_version=kwargs.get("to_version"),
        from_review_state=kwargs.get("from_review_state"),
        to_review_state=kwargs.get("to_review_state"),
        review_actor=kwargs.get("review_actor"),
        review_evidence_path=kwargs.get("review_evidence_path"),
        review_summary=kwargs.get("review_summary"),
    )


def scan_directories() -> dict:
    """Return sets of names for each location.

    Returns:
        {
            "claude_skills": set[str],
            "claude_agents": set[str],
            "codex_skills":  set[str],
            "codex_agents":  set[str],
        }
    """
    result: dict[str, set[str]] = {
        "claude_skills": set(),
        "claude_agents": set(),
        "codex_skills": set(),
        "codex_agents": set(),
    }

    # .claude/skills/*/SKILL.md — skill name is the directory name
    if SOURCE_SKILLS_DIR.exists():
        for skill_md in SOURCE_SKILLS_DIR.rglob("SKILL.md"):
            if _is_excluded(skill_md):
                continue
            result["claude_skills"].add(skill_md.parent.name)

    # .claude/agents/*.md — agent name is the file stem
    if SOURCE_AGENTS_DIR.exists():
        for agent_file in SOURCE_AGENTS_DIR.glob("*.md"):
            if _is_excluded(agent_file):
                continue
            result["claude_agents"].add(agent_file.stem)

    # .codex/skills/*/SKILL.md — skill name is the directory name
    if TARGET_SKILLS_DIR.exists():
        for skill_md in TARGET_SKILLS_DIR.rglob("SKILL.md"):
            if _is_excluded(skill_md):
                continue
            result["codex_skills"].add(skill_md.parent.name)

    # .codex/agents/*.{md,toml} — agent name is the file stem
    if TARGET_AGENTS_DIR.exists():
        for pattern in ("*.md", "*.toml"):
            for agent_file in TARGET_AGENTS_DIR.glob(pattern):
                if _is_excluded(agent_file):
                    continue
                result["codex_agents"].add(agent_file.stem)

    return result


# ── Status derivation engine ──────────────────────────────────────────────────


def _read_skill_header(path: Path, max_bytes: int = 500) -> str:
    """Read the first ``max_bytes`` bytes of a SKILL.md for marker detection.

    The ARCHIVED/REDIRECTED markers appear in the YAML frontmatter
    ``description`` field rather than as a bare first line.  Scanning the
    header block (matching the pattern used by check_skill_integrity.py
    line 247-248) is the correct approach.

    Returns "" on any I/O error.
    """
    try:
        with path.open(encoding="utf-8") as fh:
            return fh.read(max_bytes)
    except OSError:
        return ""


def derive_status(
    name: str,
    artifact_type: str,
    claude_names: set,
    codex_names: set,
    previous_ids: set,
    skill_path: Path | None = None,
) -> tuple[str, str]:
    """Return (status, status_reason) using the precedence ladder.

    Precedence (first match wins):
      1. archived      — SKILL.md header contains \\bARCHIVED\\b
      2. redirected    — SKILL.md header contains \\bREDIRECTED\\b
      3. ignored       — intentionally excluded from migration policy
      4. migrated      — same-name overlap in .claude and .codex
      5. native_codex  — exists only in .codex
      6. removed       — in previous JSON but not found on disk
      7. pending       — exists only in .claude
    """
    # Steps 1 & 2 apply to skills only (agents have no SKILL.md)
    if artifact_type == "skill" and skill_path is not None and skill_path.exists():
        header = _read_skill_header(skill_path)
        if ARCHIVED_RE.search(header):
            return (
                "archived",
                "SKILL.md header (first 500 bytes) contains ARCHIVED marker",
            )
        if REDIRECTED_RE.search(header):
            return (
                "redirected",
                "SKILL.md header (first 500 bytes) contains REDIRECTED marker",
            )

    in_claude = name in claude_names
    in_codex = name in codex_names
    artifact_id = f"{artifact_type}:{name}"

    if artifact_id in PUBLIC_IGNORE_OVERRIDES:
        return ("ignored", PUBLIC_IGNORE_OVERRIDES[artifact_id])
    if in_claude and in_codex:
        return ("migrated", "same-name overlap in .claude and .codex")
    if in_codex and not in_claude:
        return ("native_codex", "exists only in .codex")
    if artifact_id in previous_ids and not in_claude and not in_codex:
        return ("removed", "was in previous tracker but not found on disk")
    return ("pending", "exists only in .claude")


# ── Version computation ───────────────────────────────────────────────────────


def compute_version(paths: list[Path]) -> ArtifactVersion:
    """Compute content_sha256 from sorted file contents and git_commit from git log.

    content_sha256: SHA-256 hash of the concatenated bytes of all existing files,
                    processed in sorted path order for determinism.
    git_commit:     most recent commit hash touching any of the paths; "unknown"
                    if git is unavailable or returns no output.
    """
    hasher = hashlib.sha256()
    for path in sorted(paths):
        if path.exists():
            hasher.update(path.read_bytes())
    content_sha256 = hasher.hexdigest()

    git_commit = "unknown"
    existing = [str(p) for p in paths if p.exists()]
    if existing:
        try:
            result = subprocess.run(
                ["git", "log", "-1", "--format=%H", "--", *existing],
                capture_output=True,
                text=True,
                cwd=str(REPO_ROOT),
                timeout=10,
            )
            commit = result.stdout.strip()
            if commit:
                git_commit = commit
        except (OSError, subprocess.TimeoutExpired):
            pass

    return ArtifactVersion(content_sha256=content_sha256, git_commit=git_commit)


# ── Evidence collection ───────────────────────────────────────────────────────


def collect_evidence(
    name: str,
    artifact_type: str,
    claude_names: set,
    codex_names: set,
) -> ArtifactEvidence:
    """Collect filesystem evidence for the artifact.

    has_source_file:      name present in claude_names
    has_codex_file:       name present in codex_names
    has_migration_banner: AUTO-GENERATED marker found in the codex file (if any)
    validator_pass:       None — set by external validator
    """
    has_source_file = name in claude_names
    has_codex_file = name in codex_names

    has_migration_banner = False
    has_condensed_counterpart_marker = False
    if has_codex_file:
        if artifact_type == "skill":
            codex_skill_md = TARGET_SKILLS_DIR / name / "SKILL.md"
            try:
                content = codex_skill_md.read_text(encoding="utf-8")
                has_migration_banner = AUTO_GENERATED_MARKER in content
                has_condensed_counterpart_marker = (
                    CONDENSED_COUNTERPART_MARKER in content.lower()
                )
            except OSError:
                pass
        else:
            for codex_agent_file in _codex_agent_files(name):
                try:
                    content = codex_agent_file.read_text(encoding="utf-8")
                    if AUTO_GENERATED_MARKER in content:
                        has_migration_banner = True
                        break
                except OSError:
                    continue

    return ArtifactEvidence(
        has_source_file=has_source_file,
        has_codex_file=has_codex_file,
        has_migration_banner=has_migration_banner,
        has_condensed_counterpart_marker=has_condensed_counterpart_marker,
        validator_pass=None,
    )


def default_review_for_artifact(artifact: Artifact) -> ArtifactReview:
    """Return the default nativeness-review state for an artifact."""
    mechanically_migrated = (
        artifact.evidence.has_codex_file
        and artifact.evidence.has_migration_banner
        and artifact.status in {"migrated", "native_codex"}
    )
    legacy_migrated_agent = (
        artifact.artifact_type == "agent"
        and artifact.status == "migrated"
        and artifact.evidence.has_codex_file
        and artifact.evidence.has_source_file
    )
    if mechanically_migrated:
        return ArtifactReview(
            state="pending_native_review",
            reason="mechanically generated Codex artifact requires recorded nativeness review",
            reviewed_at=None,
            reviewed_by=None,
            reviewed_content_sha256=None,
            review_evidence_path=None,
            review_summary=None,
        )
    if legacy_migrated_agent:
        return ArtifactReview(
            state="pending_native_review",
            reason="legacy migrated agent lacks explicit provenance banner and requires recorded nativeness review",
            reviewed_at=None,
            reviewed_by=None,
            reviewed_content_sha256=None,
            review_evidence_path=None,
            review_summary=None,
        )
    return ArtifactReview(
        state="not_applicable",
        reason="artifact is not a mechanically generated Codex migration target",
        reviewed_at=None,
        reviewed_by=None,
        reviewed_content_sha256=None,
        review_evidence_path=None,
        review_summary=None,
    )


def artifact_status_supports_review(artifact: Artifact) -> bool:
    """Return True when an artifact status is eligible for nativeness review."""
    return artifact.status in {"migrated", "native_codex"}


def explicit_review_reason() -> str:
    """Reason text for a recorded manual nativeness review."""
    return "manual nativeness review recorded for current Codex artifact"


def parse_previous_review(raw_review: dict | None) -> ArtifactReview | None:
    """Normalize an existing serialized review block."""
    if not isinstance(raw_review, dict):
        return None
    state = raw_review.get("state")
    if state not in REVIEW_STATES:
        return None
    return ArtifactReview(
        state=state,
        reason=raw_review.get("reason", ""),
        reviewed_at=raw_review.get("reviewed_at"),
        reviewed_by=raw_review.get("reviewed_by"),
        reviewed_content_sha256=raw_review.get("reviewed_content_sha256"),
        review_evidence_path=raw_review.get("review_evidence_path"),
        review_summary=raw_review.get("review_summary"),
    )


def recover_review_from_events(
    artifact: Artifact,
    existing_events: list[dict],
) -> ArtifactReview | None:
    """Recover review state from legacy reviewed events when no review block exists."""
    latest_event: dict | None = None
    latest_timestamp: datetime | None = None
    for event in existing_events:
        if event.get("artifact_id") != artifact.artifact_id:
            continue
        if event.get("event_type") != "reviewed":
            continue
        if event.get("to_version") != artifact.version.content_sha256:
            continue
        timestamp = _parse_event_timestamp(event.get("timestamp"))
        if timestamp is None:
            continue
        if latest_timestamp is None or timestamp > latest_timestamp:
            latest_timestamp = timestamp
            latest_event = event

    if latest_event is None:
        return None

    state = explicit_event_review_state(latest_event)
    if state is None:
        return None

    return ArtifactReview(
        state=state,
        reason="restored from existing tracker review event",
        reviewed_at=latest_event.get("timestamp"),
        reviewed_by=latest_event.get("review_actor", "manual"),
        reviewed_content_sha256=artifact.version.content_sha256,
        review_evidence_path=latest_event.get("review_evidence_path"),
        review_summary=latest_event.get("review_summary"),
    )


# ── Build artifact list ───────────────────────────────────────────────────────


def _skill_files(name: str) -> list[Path]:
    """Return tracked files for a skill across source and migrated Codex trees.

    For same-name overlap skills, trust and version metadata should move when
    either the Claude source or the Codex artifact changes. Native Codex skills
    still resolve from the Codex tree only.
    """
    paths: list[Path] = []

    claude_dir = SOURCE_SKILLS_DIR / name
    if claude_dir.exists():
        paths.extend(sorted(p for p in claude_dir.rglob("*") if p.is_file()))

    codex_dir = TARGET_SKILLS_DIR / name
    if codex_dir.exists():
        paths.extend(sorted(p for p in codex_dir.rglob("*") if p.is_file()))

    return sorted(paths)


def _agent_files(name: str) -> list[Path]:
    """Return tracked files for an agent across source and migrated Codex trees."""
    paths: list[Path] = []

    claude_path = SOURCE_AGENTS_DIR / f"{name}.md"
    if claude_path.exists():
        paths.append(claude_path)

    paths.extend(_codex_agent_files(name))
    return sorted(paths)


def _codex_agent_files(name: str) -> list[Path]:
    """Return existing Codex agent artifacts for a name, preferring TOML-first semantics."""
    paths: list[Path] = []
    for suffix in (".toml", ".md"):
        candidate = TARGET_AGENTS_DIR / f"{name}{suffix}"
        if candidate.exists():
            paths.append(candidate)
    return paths


def build_artifacts(previous_artifacts: list | None = None) -> list[Artifact]:
    """Scan directories and build a sorted list of all Artifact objects.

    The artifact universe is:
        claude_names | codex_names | {ids from previous_artifacts}

    Phase 2 will pass the previous_artifacts list loaded from the tracker JSON.
    """
    if previous_artifacts is None:
        previous_artifacts = []

    scan = scan_directories()
    claude_skills: set[str] = scan["claude_skills"]
    claude_agents: set[str] = scan["claude_agents"]
    codex_skills: set[str] = scan["codex_skills"]
    codex_agents: set[str] = scan["codex_agents"]

    # Normalize previous_artifacts: accept both Artifact dataclasses and raw dicts
    def _prev_get(item, key: str):
        return item[key] if isinstance(item, dict) else getattr(item, key)

    # Build previous_ids set for "removed" detection
    previous_ids: set[str] = {_prev_get(a, "artifact_id") for a in previous_artifacts}

    # Universe of all names per type
    all_skill_names: set[str] = claude_skills | codex_skills
    all_agent_names: set[str] = claude_agents | codex_agents

    # Add names from previous artifacts that may have been removed from disk
    for prev in previous_artifacts:
        atype = _prev_get(prev, "artifact_type")
        aname = _prev_get(prev, "name")
        if atype == "skill":
            all_skill_names.add(aname)
        elif atype == "agent":
            all_agent_names.add(aname)

    artifacts: list[Artifact] = []

    for name in all_skill_names:
        skill_path = SOURCE_SKILLS_DIR / name / "SKILL.md"
        status, status_reason = derive_status(
            name=name,
            artifact_type="skill",
            claude_names=claude_skills,
            codex_names=codex_skills,
            previous_ids=previous_ids,
            skill_path=skill_path,
        )
        version = compute_version(_skill_files(name))
        evidence = collect_evidence(name, "skill", claude_skills, codex_skills)
        artifacts.append(
            Artifact(
                artifact_id=f"skill:{name}",
                artifact_type="skill",
                name=name,
                status=status,
                status_reason=status_reason,
                trust_level="not_applicable",
                trust_reason="trust tracking applies only to migrated artifacts",
                version=version,
                evidence=evidence,
                review=ArtifactReview(
                    state="not_applicable",
                    reason="review state not initialized",
                    reviewed_at=None,
                    reviewed_by=None,
                    reviewed_content_sha256=None,
                    review_evidence_path=None,
                    review_summary=None,
                ),
            )
        )

    for name in all_agent_names:
        status, status_reason = derive_status(
            name=name,
            artifact_type="agent",
            claude_names=claude_agents,
            codex_names=codex_agents,
            previous_ids=previous_ids,
            skill_path=None,  # agents have no SKILL.md
        )
        version = compute_version(_agent_files(name))
        evidence = collect_evidence(name, "agent", claude_agents, codex_agents)
        artifacts.append(
            Artifact(
                artifact_id=f"agent:{name}",
                artifact_type="agent",
                name=name,
                status=status,
                status_reason=status_reason,
                trust_level="not_applicable",
                trust_reason="trust tracking applies only to migrated artifacts",
                version=version,
                evidence=evidence,
                review=ArtifactReview(
                    state="not_applicable",
                    reason="review state not initialized",
                    reviewed_at=None,
                    reviewed_by=None,
                    reviewed_content_sha256=None,
                    review_evidence_path=None,
                    review_summary=None,
                ),
            )
        )

    # Sort by artifact_id for deterministic output
    artifacts.sort(key=lambda a: a.artifact_id)
    return artifacts


# ── JSON I/O ──────────────────────────────────────────────────────────────────


def load_tracker(path: Path = STATE_FILE) -> dict | None:
    """Load existing tracker JSON. Returns None if file doesn't exist."""
    return load_tracker_json(path)


def save_tracker(state: dict, path: Path = STATE_FILE) -> None:
    """Write tracker JSON with indent=2, sort_keys=True."""
    path.write_text(
        json.dumps(state, indent=2, sort_keys=True, ensure_ascii=False),
        encoding="utf-8",
    )


# ── Artifact / Event serialisation ───────────────────────────────────────────


def artifact_to_dict(a: Artifact) -> dict:
    """Convert Artifact dataclass to JSON-serializable dict."""
    return {
        "artifact_id": a.artifact_id,
        "artifact_type": a.artifact_type,
        "evidence": {
            "has_codex_file": a.evidence.has_codex_file,
            "has_condensed_counterpart_marker": a.evidence.has_condensed_counterpart_marker,
            "has_migration_banner": a.evidence.has_migration_banner,
            "has_source_file": a.evidence.has_source_file,
            "validator_pass": a.evidence.validator_pass,
        },
        "name": a.name,
        "status": a.status,
        "status_reason": a.status_reason,
        "trust_level": a.trust_level,
        "trust_reason": a.trust_reason,
        "review": {
            "reason": a.review.reason,
            "reviewed_at": a.review.reviewed_at,
            "reviewed_by": a.review.reviewed_by,
            "reviewed_content_sha256": a.review.reviewed_content_sha256,
            "review_evidence_path": a.review.review_evidence_path,
            "review_summary": a.review.review_summary,
            "state": a.review.state,
        },
        "version": {
            "content_sha256": a.version.content_sha256,
            "git_commit": a.version.git_commit,
        },
    }


def event_to_dict(e: Event) -> dict:
    """Convert Event dataclass to JSON-serializable dict."""
    return {
        "artifact_id": e.artifact_id,
        "event_id": e.event_id,
        "event_type": e.event_type,
        "from_status": e.from_status,
        "from_version": e.from_version,
        "from_review_state": e.from_review_state,
        "review_actor": e.review_actor,
        "review_evidence_path": e.review_evidence_path,
        "review_summary": e.review_summary,
        "timestamp": e.timestamp,
        "to_review_state": e.to_review_state,
        "to_status": e.to_status,
        "to_version": e.to_version,
    }


# ── Merge logic ───────────────────────────────────────────────────────────────

_ALL_STATUSES = (
    "pending",
    "blocked",
    "ignored",
    "migrated",
    "native_codex",
    "archived",
    "redirected",
    "removed",
)


def _parse_event_timestamp(raw_timestamp: str) -> datetime | None:
    """Return parsed ISO timestamp or None when malformed."""
    try:
        return datetime.fromisoformat(raw_timestamp)
    except (TypeError, ValueError):
        return None


def apply_review_states(
    artifacts: list[Artifact],
    previous_data: dict | None,
) -> list[Artifact]:
    """Apply persisted nativeness-review state and reset on content drift.

    Mechanically generated Codex artifacts default to `pending_native_review`.
    A prior review record is preserved only when the tracked content SHA is
    unchanged. Any content change resets the review state back to pending.
    """
    previous_artifacts: list[dict] = (
        previous_data.get("artifacts", []) if previous_data else []
    )
    previous_by_id: dict[str, dict] = {a["artifact_id"]: a for a in previous_artifacts}
    previous_events: list[dict] = (
        previous_data.get("events", []) if previous_data else []
    )

    for artifact in artifacts:
        default_review = default_review_for_artifact(artifact)
        if not artifact_status_supports_review(artifact):
            artifact.review = default_review
            continue

        previous = previous_by_id.get(artifact.artifact_id)
        previous_review = (
            parse_previous_review(previous.get("review")) if previous else None
        )
        previous_sha = (
            previous.get("version", {}).get("content_sha256") if previous else None
        )

        if previous is not None and previous_sha == artifact.version.content_sha256:
            if (
                previous_review is not None
                and previous_review.state == "not_applicable"
                and default_review.state != "not_applicable"
            ):
                previous_review = None

            if previous_review is not None:
                artifact.review = previous_review
                continue

            recovered_review = recover_review_from_events(artifact, previous_events)
            if recovered_review is not None:
                artifact.review = recovered_review
                continue

        artifact.review = default_review

    return artifacts


def apply_trust_levels(
    artifacts: list[Artifact], all_events: list[dict]
) -> list[Artifact]:
    """Annotate each artifact with a trust level derived from migration events.

    Policy:
    - `trusted_recent`: artifact is currently `migrated` and its most recent
      qualifying migration or explicit review event is on or after <migration-trust-cutoff-date>.
    - qualifying events are:
      - `status_changed` to `migrated`
      - `reviewed`
    - `legacy_unverified`: artifact is currently `migrated` but has no recorded
      qualifying event on or after the cutoff.
    - `not_applicable`: every non-migrated artifact status.
    """
    latest_qualifying_by_artifact: dict[str, tuple[datetime, str]] = {}
    for event in all_events:
        event_type = event.get("event_type")
        if event_type == "status_changed":
            if event.get("to_status") != "migrated":
                continue
            event_reason = "migration"
        elif event_type == "reviewed":
            event_reason = "review"
        else:
            continue

        timestamp = _parse_event_timestamp(event.get("timestamp"))
        if timestamp is None:
            continue
        artifact_id = event["artifact_id"]
        previous = latest_qualifying_by_artifact.get(artifact_id)
        if previous is None or timestamp > previous[0]:
            latest_qualifying_by_artifact[artifact_id] = (timestamp, event_reason)

    for artifact in artifacts:
        if artifact.status != "migrated":
            artifact.trust_level = "not_applicable"
            artifact.trust_reason = "trust tracking applies only to migrated artifacts"
            continue

        if artifact.evidence.has_condensed_counterpart_marker:
            artifact.trust_level = "legacy_unverified"
            artifact.trust_reason = (
                "Codex artifact is explicitly marked as a condensed dependency "
                "counterpart and must not be treated as trusted until it "
                "receives a fuller migration and explicit review"
            )
            continue

        qualifying_event = latest_qualifying_by_artifact.get(artifact.artifact_id)
        if qualifying_event is None:
            artifact.trust_level = "legacy_unverified"
            artifact.trust_reason = "migrated artifact has no recorded migration or explicit review event in tracker history"
            continue

        event_at, event_reason = qualifying_event
        if event_at.date() >= REVIEW_RECENCY_START_DATE:
            artifact.trust_level = "trusted_recent"
            if event_reason == "migration":
                artifact.trust_reason = (
                    f"most recent migration event is {event_at.date().isoformat()}, "
                    f"on or after review recency start {REVIEW_RECENCY_START_DATE.isoformat()}"
                )
            else:
                artifact.trust_reason = (
                    f"most recent review event is {event_at.date().isoformat()}, "
                    f"on or after review recency start {REVIEW_RECENCY_START_DATE.isoformat()}"
                )
        else:
            artifact.trust_level = "legacy_unverified"
            if event_reason == "migration":
                artifact.trust_reason = (
                    f"most recent migration event is {event_at.date().isoformat()}, "
                    f"before review recency start {REVIEW_RECENCY_START_DATE.isoformat()}"
                )
            else:
                artifact.trust_reason = (
                    f"most recent review event is {event_at.date().isoformat()}, "
                    f"before review recency start {REVIEW_RECENCY_START_DATE.isoformat()}"
                )

    return artifacts


def merge_artifacts(
    current: list[Artifact],
    previous_data: dict | None,
) -> tuple[list[Artifact], list[Event]]:
    """Merge current scanned artifacts against previous JSON state.

    Returns (merged_artifacts, new_events).

    Detection:
    - New artifact (artifact_id not in previous): emit "discovered" event
    - Status changed: emit "status_changed" event (from_status, to_status)
    - Version changed: emit "version_changed" event (from_version, to_version)
    - Removed artifact (in previous but not current): emit "removed" event, set status="removed"
    - No change: 0 events (idempotent)
    """
    previous_artifacts: list[dict] = (
        previous_data.get("artifacts", []) if previous_data else []
    )
    previous_by_id: dict[str, dict] = {a["artifact_id"]: a for a in previous_artifacts}

    new_events: list[Event] = []
    merged: list[Artifact] = []

    # Process current artifacts (discovered / changed / unchanged / removed)
    # build_artifacts() already sets status="removed" for artifacts that were in
    # previous_ids but are no longer on disk — so "removed" is handled here,
    # not in a separate second pass. This single loop is the sole removal path.
    for artifact in current:
        aid = artifact.artifact_id
        if aid not in previous_by_id:
            # New artifact (never seen before)
            new_events.append(make_event(aid, "discovered"))
        elif artifact.status == "removed":
            # Artifact was known but is no longer on disk
            new_events.append(make_event(aid, "removed"))
        else:
            prev = previous_by_id[aid]
            prev_status = prev["status"]
            prev_sha = prev["version"]["content_sha256"]
            curr_sha = artifact.version.content_sha256

            if prev_status != artifact.status:
                new_events.append(
                    make_event(
                        aid,
                        "status_changed",
                        from_status=prev_status,
                        to_status=artifact.status,
                    )
                )
            if prev_sha != curr_sha:
                new_events.append(
                    make_event(
                        aid,
                        "version_changed",
                        from_version=prev_sha,
                        to_version=curr_sha,
                    )
                )
        merged.append(artifact)

    # Sort merged list for deterministic output
    merged.sort(key=lambda a: a.artifact_id)
    return merged, new_events


# ── Summary counter computation ───────────────────────────────────────────────


def compute_summary(artifacts: list[Artifact]) -> dict:
    """Group artifact counts by artifact_type x status."""
    summary: dict[str, dict[str, int]] = {
        "agent": dict.fromkeys(_ALL_STATUSES, 0),
        "skill": dict.fromkeys(_ALL_STATUSES, 0),
    }
    for a in artifacts:
        atype = a.artifact_type
        if atype in summary and a.status in summary[atype]:
            summary[atype][a.status] += 1
    return summary


def parse_review_record(record: str) -> tuple[str, str]:
    """Parse `artifact_id=review_state` review CLI input."""
    try:
        artifact_id, outcome = record.rsplit("=", 1)
    except ValueError as exc:
        raise ValueError(
            "Review record must use the form <artifact_id>=<native|codex_compatible_but_not_native>"
        ) from exc

    artifact_id = artifact_id.strip()
    outcome = outcome.strip()
    if not re.fullmatch(r"(skill|agent):[a-z0-9][a-z0-9\-_]*", artifact_id):
        raise ValueError(f"Invalid artifact id for review record: {artifact_id}")
    if outcome not in {"native", "codex_compatible_but_not_native"}:
        raise ValueError(f"Invalid review outcome: {outcome}")
    return artifact_id, outcome


def build_review_record_map(records: list[str]) -> dict[str, str]:
    """Return a map of artifact_id -> review outcome, rejecting duplicates."""
    result: dict[str, str] = {}
    for record in records:
        artifact_id, outcome = parse_review_record(record)
        if artifact_id in result:
            raise ValueError(f"Duplicate review target: {artifact_id}")
        result[artifact_id] = outcome
    return result


def parse_review_metadata_record(record: str) -> tuple[str, str]:
    """Parse `artifact_id=value` review metadata CLI input."""
    try:
        artifact_id, value = record.split("=", 1)
    except ValueError as exc:
        raise ValueError(
            "Review metadata must use the form <artifact_id>=<value>"
        ) from exc

    artifact_id = artifact_id.strip()
    value = value.strip()
    if not re.fullmatch(r"(skill|agent):[a-z0-9][a-z0-9\-_]*", artifact_id):
        raise ValueError(f"Invalid artifact id for review metadata: {artifact_id}")
    if not value:
        raise ValueError("Review metadata value must not be empty")
    return artifact_id, value


def build_review_metadata_map(records: list[str]) -> dict[str, str]:
    """Return a map of artifact_id -> metadata value."""
    result: dict[str, str] = {}
    for record in records:
        artifact_id, value = parse_review_metadata_record(record)
        if artifact_id in result:
            raise ValueError(f"Duplicate review metadata target: {artifact_id}")
        result[artifact_id] = value
    return result


def build_review_events(
    review_records: list[str],
    artifacts: list[Artifact],
    existing_events: list[dict],
    review_actor: str,
    review_evidence_by_id: dict[str, str] | None = None,
    review_summary_by_id: dict[str, str] | None = None,
) -> list[Event]:
    """Create explicit nativeness-review events and update artifact review state."""
    if not review_records:
        return []

    artifact_by_id = {a.artifact_id: a for a in artifacts}
    review_outcomes_by_id = build_review_record_map(review_records)
    review_evidence_by_id = review_evidence_by_id or {}
    review_summary_by_id = review_summary_by_id or {}
    new_events: list[Event] = []

    for artifact_id, outcome in review_outcomes_by_id.items():
        artifact = artifact_by_id.get(artifact_id)
        if artifact is None:
            raise ValueError(f"Unknown artifact for review event: {artifact_id}")
        if artifact.status not in {"migrated", "native_codex"}:
            raise ValueError(
                f"Cannot record review for artifact outside migrated/native_codex states: "
                f"{artifact_id} ({artifact.status})"
            )

        review_evidence_path = review_evidence_by_id.get(artifact_id)
        review_summary = review_summary_by_id.get(artifact_id)
        already_recorded = any(
            event.get("artifact_id") == artifact.artifact_id
            and event.get("event_type") == "reviewed"
            and event.get("to_version") == artifact.version.content_sha256
            and (event.get("to_review_state") or "native") == outcome
            and event.get("review_evidence_path") == review_evidence_path
            and event.get("review_summary") == review_summary
            for event in existing_events
        )
        if already_recorded:
            artifact.review = ArtifactReview(
                state=outcome,
                reason=explicit_review_reason(),
                reviewed_at=artifact.review.reviewed_at,
                reviewed_by=artifact.review.reviewed_by or review_actor,
                reviewed_content_sha256=artifact.version.content_sha256,
                review_evidence_path=review_evidence_path
                or artifact.review.review_evidence_path,
                review_summary=review_summary or artifact.review.review_summary,
            )
            continue

        review_event = make_event(
            artifact.artifact_id,
            "reviewed",
            from_review_state=artifact.review.state,
            to_review_state=outcome,
            to_version=artifact.version.content_sha256,
            review_actor=review_actor,
            review_evidence_path=review_evidence_path,
            review_summary=review_summary,
        )
        new_events.append(review_event)
        artifact.review = ArtifactReview(
            state=outcome,
            reason=explicit_review_reason(),
            reviewed_at=review_event.timestamp,
            reviewed_by=review_actor,
            reviewed_content_sha256=artifact.version.content_sha256,
            review_evidence_path=review_evidence_path,
            review_summary=review_summary,
        )

    return new_events


# ── Main ──────────────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Track .claude → .codex migration status"
    )
    parser.add_argument(
        "--record-review",
        action="append",
        default=[],
        help=(
            "Record a nativeness review outcome in the form "
            "`skill:name=native` or `agent:name=codex_compatible_but_not_native` "
            "(repeatable, --write only)"
        ),
    )
    parser.add_argument(
        "--review-skill",
        action="append",
        default=[],
        help=(
            "Deprecated alias for `--record-review skill:<name>=native` "
            "(repeatable, --write only)"
        ),
    )
    parser.add_argument(
        "--reviewer",
        default="manual",
        help="Identifier recorded with nativeness review events (default: manual)",
    )
    parser.add_argument(
        "--review-evidence",
        action="append",
        default=[],
        help=(
            "Attach review evidence in the form "
            "`skill:name=/path/to/review-report.md` or `agent:name=/path/to/review-report.md` "
            "(repeatable, --write only)"
        ),
    )
    parser.add_argument(
        "--review-summary",
        action="append",
        default=[],
        help=(
            "Attach a compact review summary in the form "
            '`skill:name="No findings after convergence"` '
            "(repeatable, --write only)"
        ),
    )
    mode_group = parser.add_mutually_exclusive_group()
    mode_group.add_argument(
        "--write",
        action="store_true",
        help="Scan and write tracker JSON",
    )
    mode_group.add_argument(
        "--check",
        action="store_true",
        help="Check if tracker is up-to-date (CI mode, exits non-zero if stale)",
    )
    args = parser.parse_args(argv)

    legacy_review_records = [f"skill:{name}=native" for name in args.review_skill]
    review_records = [*legacy_review_records, *args.record_review]

    if (
        review_records or args.review_evidence or args.review_summary
    ) and not args.write:
        parser.error(
            "--record-review/--review-skill/--review-evidence/--review-summary require --write"
        )

    try:
        review_outcomes_by_id = build_review_record_map(review_records)
        review_evidence_by_id = build_review_metadata_map(args.review_evidence)
        review_summary_by_id = build_review_metadata_map(args.review_summary)
    except ValueError as exc:
        parser.error(str(exc))

    review_records = [
        f"{artifact_id}={outcome}"
        for artifact_id, outcome in review_outcomes_by_id.items()
    ]
    review_target_ids = set(review_outcomes_by_id)
    unexpected_review_evidence = sorted(set(review_evidence_by_id) - review_target_ids)
    unexpected_review_summaries = sorted(set(review_summary_by_id) - review_target_ids)
    if unexpected_review_evidence:
        parser.error(
            "--review-evidence requires matching --record-review targets for: "
            + ", ".join(unexpected_review_evidence)
        )
    if unexpected_review_summaries:
        parser.error(
            "--review-summary requires matching --record-review targets for: "
            + ", ".join(unexpected_review_summaries)
        )

    if args.write:
        previous_data = load_tracker()
        effective_previous_data, tracker_integrity = build_effective_tracker_state(
            previous_data,
            load_tracker(ARCHIVED_STATE_FILE),
        )
        previous_artifacts = previous_data.get("artifacts", []) if previous_data else []
        current = build_artifacts(previous_artifacts)
        merged, new_events = merge_artifacts(current, previous_data)
        merged = apply_review_states(merged, effective_previous_data)
        existing_events = (
            effective_previous_data.get("events", []) if effective_previous_data else []
        )
        review_events = build_review_events(
            review_records,
            merged,
            existing_events,
            args.reviewer,
            review_evidence_by_id=review_evidence_by_id,
            review_summary_by_id=review_summary_by_id,
        )
        all_events = existing_events + [
            event_to_dict(e) for e in (new_events + review_events)
        ]
        merged = apply_trust_levels(merged, all_events)

        state = {
            "schema_version": PUBLIC_STATE_FORMAT_VERSION,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "source_system": ".claude",
            "target_system": ".codex",
            "trust_policy": {
                "recent_review_cutoff": REVIEW_RECENCY_START_DATE.isoformat(),
                "trusted_level": "trusted_recent",
                "untrusted_level": "legacy_unverified",
            },
            "review_policy": {
                "mechanical_migrations_require_manual_nativeness_review": True,
                "default_state": "pending_native_review",
                "recorded_outcomes": [
                    "codex_compatible_but_not_native",
                    "native",
                ],
                "optional_review_metadata": [
                    "review_evidence_path",
                    "review_summary",
                ],
            },
            "summary": compute_summary(merged),
            "artifacts": [artifact_to_dict(a) for a in merged],
            "events": all_events,
        }
        save_tracker(state)
        print(
            f"Tracker written: {len(merged)} artifacts, "
            f"{len(new_events) + len(review_events)} new events"
        )
        if review_events:
            print("  recorded reviews: " + ", ".join(sorted(set(review_records))))
        if tracker_integrity["recovered_review_artifact_ids"]:
            print(
                "  recovered archived reviews: "
                + ", ".join(tracker_integrity["recovered_review_artifact_ids"])
            )
        if tracker_integrity["recovery_conflicts"]:
            print("  archived review conflicts:")
            for detail in tracker_integrity["recovery_conflicts"]:
                print(f"    - {detail}")
        for atype in ("skill", "agent"):
            counts = state["summary"][atype]
            parts = ", ".join(f"{v} {k}" for k, v in counts.items())
            print(f"  {atype}: {parts}")
        migrated_artifacts = state["artifacts"]
        trusted_recent = sum(
            1
            for artifact in migrated_artifacts
            if artifact["status"] == "migrated"
            and artifact["trust_level"] == "trusted_recent"
        )
        legacy_unverified = sum(
            1
            for artifact in migrated_artifacts
            if artifact["status"] == "migrated"
            and artifact["trust_level"] == "legacy_unverified"
        )
        print(
            "  trust: "
            f"{trusted_recent} trusted_recent, {legacy_unverified} legacy_unverified "
            f"(cutoff {REVIEW_RECENCY_START_DATE.isoformat()})"
        )
        return 0

    if args.check:
        previous_data = load_tracker()
        if previous_data is None:
            print(
                "ERROR: Tracker file not found. Run --write first.",
                file=sys.stderr,
            )
            return 1

        effective_previous_data, _ = build_effective_tracker_state(
            previous_data,
            load_tracker(ARCHIVED_STATE_FILE),
        )
        previous_artifacts = previous_data.get("artifacts", [])
        current = build_artifacts(previous_artifacts)
        current = apply_review_states(current, effective_previous_data)
        current = apply_trust_levels(
            current,
            effective_previous_data.get("events", [])
            if effective_previous_data
            else [],
        )

        current_comparable = {
            a.artifact_id: (
                a.status,
                a.version.content_sha256,
                a.trust_level,
                a.review.state,
                a.review.reviewed_content_sha256,
                a.review.review_evidence_path,
                a.review.review_summary,
            )
            for a in current
        }
        previous_comparable = {
            a["artifact_id"]: (
                a["status"],
                a["version"]["content_sha256"],
                a.get("trust_level", "not_applicable"),
                a.get("review", {}).get("state", "not_applicable"),
                a.get("review", {}).get("reviewed_content_sha256"),
                a.get("review", {}).get("review_evidence_path"),
                a.get("review", {}).get("review_summary"),
            )
            for a in previous_artifacts
        }

        if current_comparable == previous_comparable:
            print("Tracker is up-to-date.")
            return 0
        else:
            added = set(current_comparable) - set(previous_comparable)
            removed = set(previous_comparable) - set(current_comparable)
            changed = {
                k
                for k in current_comparable.keys() & previous_comparable.keys()
                if current_comparable[k] != previous_comparable[k]
            }
            print(
                "ERROR: Tracker is stale. Run: python3 tools/migration_support/tracker.py --write",
                file=sys.stderr,
            )
            if added:
                print(f"  New artifacts: {sorted(added)}", file=sys.stderr)
            if removed:
                print(f"  Removed artifacts: {sorted(removed)}", file=sys.stderr)
            if changed:
                print(f"  Changed artifacts: {sorted(changed)}", file=sys.stderr)
            return 1

    # Default: smoke-test the scan and report counts
    artifacts = build_artifacts()
    skill_count = sum(1 for a in artifacts if a.artifact_type == "skill")
    agent_count = sum(1 for a in artifacts if a.artifact_type == "agent")
    print(f"Scanned {skill_count} skill(s), {agent_count} agent(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
