# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Public tracker CLI wrapper for migration-state.json."""

from __future__ import annotations

import sys
from pathlib import Path

_SUPPORT_ROOT = Path(__file__).resolve().parents[1]
if str(_SUPPORT_ROOT) not in sys.path:
    sys.path.append(str(_SUPPORT_ROOT))

from migration_support import tracker_cli as _tracker_cli  # noqa: E402


def main(argv: list[str] | None = None) -> int:
    return _tracker_cli.main(argv)


if __name__ == "__main__":
    sys.exit(main())
