#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Shared effective-state helpers for migration tracker recovery."""

from __future__ import annotations

import copy
import json
from datetime import datetime
from pathlib import Path

from .paths import archived_tracker_file_path, find_repo_root, tracker_file_path

REPO_ROOT = find_repo_root()
STATE_FILE = tracker_file_path(REPO_ROOT)
ARCHIVED_STATE_FILE = archived_tracker_file_path(REPO_ROOT)

_REVIEWABLE_STATUSES = frozenset({"migrated", "native_codex"})
_EXPLICIT_REVIEW_STATES = frozenset({"native", "codex_compatible_but_not_native"})


def default_tracker_integrity() -> dict[str, object]:
    """Return the default integrity envelope for dashboard/result payloads."""
    return {
        "recovered_from_archived": False,
        "recovered_review_artifact_ids": [],
        "recovery_conflicts": [],
        "actionability": "normal",
    }


def load_tracker_json(path: Path) -> dict | None:
    """Load a tracker JSON file. Returns None when the file is missing."""
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return None


def _parse_timestamp(raw_timestamp: str | None) -> datetime | None:
    try:
        if raw_timestamp is None:
            return None
        return datetime.fromisoformat(raw_timestamp)
    except (TypeError, ValueError):
        return None


def _review_matches_current_sha(review: dict | None, current_sha: str) -> bool:
    if not isinstance(review, dict):
        return False
    state = review.get("state")
    if state not in _EXPLICIT_REVIEW_STATES:
        return False
    return review.get("reviewed_content_sha256") == current_sha


def _artifact_review_candidate(artifact: dict | None, current_sha: str) -> dict | None:
    if not isinstance(artifact, dict):
        return None
    review = artifact.get("review")
    if not _review_matches_current_sha(review, current_sha):
        return None
    return copy.deepcopy(review)


def explicit_event_review_state(event: dict) -> str | None:
    """Return only explicit terminal review outcomes from an event payload."""
    state = event.get("to_review_state")
    if state not in _EXPLICIT_REVIEW_STATES:
        return None
    return state


def _event_review_payload(event: dict, current_sha: str) -> dict:
    state = explicit_event_review_state(event)
    if state is None:
        raise ValueError("archived review event is missing an explicit review state")
    return {
        "state": state,
        "reason": "restored from archived tracker review event",
        "reviewed_at": event.get("timestamp"),
        "reviewed_by": event.get("review_actor", "manual"),
        "reviewed_content_sha256": current_sha,
        "review_evidence_path": event.get("review_evidence_path"),
        "review_summary": event.get("review_summary"),
    }


def _matching_archived_review_events(
    archived_events: list[dict],
    artifact_id: str,
    current_sha: str,
) -> tuple[dict | None, list[dict], str | None]:
    """Return a single event-derived review payload plus matching events.

    Conflicts are detected when more than one explicit outcome is recorded for the
    same artifact and current content SHA in archived review events. Malformed
    events without an explicit review state are ignored.
    """
    matching_events = [
        event
        for event in archived_events
        if event.get("artifact_id") == artifact_id
        and event.get("event_type") == "reviewed"
        and event.get("to_version") == current_sha
        and explicit_event_review_state(event) is not None
    ]
    if not matching_events:
        return None, [], None

    states = sorted({explicit_event_review_state(event) for event in matching_events})
    if len(states) > 1:
        return (
            None,
            [],
            (
                f"{artifact_id} has conflicting archived review events for current SHA "
                f"{current_sha[:12]}: {', '.join(states)}"
            ),
        )

    matching_events.sort(
        key=lambda event: (
            _parse_timestamp(event.get("timestamp")) or datetime.min,
            event.get("event_id", ""),
        )
    )
    latest_event = matching_events[-1]
    return (
        _event_review_payload(latest_event, current_sha),
        copy.deepcopy(matching_events),
        None,
    )


def _event_identity(event: dict) -> tuple[object, ...]:
    return (
        event.get("artifact_id"),
        event.get("event_type"),
        event.get("timestamp"),
        event.get("from_review_state"),
        event.get("to_review_state"),
        event.get("from_status"),
        event.get("to_status"),
        event.get("from_version"),
        event.get("to_version"),
        event.get("review_actor"),
        event.get("review_evidence_path"),
        event.get("review_summary"),
    )


def _merge_events(
    live_events: list[dict],
    recovered_events: list[dict],
) -> list[dict]:
    merged = [copy.deepcopy(event) for event in live_events]
    seen = {_event_identity(event) for event in merged}
    for event in recovered_events:
        identity = _event_identity(event)
        if identity in seen:
            continue
        merged.append(copy.deepcopy(event))
        seen.add(identity)
    return merged


def build_effective_tracker_state(
    live_tracker: dict | None,
    archived_tracker: dict | None,
) -> tuple[dict | None, dict[str, object]]:
    """Merge archived explicit review history into the live tracker view."""
    integrity = default_tracker_integrity()
    if live_tracker is None:
        return None, integrity
    if archived_tracker is None:
        return copy.deepcopy(live_tracker), integrity

    effective_tracker = copy.deepcopy(live_tracker)
    archived_by_id = {
        artifact.get("artifact_id"): artifact
        for artifact in archived_tracker.get("artifacts", [])
        if isinstance(artifact, dict) and artifact.get("artifact_id")
    }
    live_events = effective_tracker.get("events", [])
    archived_events = archived_tracker.get("events", [])

    recovered_ids: list[str] = []
    recovery_conflicts: list[str] = []
    recovered_events: list[dict] = []

    for artifact in effective_tracker.get("artifacts", []):
        artifact_id = artifact.get("artifact_id")
        current_sha = artifact.get("version", {}).get("content_sha256")
        status = artifact.get("status")
        if not artifact_id or not current_sha:
            continue
        if status not in _REVIEWABLE_STATUSES:
            continue
        if _review_matches_current_sha(artifact.get("review"), current_sha):
            continue

        archived_artifact = archived_by_id.get(artifact_id)
        artifact_candidate = _artifact_review_candidate(archived_artifact, current_sha)
        event_candidate, matching_events, event_conflict = (
            _matching_archived_review_events(archived_events, artifact_id, current_sha)
        )
        if event_conflict is not None:
            recovery_conflicts.append(event_conflict)
            continue

        if artifact_candidate and event_candidate:
            artifact_state = artifact_candidate["state"]
            event_state = event_candidate["state"]
            if artifact_state != event_state:
                recovery_conflicts.append(
                    f"{artifact_id} has conflicting archived review sources for "
                    f"current SHA {current_sha[:12]}: {artifact_state}, {event_state}"
                )
                continue

        candidate = event_candidate or artifact_candidate
        if candidate is None:
            continue

        artifact["review"] = copy.deepcopy(candidate)
        recovered_ids.append(artifact_id)
        recovered_events.extend(matching_events)

    effective_tracker["events"] = _merge_events(live_events, recovered_events)

    if recovered_ids:
        integrity["recovered_from_archived"] = True
        integrity["recovered_review_artifact_ids"] = sorted(set(recovered_ids))
        integrity["actionability"] = "warning"
    if recovery_conflicts:
        integrity["recovery_conflicts"] = sorted(set(recovery_conflicts))
        integrity["actionability"] = "blocked"

    return effective_tracker, integrity


def load_effective_tracker_state(
    live_path: Path = STATE_FILE,
    archived_path: Path = ARCHIVED_STATE_FILE,
) -> tuple[dict | None, dict[str, object]]:
    """Load live + archived trackers and return the effective merged state."""
    live_tracker = load_tracker_json(live_path)
    archived_tracker = load_tracker_json(archived_path)
    return build_effective_tracker_state(live_tracker, archived_tracker)
