# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Public validator CLI wrapper for migrated Codex skill names."""

from __future__ import annotations

import runpy
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
VALIDATOR = (
    REPO_ROOT
    / ".codex"
    / "skills"
    / "verify-skill-migration"
    / "scripts"
    / "validate_skill_migration.py"
)

if __name__ == "__main__":
    runpy.run_path(str(VALIDATOR), run_name="__main__")
