# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path


SCRIPT_PATH = (
    Path(__file__).resolve().parents[1] / "scripts" / "migrate_claude_workflows_to_codex.py"
)
SPEC = importlib.util.spec_from_file_location("migrate_claude_workflows_to_codex", SCRIPT_PATH)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
sys.modules[SPEC.name] = MODULE
SPEC.loader.exec_module(MODULE)


class CodexRuntimeInstallationTests(unittest.TestCase):
    def test_install_runtime_assets_writes_hook_and_script(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            codex_home = Path(tmpdir) / ".codex"
            claude_home = Path(tmpdir) / ".claude"
            codex_home.mkdir()
            claude_home.mkdir()
            (claude_home / "notify.sh").write_text("#!/bin/bash\necho notify\n", encoding="utf-8")

            runtime_plan = MODULE.RuntimeInstallPlan(
                files=[
                    MODULE.RuntimeFileCopy(
                        source=claude_home / "notify.sh",
                        relative_target=Path("notify.sh"),
                    )
                ],
                hook_commands=["bash ~/.codex/notify.sh"],
                config_plugins={"superpowers@openai-curated": {"enabled": True}},
            )

            MODULE.install_runtime_assets(runtime_plan, codex_home=codex_home, dry_run=False)

            self.assertTrue((codex_home / "notify.sh").exists())
            self.assertTrue((codex_home / "hooks.json").exists())
            self.assertIn(
                "superpowers@openai-curated",
                (codex_home / "config.toml").read_text(encoding="utf-8"),
            )


if __name__ == "__main__":
    unittest.main()
