#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Migrate Claude agent definitions to Codex-compatible markdown or TOML.

Transforms .claude/agents/*.md (YAML frontmatter + body) into
.codex/agents/*.toml (native Codex custom agent config) or
.codex/agents/*.md (backward-compatible pure markdown).

Reuses MCP namespace normalization and primitive mapping from the shared
migration support package.

Usage:
  python3 .codex/skills/migrate-agents-to-codex/scripts/migrate_claude_agents_to_codex.py --agent example-agent-a
  python3 .codex/skills/migrate-agents-to-codex/scripts/migrate_claude_agents_to_codex.py --all --format toml
  python3 .codex/skills/migrate-agents-to-codex/scripts/migrate_claude_agents_to_codex.py --all --dry-run --format toml
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

import tomllib

MIN_SUPPORTED_PYTHON = (3, 11)


def _python_version_label(version_info: tuple[int, ...] | object) -> str:
    major = getattr(version_info, "major", None)
    minor = getattr(version_info, "minor", None)
    micro = getattr(version_info, "micro", None)
    if major is not None and minor is not None:
        if micro is not None:
            return f"{major}.{minor}.{micro}"
        return f"{major}.{minor}"
    seq = tuple(version_info)  # type: ignore[arg-type]
    if len(seq) >= 3:
        return f"{seq[0]}.{seq[1]}.{seq[2]}"
    if len(seq) >= 2:
        return f"{seq[0]}.{seq[1]}"
    return ".".join(str(part) for part in seq)


def _require_supported_python(version_info: tuple[int, ...] | object | None = None) -> None:
    current = version_info or sys.version_info
    current_tuple = (
        current.major,
        current.minor,
    ) if hasattr(current, "major") else tuple(current[:2])  # type: ignore[index]
    if current_tuple < MIN_SUPPORTED_PYTHON:
        detected = _python_version_label(current)
        required = ".".join(str(part) for part in MIN_SUPPORTED_PYTHON)
        raise SystemExit(
            "The agent migration scripts require Python "
            f"{required}+; detected {detected}."
        )


_require_supported_python()


def _find_repo_root() -> Path:
    p = Path(__file__).resolve().parent
    while p != p.parent:
        if (p / ".git").exists() or (p / "package.json").exists():
            return p
        p = p.parent
    raise RuntimeError("Repository root not found")


REPO_ROOT = _find_repo_root()

# Import shared migration support primitives
_SUPPORT_SRC = REPO_ROOT / "tools"
if str(_SUPPORT_SRC) not in sys.path:
    sys.path.append(str(_SUPPORT_SRC))
from migration_support.primitives import (  # noqa: E402
    apply_primitive_mappings,
    normalize_mcp_namespaces,
)
from migration_support.sanitize import validate_artifact_name  # noqa: E402

SOURCE_AGENTS_DIR = REPO_ROOT / ".claude" / "agents"
TARGET_AGENTS_DIR = REPO_ROOT / ".codex" / "agents"
TARGET_SKILLS_DIR = REPO_ROOT / ".codex" / "skills"
CODEX_REFS_DIR = TARGET_AGENTS_DIR / "references"
CODEX_CONFIG_PATH = REPO_ROOT / ".codex" / "config.toml"

# Absolute path prefix to strip from body content
ABS_PATH_PREFIX = f"{REPO_ROOT}/"

# Exact tool names that indicate file-write capability (not substrings)
WRITE_TOOLS = {"Write", "Edit", "MultiEdit", "NotebookEdit"}

# Output contract heading keywords (broadened per Codex review #6)
OUTPUT_HEADING_KEYWORDS = [
    "output", "report", "completion", "format", "contract",
    "review criteria", "review process", "diagnostic protocol",
    "verification workflow",
]

FRONTMATTER_KEY_ALIASES = {
    "disallowed_tools": "disallowedTools",
    "permission_mode": "permissionMode",
    "initial_prompt": "initialPrompt",
    "max_turns": "maxTurns",
    "reasoning_effort": "model_reasoning_effort",
}

VALID_REASONING_EFFORTS = {"low", "medium", "high", "xhigh"}
UNSUPPORTED_SOURCE_MCP_SERVERS = {"ide"}


@dataclass
class AgentClassification:
    agent: str
    tier: int
    readiness_score: int
    signals: list[str] = field(default_factory=list)
    mcp_servers: list[str] = field(default_factory=list)
    mcp_tools: list[str] = field(default_factory=list)
    hooks_used: bool = False
    line_count: int = 0
    sandbox_recommendation: str = "read-only"
    skip_reason: str | None = None
    already_migrated: bool = False
    required_mcp_servers: list[str] = field(default_factory=list)
    configured_mcp_servers: list[str] = field(default_factory=list)
    missing_mcp_servers: list[str] = field(default_factory=list)
    unsupported_mcp_servers: list[str] = field(default_factory=list)
    valid_skill_refs: list[str] = field(default_factory=list)
    missing_skill_refs: list[str] = field(default_factory=list)


@dataclass
class PreparedMigration:
    name: str
    classification: AgentClassification
    output: str | None = None
    target_path: Path | None = None
    companion: str | None = None

    @property
    def blocked(self) -> bool:
        return bool(self.classification.missing_mcp_servers)

    @property
    def writable(self) -> bool:
        return (
            self.output is not None
            and self.target_path is not None
            and not self.classification.already_migrated
            and self.classification.tier > 0
        )


def canonicalize_frontmatter(frontmatter: dict) -> dict:
    """Normalize alternate frontmatter key spellings to canonical names."""
    normalized = dict(frontmatter)
    for source_key, target_key in FRONTMATTER_KEY_ALIASES.items():
        if source_key in normalized and target_key not in normalized:
            normalized[target_key] = normalized[source_key]
    return normalized


def parse_yaml_frontmatter(frontmatter_text: str) -> dict | None:
    """Parse YAML frontmatter into a dict, returning None on failure."""
    # Try pyyaml first (handles block scalars, nested maps correctly)
    try:
        import yaml
        fm = yaml.safe_load(frontmatter_text)
        if not isinstance(fm, dict):
            return None
        return fm
    except ImportError:
        pass
    except Exception:
        pass

    # Fallback: indentation-aware manual parsing
    fm: dict = {}
    current_key: str | None = None
    for line in frontmatter_text.split("\n"):
        if not line.strip():
            continue

        # Top-level key detection
        match = re.match(r"^(\w[\w-]*):\s*(.*)", line)
        if match:
            key = match.group(1)
            value = match.group(2).strip()

            if value == "" or value in ("|", ">", ">-"):
                current_key = key
                fm[key] = [] if value == "" else ""
            else:
                if value.startswith('"') and value.endswith('"'):
                    value = value[1:-1]
                elif value.startswith("'") and value.endswith("'"):
                    value = value[1:-1]
                fm[key] = value
                current_key = key
        elif line.strip().startswith("- ") and current_key:
            item = line.strip()[2:].strip()
            if isinstance(fm.get(current_key), list):
                fm[current_key].append(item)
            elif not isinstance(fm.get(current_key), list):
                # Nested structure under a non-list key (e.g., hooks) — skip
                pass
        elif current_key and isinstance(fm.get(current_key), str):
            # Block scalar continuation
            fm[current_key] += " " + line.strip()

    # Clean up multi-line strings
    for k, v in fm.items():
        if isinstance(v, str):
            fm[k] = v.strip()

    return fm or None


def parse_toml_frontmatter(frontmatter_text: str) -> dict | None:
    """Parse TOML frontmatter into a dict, returning None on failure."""
    try:
        parsed = tomllib.loads(frontmatter_text)
    except Exception:
        return None
    if not isinstance(parsed, dict):
        return None
    return parsed


def parse_agent_frontmatter(content: str) -> tuple[dict, str]:
    """Split YAML or TOML frontmatter from markdown body."""
    match = re.match(
        r"^(?P<delimiter>---|\+\+\+)\r?\n(?P<frontmatter>.*?)(?:\r?\n)(?P=delimiter)(?:\r?\n)?(?P<body>.*)$",
        content,
        re.DOTALL,
    )
    if not match:
        return {}, content

    delimiter = match.group("delimiter")
    frontmatter_text = match.group("frontmatter")
    body = match.group("body").strip()
    parsers = [parse_yaml_frontmatter, parse_toml_frontmatter]
    if delimiter == "+++":
        parsers = [parse_toml_frontmatter, parse_yaml_frontmatter]

    for parser in parsers:
        parsed = parser(frontmatter_text)
        if parsed is not None:
            return canonicalize_frontmatter(parsed), body

    return {}, body


def tokenize_tools(tools_str: str) -> set[str]:
    """Split comma-separated tools string into exact tool names."""
    return {t.strip() for t in tools_str.split(",") if t.strip()}


def normalize_mcp_server_compare_key(server_id: str) -> str:
    """Normalize an MCP server id for underscore/hyphen-insensitive comparison."""
    return server_id.replace("_", "-").lower()


def default_config_key_form(server_id: str) -> str:
    """Convert tool-namespace server ids to the default config-key form."""
    return server_id.replace("_", "-")


def load_project_mcp_server_ids(config_path: Path | None = None) -> list[str]:
    """Read only top-level mcp server ids from project .codex/config.toml."""
    config_path = config_path or CODEX_CONFIG_PATH
    parsed = tomllib.loads(config_path.read_text(encoding="utf-8"))
    mcp_servers = parsed.get("mcp_servers", {})
    if not isinstance(mcp_servers, dict):
        return []
    return sorted(server_id for server_id in mcp_servers if isinstance(server_id, str))


def resolve_mcp_dependencies(
    tools_str: str,
    available_server_ids: list[str],
) -> tuple[list[str], list[str], list[str], list[str]]:
    """Resolve required/configured/missing MCP servers from frontmatter tools."""
    configured_by_key = {
        normalize_mcp_server_compare_key(server_id): server_id
        for server_id in available_server_ids
    }
    required_by_key: dict[str, str] = {}
    unsupported_by_key: dict[str, str] = {}
    for match in re.finditer(r"mcp__([A-Za-z0-9_-]+)__([\w-]+)", tools_str):
        raw_server_id = match.group(1)
        compare_key = normalize_mcp_server_compare_key(raw_server_id)
        if compare_key in UNSUPPORTED_SOURCE_MCP_SERVERS:
            unsupported_by_key.setdefault(compare_key, default_config_key_form(raw_server_id))
            continue
        required_by_key.setdefault(
            compare_key,
            configured_by_key.get(compare_key, default_config_key_form(raw_server_id)),
        )

    required = [required_by_key[key] for key in sorted(required_by_key)]
    configured = [server_id for server_id in required if normalize_mcp_server_compare_key(server_id) in configured_by_key]
    missing = [server_id for server_id in required if normalize_mcp_server_compare_key(server_id) not in configured_by_key]
    unsupported = [unsupported_by_key[key] for key in sorted(unsupported_by_key)]
    return required, configured, missing, unsupported


def count_mcp_tools(tools_str: str) -> tuple[int, list[str], list[str]]:
    """Count MCP tools, extract server names, and full tool names."""
    servers = set()
    tool_names = []
    count = 0
    for match in re.finditer(r"mcp__([A-Za-z0-9_-]+)__([\w-]+)", tools_str):
        server = match.group(1)
        tool = match.group(2)
        servers.add(default_config_key_form(server))
        tool_names.append(tool)
        count += 1
    return count, sorted(servers), tool_names


def has_gemini_tool(mcp_tool_names: list[str]) -> bool:
    """Check if agent has Gemini access via actual tool names (not server names)."""
    return any("gemini" in t.lower() for t in mcp_tool_names)


def existing_output_paths(name: str) -> list[Path]:
    """Return existing markdown and TOML outputs for an agent name."""
    return [
        path for path in (
            TARGET_AGENTS_DIR / f"{name}.md",
            TARGET_AGENTS_DIR / f"{name}.toml",
        ) if path.exists()
    ]


def classify_agent(name: str, frontmatter: dict, body: str) -> AgentClassification:
    """Classify agent into tier 1-3 based on frontmatter and body signals."""
    existing_outputs = existing_output_paths(name)
    if existing_outputs:
        return AgentClassification(
            agent=name, tier=0, readiness_score=0,
            skip_reason=f"Already migrated ({', '.join(path.name for path in existing_outputs)})",
            already_migrated=True
        )

    tools_str = frontmatter.get("tools", "")
    disallowed_str = frontmatter.get("disallowedTools", "")
    tools = tokenize_tools(tools_str)
    disallowed = tokenize_tools(disallowed_str)
    mcp_count, mcp_servers, mcp_tool_names = count_mcp_tools(tools_str)

    # Exact tool matching (fix #4: no substring matching)
    has_write = bool(tools & WRITE_TOOLS - disallowed)
    has_hooks = isinstance(frontmatter.get("hooks"), dict) or "Stop" in str(frontmatter.get("hooks", ""))
    has_example_mcp_write = any(t in mcp_tool_names for t in ["save_note", "update_note", "delete_note"])
    has_initial_prompt = bool(frontmatter.get("initialPrompt"))
    has_permission_mode = bool(frontmatter.get("permissionMode"))
    line_count = body.count("\n") + 1

    signals = []
    score = 100
    tier = 1

    if has_hooks and has_write:
        tier = max(tier, 3)
        signals.append("hooks + write tools")
        score -= 15

    if mcp_count >= 20:
        tier = max(tier, 3)
        signals.append(f"{mcp_count} MCP tools")
        score -= 12

    orchestration_keywords = ["Supervisor Pattern", "TaskCreate", "TeamCreate", "spawn_agent", "delegate to"]
    if any(kw.lower() in body.lower() for kw in orchestration_keywords):
        tier = max(tier, 3)
        signals.append("orchestrates other agents")
        score -= 10

    if line_count > 300:
        tier = max(tier, 3)
        signals.append(f"{line_count} lines")
        score -= 10

    if has_write and mcp_count >= 5 and tier < 3:
        tier = max(tier, 2)
        signals.append("write + MCP")
        score -= 8

    if has_example_mcp_write and tier < 3:
        tier = max(tier, 2)
        signals.append("external memory write")
        score -= 6

    if has_initial_prompt and tier < 3:
        tier = max(tier, 2)
        signals.append("initialPrompt")
        score -= 4

    if has_permission_mode:
        signals.append(f"permissionMode: {frontmatter.get('permissionMode', '')}")
        score -= 4

    if mcp_count > 0:
        score -= 3

    # Sandbox inference: only two outcomes are valid for migrated Codex agents:
    # read-only or workspace-write. Even infrastructure-aware roles should stay
    # on workspace-write unless a human explicitly authors something stronger.
    if has_write:
        sandbox = "workspace-write"
    elif has_example_mcp_write:
        sandbox = "workspace-write"
    elif disallowed & {"Edit", "Write"}:
        sandbox = "read-only"
    else:
        sandbox = "read-only"

    return AgentClassification(
        agent=name, tier=tier, readiness_score=max(0, score),
        signals=signals, mcp_servers=mcp_servers, mcp_tools=mcp_tool_names,
        hooks_used=has_hooks, line_count=line_count,
        sandbox_recommendation=sandbox
    )


def strip_absolute_paths(text: str) -> str:
    """Replace absolute repo paths with repo-relative."""
    return text.replace(ABS_PATH_PREFIX, "")


def rewrite_claude_refs(text: str) -> str:
    """Rewrite .claude/ references to .codex/ equivalents (fix #5)."""
    text = re.sub(r"\.claude/skills/", ".codex/skills/", text)
    text = re.sub(r"\.claude/agents/", ".codex/agents/", text)
    text = re.sub(r"\.claude/commands/", "[REVIEW: .claude/commands/ has no Codex equivalent] ", text)
    return text


def map_model_to_runtime(model: str, effort: str) -> str:
    """Map Claude model+effort to advisory runtime config text."""
    raw_model = (model or "").strip()
    normalized_model = raw_model.lower()
    effort_value = normalize_reasoning_effort(effort)
    if "opus" in normalized_model:
        return f"`gpt-5.4` with `{effort_value or 'high'}` reasoning effort"
    if "sonnet" in normalized_model:
        return f"`gpt-5.4` with `{effort_value or 'medium'}` reasoning effort"
    if "haiku" in normalized_model or "haiko" in normalized_model:
        return f"`gpt-5.4-mini` with `{effort_value or 'medium'}` reasoning effort"
    if normalized_model == "inherit" or not normalized_model:
        if effort_value:
            return f"inherits from parent session with `{effort_value}` reasoning effort"
        return "inherits from parent session"
    if effort_value:
        return f"`{raw_model}` with `{effort_value}` reasoning effort"
    return f"`{raw_model}`"


def normalize_reasoning_effort(effort: str | None) -> str | None:
    """Normalize supported reasoning-effort values."""
    normalized_effort = (effort or "").lower().strip()
    if normalized_effort in VALID_REASONING_EFFORTS:
        return normalized_effort
    return None


def get_model_reasoning_effort(frontmatter: dict) -> str:
    """Read reasoning effort from modern and legacy frontmatter keys."""
    for key in ("model_reasoning_effort", "reasoning_effort", "effort"):
        value = frontmatter.get(key)
        if value not in (None, ""):
            return str(value)
    return ""


def map_model_to_codex_config(model: str, effort: str) -> tuple[str | None, str | None]:
    """Map Claude model+effort hints to concrete Codex config fields."""
    normalized_model = (model or "").lower().strip()
    effort_value = normalize_reasoning_effort(effort)

    if "opus" in normalized_model:
        return "gpt-5.4", effort_value or "high"
    if "sonnet" in normalized_model:
        return "gpt-5.4", effort_value or "medium"
    if "haiku" in normalized_model or "haiko" in normalized_model:
        return "gpt-5.4-mini", effort_value or "medium"
    if normalized_model == "inherit" or not normalized_model:
        return None, effort_value
    return normalized_model, effort_value


def map_hooks_to_gate(frontmatter: dict) -> str | None:
    """Extract Stop hook and convert to completion gate text."""
    hooks = frontmatter.get("hooks")
    if not hooks:
        return None
    return "Parent workflow must verify: `npm run build` and `npm run lint` pass"


def map_skills_to_references(skills: list | str) -> tuple[list[str], list[str]]:
    """Map skill names to .codex/skills/ paths. Returns (valid_refs, missing_refs)."""
    if isinstance(skills, str):
        skills = [s.strip() for s in skills.split(",") if s.strip()]
    valid = []
    missing = []
    for s in skills:
        codex_path = TARGET_SKILLS_DIR / s / "SKILL.md"
        ref = f".codex/skills/{s}/SKILL.md"
        if codex_path.exists():
            valid.append(ref)
        else:
            missing.append(ref)
    return valid, missing


def infer_sandbox_rationale(sandbox: str, frontmatter: dict) -> str:
    disallowed = frontmatter.get("disallowedTools", "")
    tools_str = frontmatter.get("tools", "")
    has_example_mcp_write = any(t in tools_str for t in ["save_note", "update_note", "delete_note"])
    if sandbox == "read-only":
        if "Edit" in str(disallowed) or "Write" in str(disallowed):
            return "Agent explicitly disallows file editing tools"
        return "Agent uses only read and analysis tools"
    elif has_example_mcp_write and "Edit" not in tools_str and "Write" not in tools_str.split(",")[0:]:
        return "Agent performs external memory writes but does not edit files"
    return "Agent creates and modifies files within the workspace"


def extract_body_sections(body: str) -> dict[str, str]:
    """Parse markdown body into sections keyed by heading text."""
    sections: dict[str, str] = {}
    current_heading = "_preamble"
    current_lines: list[str] = []

    for line in body.split("\n"):
        heading_match = re.match(r"^(#{1,3})\s+(.+)", line)
        if heading_match:
            if current_lines:
                sections[current_heading] = "\n".join(current_lines).strip()
            current_heading = heading_match.group(2).strip()
            current_lines = []
        else:
            current_lines.append(line)

    if current_lines:
        sections[current_heading] = "\n".join(current_lines).strip()

    return sections


def generate_codex_agent(
    name: str,
    frontmatter: dict,
    body_sections: dict[str, str],
    classification: AgentClassification,
) -> str:
    """Generate Codex agent markdown from parsed Claude agent."""
    title = name.replace("-", " ").title()
    desc = frontmatter.get("description", "Specialized agent for a migrated project.")
    if isinstance(desc, dict):
        desc = str(desc)
    model_text = map_model_to_runtime(
        str(frontmatter.get("model", "")),
        get_model_reasoning_effort(frontmatter),
    )
    sandbox = classification.sandbox_recommendation
    sandbox_rationale = infer_sandbox_rationale(sandbox, frontmatter)
    gate = map_hooks_to_gate(frontmatter)
    skills = frontmatter.get("skills", [])
    valid_refs, missing_refs = map_skills_to_references(skills) if skills else ([], [])
    max_turns = frontmatter.get("maxTurns", "")
    initial_prompt = frontmatter.get("initialPrompt", "")
    disallowed = str(frontmatter.get("disallowedTools", ""))

    lines: list[str] = []
    lines.append(f"# Agent: {title}")
    lines.append("")

    # Purpose
    lines.append("## Purpose")
    lines.append("")
    desc_sentences = re.split(r"(?<=[.!?])\s+", desc)
    lines.append(" ".join(desc_sentences[:3]))
    lines.append("")

    # Use When
    lines.append("## Use When")
    lines.append("")
    lines.append(f"- {desc_sentences[0] if desc_sentences else 'Specialized task delegation'}")
    if classification.tier == 3:
        lines.append("- [TODO: hand-author additional spawn scenarios]")
    lines.append("")

    # Recommended Sandbox
    lines.append("## Recommended Sandbox")
    lines.append("")
    lines.append(f"Mode: `{sandbox}`")
    lines.append(f"Rationale: {sandbox_rationale}")
    lines.append("")

    # Runtime Configuration
    lines.append("## Runtime Configuration")
    lines.append("")
    lines.append(f"- Intended model class: {model_text}")
    if max_turns:
        lines.append(f"- Suggested turn limit: ~{max_turns}")
    else:
        lines.append("- Suggested turn limit: no limit")
    if gate:
        lines.append(f"- Completion gate: {gate}")
    lines.append("- External memory: optional; describe only when configured")
    if classification.required_mcp_servers:
        if classification.missing_mcp_servers:
            lines.append(
                "- MCP dependency status: BLOCKED until project `.codex/config.toml` adds "
                f"{', '.join(classification.missing_mcp_servers)}"
            )
        else:
            lines.append(
                "- MCP dependency status: satisfied by project `.codex/config.toml` "
                f"({', '.join(classification.configured_mcp_servers)})"
            )
    else:
        lines.append("- MCP dependency status: no project-level MCP dependencies declared in frontmatter")
    lines.append("")

    # Initial Action (fix #2: emit initialPrompt with path normalization)
    if initial_prompt:
        lines.append("## Initial Action")
        lines.append("")
        if isinstance(initial_prompt, str) and len(initial_prompt) > 10:
            normalized_prompt = rewrite_claude_refs(strip_absolute_paths(str(initial_prompt)))
            lines.append(f"On spawn, immediately: {normalized_prompt}")
        else:
            lines.append("- [REVIEW: initialPrompt was present but could not be fully parsed]")
        lines.append("")

    # Constraints
    lines.append("## Constraints")
    lines.append("")
    if "Edit" in disallowed or "Write" in disallowed:
        lines.append("- Read-only: do not edit files or propose patches unless explicitly requested")
    if "Bash" in disallowed:
        lines.append("- Do not execute shell commands directly")
    for heading, content in body_sections.items():
        if "anti-pattern" in heading.lower():
            for line in content.split("\n"):
                stripped = line.strip()
                if stripped.startswith("- ") and len(stripped) < 120:
                    lines.append(stripped)
            break
    if classification.tier >= 2:
        lines.append("- [REVIEW: verify constraints match agent's access pattern]")
    lines.append("")

    # Inputs Expected
    lines.append("## Inputs Expected")
    lines.append("")
    lines.append("- Task description from spawning skill or orchestrator")
    lines.append("- Relevant file paths or scope context")
    if classification.tier == 3:
        lines.append("- [TODO: hand-author specific input requirements]")
    lines.append("")

    # Knowledge Priority (fix #3: Gemini from tool names, not server names)
    lines.append("## Knowledge Priority")
    lines.append("")
    lines.append("1. Task-specific skill files passed into the prompt")
    if valid_refs:
        lines.append(f"2. Codex skill references: {', '.join(valid_refs[:3])}")
    else:
        lines.append("2. Existing code and diff evidence")
    lines.append("3. code search for historical and architectural context")
    lines.append("4. optional code-navigation tools for symbol lookup and dependency tracing")
    if has_gemini_tool(classification.mcp_tools):
        lines.append("5. large-context reviewer for cross-service analysis spanning 10+ files")
    lines.append("")

    # Domain sections
    domain_content: list[str] = []
    skip_headings = {
        "_preamble", "anti-patterns", "anti-patterns to avoid",
        "coordination with other agents", "quality checklist",
        "quality assurance coordination", "completion checklist",
        "debugging completion checklist",
    }
    for heading, content in body_sections.items():
        if heading.lower() in skip_headings:
            continue
        if len(content) > 20:
            domain_content.append(f"## {heading}\n\n{content}")

    if domain_content:
        total_domain_lines = sum(c.count("\n") + 1 for c in domain_content)
        if total_domain_lines > 40 or classification.tier == 3:
            lines.append("## Domain Knowledge")
            lines.append("")
            lines.append(f"See `.codex/agents/references/{name}-domain.md` for detailed patterns.")
            if classification.tier == 3:
                lines.append("[TODO: hand-author key domain sections inline]")
            lines.append("")
        else:
            for dc in domain_content[:3]:
                dc_lines = dc.split("\n")
                lines.extend(dc_lines[:15])
                if len(dc_lines) > 15:
                    lines.append(f"[... {len(dc_lines) - 15} lines truncated, see companion ref]")
                lines.append("")

    # Output Contract: find best-matching non-empty section
    # Prefer specific "output format" over broad "review process"
    lines.append("## Output Contract")
    lines.append("")
    found_output = False
    # Priority-ordered keywords: most specific first
    priority_keywords = [
        "output format", "output contract", "output",
        "report", "completion checklist", "format",
    ]
    for kw in priority_keywords:
        for heading, content in body_sections.items():
            if kw in heading.lower() and content.strip():
                for line in content.split("\n")[:10]:
                    lines.append(line)
                found_output = True
                break
        if found_output:
            break
    if not found_output:
        lines.append("- Return structured results appropriate to the task")
        if classification.tier >= 2:
            lines.append("- [REVIEW: define specific output structure from source agent]")
        if classification.tier == 3:
            lines.append("- [TODO: hand-author output contract]")
    lines.append("")

    # References (fix #3: validate paths, flag missing)
    lines.append("## References")
    lines.append("")
    if classification.line_count > 1000:
        lines.append(f"- `.codex/agents/references/{name}-domain.md` — detailed domain patterns")
    for ref in valid_refs:
        skill_name = ref.split("/")[-2]
        lines.append(f"- `{ref}` — {skill_name}")
    for ref in missing_refs:
        skill_name = ref.split("/")[-2]
        lines.append(f"- `{ref}` — {skill_name} [REVIEW: not yet migrated to Codex]")
    if not valid_refs and not missing_refs and classification.tier < 3:
        lines.append("- No specific skill dependencies")
    lines.append("")

    return "\n".join(lines)


def generate_companion_reference(
    name: str,
    body_sections: dict[str, str],
) -> str | None:
    """Generate companion reference file for large agents."""
    skip_headings = {"_preamble"}
    domain_sections = []
    for heading, content in body_sections.items():
        if heading.lower() in skip_headings:
            continue
        if len(content) > 10:
            domain_sections.append(f"## {heading}\n\n{content}")

    if not domain_sections:
        return None

    title = name.replace("-", " ").title()
    header = (
        f"# {title}: Domain Reference\n\n"
        f"Companion reference for `.codex/agents/{name}.toml`.\n"
        "Contains detailed domain knowledge extracted during Codex migration.\n"
        "MCP namespaces normalized. Absolute paths stripped.\n\n"
    )
    body = "\n\n".join(domain_sections)
    # Fix #5: rewrite .claude/ refs to .codex/ equivalents
    body = rewrite_claude_refs(body)
    return header + body


def make_agent_markdown_banner(name: str) -> str:
    """Create a provenance banner for mechanically generated markdown agents."""
    return (
        "<!--\n"
        "AUTO-GENERATED FILE\n"
        f"Source artifact: {name}\n"
        "Generated by: agent migration workflow\n"
        "Notes:\n"
        "- Field mappings and namespace normalization were mechanically applied.\n"
        "- Recorded manual nativeness review is required before this artifact may be treated as native Codex.\n"
        "-->\n\n"
    )


def make_agent_toml_banner(name: str) -> str:
    """Create a provenance banner for mechanically generated TOML agents."""
    return (
        "# AUTO-GENERATED FILE\n"
        f"# Source artifact: {name}\n"
        "# Generated by: agent migration workflow\n"
        "# Notes:\n"
        "# - Field mappings and namespace normalization were mechanically applied.\n"
        "# - Recorded manual nativeness review is required before this artifact may be treated as native Codex.\n\n"
    )


def toml_basic_string(value: str) -> str:
    """Encode a single-line TOML basic string."""
    return json.dumps(value)


def toml_multiline_string(value: str) -> str:
    """Encode a TOML multiline basic string."""
    normalized = value.replace("\r\n", "\n").replace("\r", "\n")
    escaped = normalized.replace("\\", "\\\\").replace('"""', '\\"""')
    return f'"""\n{escaped}\n"""'


def toml_array(values: list[str]) -> str:
    """Encode a TOML array of basic strings."""
    return "[" + ", ".join(json.dumps(value) for value in values) + "]"


def strip_agent_markdown_banner(markdown_output: str) -> str:
    """Remove the generated markdown provenance banner before embedding in TOML."""
    if markdown_output.startswith("<!--\nAUTO-GENERATED FILE\n"):
        end = markdown_output.find("-->\n\n")
        if end != -1:
            return markdown_output[end + len("-->\n\n") :]
    return markdown_output


def generate_codex_agent_toml(
    name: str,
    frontmatter: dict,
    markdown_output: str,
    classification: AgentClassification,
) -> str:
    """Generate Codex custom-agent TOML from normalized migration output."""
    title = name.replace("-", " ").title()
    desc = frontmatter.get("description", "Specialized agent for a migrated project.")
    if isinstance(desc, dict):
        desc = str(desc)
    desc_sentences = re.split(r"(?<=[.!?])\s+", desc)
    description = " ".join(desc_sentences[:3]).strip() or f"{title} role for a migrated project."
    clean_markdown_output = strip_agent_markdown_banner(markdown_output)
    developer_instructions = (
        "\n".join(clean_markdown_output.splitlines()[2:]).strip()
        or clean_markdown_output.strip()
    )
    model_name, model_effort = map_model_to_codex_config(
        str(frontmatter.get("model", "")),
        get_model_reasoning_effort(frontmatter),
    )
    skills = frontmatter.get("skills", [])
    valid_refs, _ = map_skills_to_references(skills) if skills else ([], [])

    lines = [
        f"name = {toml_basic_string(title)}",
        f"description = {toml_basic_string(description)}",
        f"sandbox_mode = {toml_basic_string(classification.sandbox_recommendation)}",
    ]

    if model_name:
        lines.append(f"model = {toml_basic_string(model_name)}")
    if model_effort:
        lines.append(f"model_reasoning_effort = {toml_basic_string(model_effort)}")

    lines.append(f"developer_instructions = {toml_multiline_string(developer_instructions)}")

    if valid_refs:
        lines.append("")
        for ref in valid_refs:
            skill_dir = ref.removesuffix("/SKILL.md")
            lines.append("[[skills.config]]")
            lines.append(f"path = {toml_basic_string(skill_dir)}")
            lines.append("enabled = true")
            lines.append("")

    return make_agent_toml_banner(name) + "\n".join(lines) + "\n"


def validate_toml_output(output: str) -> None:
    """Validate generated TOML output before writing it."""
    parsed = tomllib.loads(output)
    required = ("name", "description", "developer_instructions")
    missing = [key for key in required if not parsed.get(key)]
    if missing:
        raise ValueError(f"Generated TOML missing required keys: {', '.join(missing)}")
    skills = parsed.get("skills")
    if skills is None:
        return
    if not isinstance(skills, dict):
        raise ValueError("Generated TOML has invalid `skills` shape; expected a table")
    config = skills.get("config")
    if config is None:
        return
    if not isinstance(config, list):
        raise ValueError("Generated TOML has invalid `skills.config` shape; expected an array of tables")
    for idx, entry in enumerate(config):
        if not isinstance(entry, dict):
            raise ValueError(f"Generated TOML has invalid `skills.config[{idx}]`; expected a table")
        if not isinstance(entry.get("enabled"), bool):
            raise ValueError(f"Generated TOML missing boolean `enabled` in `skills.config[{idx}]`")
        path = entry.get("path")
        if not isinstance(path, str) or not path:
            raise ValueError(f"Generated TOML missing string `path` in `skills.config[{idx}]`")
        if path.endswith("/SKILL.md"):
            raise ValueError(
                f"Generated TOML uses file path in `skills.config[{idx}].path`; expected skill directory"
            )


def prepare_migration(
    name: str,
    force: bool,
    output_format: str,
    available_mcp_servers: list[str],
) -> PreparedMigration:
    """Build a migration result and MCP dependency status without writing files."""
    validate_artifact_name(name)
    src = SOURCE_AGENTS_DIR / f"{name}.md"
    if not src.exists():
        print(f"ERROR: Source not found: {src}")
        return PreparedMigration(
            name=name,
            classification=AgentClassification(
                agent=name,
                tier=-1,
                readiness_score=0,
                skip_reason="Source not found",
            ),
        )

    content = src.read_text(encoding="utf-8")
    frontmatter, body = parse_agent_frontmatter(content)
    classification = classify_agent(name, frontmatter, body)
    required_mcp_servers, configured_mcp_servers, missing_mcp_servers, unsupported_mcp_servers = resolve_mcp_dependencies(
        str(frontmatter.get("tools", "")),
        available_mcp_servers,
    )
    classification.required_mcp_servers = required_mcp_servers
    classification.configured_mcp_servers = configured_mcp_servers
    classification.missing_mcp_servers = missing_mcp_servers
    classification.unsupported_mcp_servers = unsupported_mcp_servers
    classification.mcp_servers = required_mcp_servers
    skills = frontmatter.get("skills", [])
    valid_skill_refs, missing_skill_refs = map_skills_to_references(skills) if skills else ([], [])
    classification.valid_skill_refs = valid_skill_refs
    classification.missing_skill_refs = missing_skill_refs

    if classification.already_migrated and not force:
        return PreparedMigration(name=name, classification=classification)

    # Apply text transformations to body
    body = normalize_mcp_namespaces(body)
    body = apply_primitive_mappings(body)
    body = strip_absolute_paths(body)
    body = rewrite_claude_refs(body)

    body_sections = extract_body_sections(body)
    markdown_output = (
        make_agent_markdown_banner(name)
        + generate_codex_agent(name, frontmatter, body_sections, classification)
    )
    output = markdown_output
    if output_format == "toml":
        output = generate_codex_agent_toml(name, frontmatter, markdown_output, classification)
        validate_toml_output(output)

    # Generate companion reference if needed
    companion = None
    if classification.line_count > 1000:
        raw_body = rewrite_claude_refs(strip_absolute_paths(normalize_mcp_namespaces(
            apply_primitive_mappings(parse_agent_frontmatter(content)[1])
        )))
        companion = generate_companion_reference(name, extract_body_sections(raw_body))

    target_path = TARGET_AGENTS_DIR / f"{name}.{output_format}"

    return PreparedMigration(
        name=name,
        classification=classification,
        output=output,
        target_path=target_path,
        companion=companion,
    )


def format_mcp_status(classification: AgentClassification) -> str:
    """Format MCP dependency status for reports."""
    if not classification.required_mcp_servers:
        if classification.unsupported_mcp_servers:
            return f"none required; dropped unsupported {', '.join(classification.unsupported_mcp_servers)}"
        return "none required"
    if classification.missing_mcp_servers:
        return f"BLOCKED missing {', '.join(classification.missing_mcp_servers)}"
    status = f"OK ({', '.join(classification.configured_mcp_servers)})"
    if classification.unsupported_mcp_servers:
        status += f"; dropped unsupported {', '.join(classification.unsupported_mcp_servers)}"
    return status


def print_dry_run(plan: PreparedMigration) -> None:
    """Print preview output with MCP dependency status."""
    classification = plan.classification
    if classification.already_migrated and plan.output is None:
        print(f"SKIP: {plan.name} (already migrated, use --force to overwrite)")
        print(f"MCP dependency status: {format_mcp_status(classification)}")
        return

    tier_label = {1: "MECHANICAL", 2: "ASSISTED", 3: "SKELETON"}
    status = tier_label.get(classification.tier, "UNKNOWN")
    print(f"\n{'='*60}")
    print(f"[DRY RUN] {plan.name} (Tier {classification.tier}: {status})")
    print(f"Score: {classification.readiness_score}, Sandbox: {classification.sandbox_recommendation}")
    print(f"Signals: {', '.join(classification.signals) or 'none'}")
    print(f"Required MCP servers: {', '.join(classification.required_mcp_servers) or 'none'}")
    print(f"Configured MCP servers: {', '.join(classification.configured_mcp_servers) or 'none'}")
    print(f"Missing MCP servers: {', '.join(classification.missing_mcp_servers) or 'none'}")
    print(f"Unsupported source MCP servers: {', '.join(classification.unsupported_mcp_servers) or 'none'}")
    if plan.target_path is not None:
        print(f"Target: {plan.target_path.relative_to(REPO_ROOT)}")
    if plan.output is not None:
        print(f"Output lines: {plan.output.count(chr(10)) + 1}")
        print("Post-write review state: pending_native_review")
    print(f"{'='*60}")
    if plan.output is not None:
        print(plan.output[:2000])
        if len(plan.output) > 2000:
            print(f"\n[... truncated, {len(plan.output)} chars total]")


def print_blocker_report(plans: list[PreparedMigration], output_format: str) -> None:
    """Print an MCP preflight blocker report for write-mode runs."""
    blocked_plans = [plan for plan in plans if plan.blocked]
    if not blocked_plans:
        return

    print(f"\n{'='*60}")
    print("MCP PREFLIGHT BLOCKED")
    print(f"Format: {output_format}")
    print("Add missing top-level `[mcp_servers.<id>]` entries to `.codex/config.toml` before rerunning.")
    print(f"{'='*60}")
    for plan in blocked_plans:
        classification = plan.classification
        print(f"- {plan.name}")
        print(f"  required: {', '.join(classification.required_mcp_servers) or 'none'}")
        print(f"  configured: {', '.join(classification.configured_mcp_servers) or 'none'}")
        print(f"  missing: {', '.join(classification.missing_mcp_servers)}")
        if classification.unsupported_mcp_servers:
            print(f"  dropped unsupported: {', '.join(classification.unsupported_mcp_servers)}")


def write_migration(plan: PreparedMigration, emit_text: bool = True) -> AgentClassification:
    """Write a prepared migration result to disk."""
    classification = plan.classification
    if classification.already_migrated and plan.output is None:
        if emit_text:
            print(f"SKIP: {plan.name} (already migrated, use --force to overwrite)")
        return classification
    if not plan.writable or plan.output is None or plan.target_path is None:
        return classification

    tier_label = {1: "MECHANICAL", 2: "ASSISTED", 3: "SKELETON"}
    status = tier_label.get(classification.tier, "UNKNOWN")
    dst = plan.target_path
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(plan.output, encoding="utf-8")
    if emit_text:
        print(
            f"WROTE: {dst.relative_to(REPO_ROOT)} "
            f"(Tier {classification.tier}: {status}, MCP: {format_mcp_status(classification)})"
        )
        print("  post-write state: pending_native_review; record manual nativeness review before treating as native")

    if plan.companion:
        ref_dst = CODEX_REFS_DIR / f"{plan.name}-domain.md"
        ref_dst.parent.mkdir(parents=True, exist_ok=True)
        ref_dst.write_text(plan.companion, encoding="utf-8")
        if emit_text:
            print(f"WROTE: {ref_dst.relative_to(REPO_ROOT)} (companion reference)")

    return classification


def _plan_status(plan: PreparedMigration) -> str:
    classification = plan.classification
    if classification.tier < 0:
        return "error"
    if classification.already_migrated and plan.output is None:
        return "already_migrated"
    if plan.blocked:
        return "blocked"
    return "ready"


def _serialize_classification(classification: AgentClassification) -> dict[str, object]:
    return {
        "tier": classification.tier,
        "readiness_score": classification.readiness_score,
        "signals": classification.signals,
        "sandbox_recommendation": classification.sandbox_recommendation,
        "already_migrated": classification.already_migrated,
        "skip_reason": classification.skip_reason,
        "required_mcp_servers": classification.required_mcp_servers,
        "configured_mcp_servers": classification.configured_mcp_servers,
        "missing_mcp_servers": classification.missing_mcp_servers,
        "unsupported_mcp_servers": classification.unsupported_mcp_servers,
        "valid_skill_refs": classification.valid_skill_refs,
        "missing_skill_refs": classification.missing_skill_refs,
    }


def _display_path(path: Path | None) -> str | None:
    if path is None:
        return None
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def _serialize_plan(plan: PreparedMigration, wrote: bool = False) -> dict[str, object]:
    classification = plan.classification
    return {
        "agent": plan.name,
        "status": _plan_status(plan),
        "wrote": wrote,
        "review_state": "pending_native_review" if wrote else None,
        "blocked": plan.blocked,
        "target_path": _display_path(plan.target_path),
        "companion_path": (
            _display_path(CODEX_REFS_DIR / f"{plan.name}-domain.md")
            if plan.companion
            else None
        ),
        "classification": _serialize_classification(classification),
    }


def _build_blockers(plans: list[PreparedMigration]) -> list[dict[str, str]]:
    blockers: list[dict[str, str]] = []
    for plan in plans:
        classification = plan.classification
        for server in classification.missing_mcp_servers:
            blockers.append(
                {
                    "severity": "high",
                    "type": "mcp_server",
                    "agent": plan.name,
                    "detail": f"Missing top-level `.codex/config.toml` MCP server: {server}",
                }
            )
        for skill_ref in classification.missing_skill_refs:
            blockers.append(
                {
                    "severity": "medium",
                    "type": "skill_reference",
                    "agent": plan.name,
                    "detail": f"Referenced Codex skill is missing: {skill_ref}",
                }
            )
    return blockers


def _build_next_actions(
    *,
    dry_run: bool,
    plans: list[PreparedMigration],
    wrote_count: int,
) -> list[str]:
    blockers = _build_blockers(plans)
    if any(blocker["type"] == "mcp_server" for blocker in blockers):
        return ["Add the missing MCP server entries to `.codex/config.toml`, then rerun the migration."]
    if any(blocker["type"] == "skill_reference" for blocker in blockers):
        return ["Review missing skill references before relying on the migrated agent operationally."]
    if dry_run:
        return ["Inspect the assessment output, then rerun without `--dry-run` or use the workflow preview path."]
    if wrote_count:
        return ["Record nativeness review for the written agents before treating them as native Codex agents."]
    return ["No immediate action required."]


def execute_migration(
    *,
    dry_run: bool,
    agent: str | None,
    all_agents: bool,
    force: bool,
    output_format: str,
) -> tuple[int, dict[str, object]]:
    if agent:
        agent_names = [agent]
    elif all_agents:
        agent_names = [src_file.stem for src_file in sorted(SOURCE_AGENTS_DIR.glob("*.md"))]
    else:
        result = {
            "mode": "agent_migration",
            "scope": {
                "target": None,
                "all_agents": False,
                "format": output_format,
                "dry_run": dry_run,
                "force": force,
            },
            "summary": {
                "agents_considered": 0,
                "ready": 0,
                "blocked": 0,
                "already_migrated": 0,
                "errors": 1,
                "written": 0,
            },
            "items": [],
            "blockers": [],
            "next_actions": ["Specify `--agent NAME` or `--all`."],
        }
        return 1, result

    available_mcp_servers = load_project_mcp_server_ids()
    plans = [
        prepare_migration(
            name,
            force=force,
            output_format=output_format,
            available_mcp_servers=available_mcp_servers,
        )
        for name in agent_names
    ]

    blocked_plans = [plan for plan in plans if plan.blocked]
    wrote_by_agent: dict[str, bool] = {}
    exit_code = 0

    if not dry_run and blocked_plans:
        exit_code = 1
    elif not dry_run:
        for plan in plans:
            write_migration(plan, emit_text=False)
            wrote_by_agent[plan.name] = bool(plan.writable)
        if not all(plan.classification.tier >= 0 for plan in plans):
            exit_code = 1

    items = [_serialize_plan(plan, wrote=wrote_by_agent.get(plan.name, False)) for plan in plans]
    summary = {
        "agents_considered": len(plans),
        "ready": sum(1 for item in items if item["status"] == "ready" and not item["blocked"]),
        "blocked": sum(1 for item in items if item["blocked"]),
        "already_migrated": sum(1 for item in items if item["status"] == "already_migrated"),
        "errors": sum(1 for item in items if item["status"] == "error"),
        "written": sum(1 for item in items if item["wrote"]),
        "review_required": sum(1 for item in items if item["wrote"]),
    }
    result = {
        "mode": "agent_migration",
        "scope": {
            "target": agent if agent else "all",
            "all_agents": all_agents,
            "format": output_format,
            "dry_run": dry_run,
            "force": force,
        },
        "summary": summary,
        "items": items,
        "blockers": _build_blockers(plans),
        "next_actions": _build_next_actions(
            dry_run=dry_run,
            plans=plans,
            wrote_count=summary["written"],
        ),
    }
    return exit_code, result


def print_summary(plans: list[PreparedMigration], output_format: str) -> None:
    """Print a migration summary with MCP dependency status."""
    print(f"\n{'='*60}")
    print("MIGRATION SUMMARY")
    print(f"Format: {output_format}")
    print(f"{'='*60}")
    tiers = {0: "SKIP", 1: "Tier 1", 2: "Tier 2", 3: "Tier 3", -1: "ERROR"}
    for plan in plans:
        classification = plan.classification
        tier_str = tiers.get(classification.tier, f"Tier {classification.tier}")
        status = classification.skip_reason or "OK"
        print(
            f"  {classification.agent:<25} {tier_str:<10} "
            f"Score: {classification.readiness_score:>3}  "
            f"MCP: {format_mcp_status(classification):<30}  {status}"
        )
    migrated = sum(1 for plan in plans if plan.classification.tier > 0)
    skipped = sum(1 for plan in plans if plan.classification.tier == 0 or plan.classification.tier == -1)
    blocked = sum(1 for plan in plans if plan.blocked)
    print(f"\nMigrated: {migrated}, Skipped: {skipped}, Blocked: {blocked}")
    if migrated:
        print("Review required: all mechanically generated agents enter pending_native_review")


def run(dry_run: bool, agent: str | None, all_agents: bool, force: bool, output_format: str) -> int:
    if agent:
        agent_names = [agent]
    elif all_agents:
        agent_names = [src_file.stem for src_file in sorted(SOURCE_AGENTS_DIR.glob("*.md"))]
    else:
        print("ERROR: Specify --agent NAME or --all")
        return 1

    available_mcp_servers = load_project_mcp_server_ids()
    plans = [
        prepare_migration(
            name,
            force=force,
            output_format=output_format,
            available_mcp_servers=available_mcp_servers,
        )
        for name in agent_names
    ]

    if dry_run:
        for plan in plans:
            print_dry_run(plan)
        if all_agents:
            print_summary(plans, output_format)
        return 0

    blocked_plans = [plan for plan in plans if plan.blocked]
    if blocked_plans:
        print_blocker_report(plans, output_format)
        if all_agents:
            print_summary(plans, output_format)
        return 1

    written_results = [write_migration(plan) for plan in plans]
    if all_agents:
        print_summary(plans, output_format)
    return 0 if all(result.tier >= 0 for result in written_results) else 1


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Migrate Claude agent definitions to Codex-compatible markdown or TOML."
    )
    parser.add_argument("--agent", type=str, help="Migrate a single agent by name.")
    parser.add_argument("--all", action="store_true", dest="all_agents",
                       help="Migrate all agents from .claude/agents/.")
    parser.add_argument("--format", choices=("md", "toml"), default="toml",
                       help="Output format. Defaults to 'toml' because Codex native agents are TOML files.")
    parser.add_argument("--dry-run", action="store_true",
                       help="Preview output without writing files.")
    parser.add_argument("--force", action="store_true",
                       help="Overwrite existing .codex/agents/ outputs.")
    parser.add_argument("--json", action="store_true", dest="json_output",
                       help="Emit structured JSON instead of human-readable text.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.json_output:
        exit_code, result = execute_migration(
            dry_run=args.dry_run,
            agent=args.agent,
            all_agents=args.all_agents,
            force=args.force,
            output_format=args.format,
        )
        print(json.dumps(result, indent=2))
        return exit_code
    return run(
        dry_run=args.dry_run,
        agent=args.agent,
        all_agents=args.all_agents,
        force=args.force,
        output_format=args.format,
    )


if __name__ == "__main__":
    raise SystemExit(main())
