#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Deterministic wrapper for Claude agent migration through nativeness-review handoff."""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
import tempfile
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path

MIN_SUPPORTED_PYTHON = (3, 11)


def _find_repo_root() -> Path:
    p = Path(__file__).resolve().parent
    while p != p.parent:
        if (p / ".git").exists() or (p / "package.json").exists():
            return p
        p = p.parent
    raise RuntimeError("Repository root not found")


REPO_ROOT = _find_repo_root()
_SUPPORT_SRC = REPO_ROOT / "tools"
if str(_SUPPORT_SRC) not in sys.path:
    sys.path.append(str(_SUPPORT_SRC))

from migration_support import nativeness  # noqa: E402

MIGRATOR_PATH = Path(__file__).with_name("migrate_claude_agents_to_codex.py")


def _tracker_script() -> Path:
    return REPO_ROOT / "tools" / "migration_support" / "tracker.py"


def _tracker_command() -> str:
    return f"python3 {_tracker_script().relative_to(REPO_ROOT)}"


def _python_version_label(version_info: tuple[int, ...] | object) -> str:
    major = getattr(version_info, "major", None)
    minor = getattr(version_info, "minor", None)
    micro = getattr(version_info, "micro", None)
    if major is not None and minor is not None:
        if micro is not None:
            return f"{major}.{minor}.{micro}"
        return f"{major}.{minor}"
    seq = tuple(version_info)  # type: ignore[arg-type]
    if len(seq) >= 3:
        return f"{seq[0]}.{seq[1]}.{seq[2]}"
    if len(seq) >= 2:
        return f"{seq[0]}.{seq[1]}"
    return ".".join(str(part) for part in seq)


def _require_supported_python(version_info: tuple[int, ...] | object | None = None) -> None:
    current = version_info or sys.version_info
    current_tuple = (
        current.major,
        current.minor,
    ) if hasattr(current, "major") else tuple(current[:2])  # type: ignore[index]
    if current_tuple < MIN_SUPPORTED_PYTHON:
        detected = _python_version_label(current)
        required = ".".join(str(part) for part in MIN_SUPPORTED_PYTHON)
        raise SystemExit(
            "The agent migration workflow requires Python "
            f"{required}+; detected {detected}."
        )


_require_supported_python()


def _load_module(module_name: str, path: Path):
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load module from {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


migrator = _load_module("agent_migration_workflow_migrator", MIGRATOR_PATH)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run deterministic agent migration through structural validation and "
            "nativeness-review handoff."
        )
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--agent", type=str, help="Run the workflow for one Claude agent.")
    group.add_argument(
        "--all",
        action="store_true",
        dest="all_agents",
        help="Run the workflow for every Claude agent.",
    )
    parser.add_argument(
        "--preview",
        action="store_true",
        help="Write output into a temp preview tree instead of the live `.codex/agents/` directory.",
    )
    parser.add_argument(
        "--preview-dir",
        type=Path,
        help="Explicit preview root. Defaults to a new /tmp directory when --preview is used.",
    )
    parser.add_argument(
        "--report-dir",
        type=Path,
        default=Path(tempfile.gettempdir()) / "codex-agent-migration-review-reports",
        help="Directory for live-run markdown review-reports (default: /tmp/codex-agent-migration-review-reports).",
    )
    parser.add_argument(
        "--format",
        choices=("md", "toml"),
        default="toml",
        help="Output format for migrated agents.",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite existing outputs.")
    parser.add_argument("--json", action="store_true", dest="json_output", help="Emit structured JSON.")
    return parser.parse_args()


def _resolve_preview_root(preview_dir: Path | None) -> Path:
    if preview_dir is not None:
        return preview_dir
    return Path(tempfile.mkdtemp(prefix="codex-agent-migration-preview-"))


@contextmanager
def _patched_output_roots(preview_root: Path):
    original_agents_dir = migrator.TARGET_AGENTS_DIR
    original_refs_dir = migrator.CODEX_REFS_DIR
    try:
        migrator.TARGET_AGENTS_DIR = preview_root / ".codex" / "agents"
        migrator.CODEX_REFS_DIR = migrator.TARGET_AGENTS_DIR / "references"
        migrator.TARGET_AGENTS_DIR.mkdir(parents=True, exist_ok=True)
        migrator.CODEX_REFS_DIR.mkdir(parents=True, exist_ok=True)
        yield
    finally:
        migrator.TARGET_AGENTS_DIR = original_agents_dir
        migrator.CODEX_REFS_DIR = original_refs_dir


def _compute_readiness(assessment: dict[str, object]) -> str:
    blockers = assessment["blockers"]
    if any(blocker["severity"] == "high" for blocker in blockers):
        return "blocked"
    if any(blocker["severity"] == "medium" for blocker in blockers):
        return "needs_review"
    return "ready"


def _build_validation_results(
    execution: dict[str, object] | None,
    output_format: str,
    preview_root: Path | None = None,
) -> list[dict[str, object]]:
    if execution is None:
        return []
    results: list[dict[str, object]] = []
    for item in execution["items"]:
        if not item["wrote"]:
            continue
        if output_format == "toml":
            import tomllib as toml_module

            target_path = Path(item["target_path"])
            if not target_path.exists():
                suffix = ".toml" if output_format == "toml" else ".md"
                if preview_root is not None:
                    preview_candidate = (
                        preview_root / ".codex" / "agents" / f"{item['agent']}{suffix}"
                    )
                    if preview_candidate.exists():
                        target_path = preview_candidate
                elif not target_path.is_absolute():
                    repo_candidate = REPO_ROOT / target_path
                    if repo_candidate.exists():
                        target_path = repo_candidate
            try:
                payload = toml_module.loads(target_path.read_text(encoding="utf-8"))
            except (OSError, toml_module.TOMLDecodeError) as exc:
                results.append(
                    {
                        "agent": item["agent"],
                        "passed": False,
                        "details": f"TOML post-write validation failed: {exc}",
                    }
                )
                continue

            required_keys = ("name", "description", "developer_instructions")
            missing_keys = [key for key in required_keys if not payload.get(key)]
            if missing_keys:
                results.append(
                    {
                        "agent": item["agent"],
                        "passed": False,
                        "details": (
                            "TOML post-write validation failed; missing required keys: "
                            + ", ".join(missing_keys)
                        ),
                    }
                )
                continue

            detail = (
                "Generated TOML parsed successfully and includes the required "
                "Codex agent contract keys."
            )
        else:
            detail = (
                "Markdown agent was written; workflow validation stops at migration-shape "
                "checks before nativeness review."
            )
        results.append(
            {
                "agent": item["agent"],
                "passed": True,
                "details": detail,
            }
        )
    return results


def _written_artifact_ids(execution: dict[str, object] | None) -> list[str]:
    if execution is None:
        return []
    return [
        f"agent:{item['agent']}"
        for item in execution["items"]
        if item["wrote"]
    ]


def _validated_written_artifact_ids(
    execution: dict[str, object] | None,
    validations: list[dict[str, object]],
) -> list[str]:
    if execution is None:
        return []
    passed_agents = {
        item["agent"]
        for item in validations
        if item.get("passed") is True
    }
    return [
        f"agent:{item['agent']}"
        for item in execution["items"]
        if item["wrote"] and item["agent"] in passed_agents
    ]


def _build_next_actions(
    *,
    assessment: dict[str, object],
    execution: dict[str, object] | None,
    preview: bool,
    nativeness_review: dict[str, object],
) -> list[str]:
    readiness = _compute_readiness(assessment)
    if readiness == "blocked":
        return ["Resolve the hard blockers first, then rerun the workflow."]
    if preview:
        return ["Inspect the preview tree and review-report, then rerun without `--preview` when the output looks correct."]
    if nativeness_review["state"] == "validation_failed":
        return [
            "Fix the post-write validation failures first, then rerun the "
            "workflow before refreshing the tracker or starting nativeness review."
        ]
    if nativeness_review["state"] == "tracker_refresh_required":
        return [
            "Refresh the tracker first so the live artifacts persist as "
            "`pending_native_review`, then run the nativeness-review audit."
        ]
    if nativeness_review["state"] == "pending_native_review":
        return [
            "Run the nativeness-review audit next. Clean `NO_FINDINGS` reviews should "
            "auto-record `native`; only MEDIUM-only outcomes, audit-only requests, or "
            "tracker-write failures should require manual close-out."
        ]
    return assessment["next_actions"]


def _write_report(
    *,
    assessment: dict[str, object],
    execution: dict[str, object] | None,
    validations: list[dict[str, object]],
    preview: bool,
    preview_root: Path | None,
    report_dir: Path,
    next_actions: list[str],
    nativeness_review: dict[str, object],
    tracker_updated: bool,
    tracker_output: str,
) -> Path:
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    if preview:
        assert preview_root is not None
        report_path = preview_root / "agent-migration-review-report.md"
        report_path.parent.mkdir(parents=True, exist_ok=True)
    else:
        report_dir.mkdir(parents=True, exist_ok=True)
        report_path = report_dir / f"agent-migration-review-report-{timestamp}.md"

    lines = [
        "# Codex Agent Migration Review report",
        "",
        f"- Generated: {datetime.now(timezone.utc).isoformat()}",
        f"- Mode: {'preview' if preview else 'live'}",
        f"- Readiness: {_compute_readiness(assessment)}",
        f"- Agents considered: {assessment['summary']['agents_considered']}",
        f"- Hard blockers: {sum(1 for blocker in assessment['blockers'] if blocker['severity'] == 'high')}",
        "",
        "## Assessment",
        "",
    ]

    for item in assessment["items"]:
        lines.append(
            f"- `{item['agent']}`: status={item['status']} "
            f"tier={item['classification']['tier']} "
            f"missing_mcp={len(item['classification']['missing_mcp_servers'])} "
            f"missing_skill_refs={len(item['classification']['missing_skill_refs'])}"
        )

    if assessment["blockers"]:
        lines.extend(["", "## Blockers", ""])
        for blocker in assessment["blockers"]:
            lines.append(
                f"- [{blocker['severity']}] `{blocker['agent']}` {blocker['type']}: {blocker['detail']}"
            )

    lines.extend(["", "## Execution", ""])
    if execution is None:
        lines.append("- No write step was executed.")
    else:
        for item in execution["items"]:
            if item["wrote"]:
                lines.append(f"- Wrote `{item['target_path']}`")
            elif item["status"] == "already_migrated":
                lines.append(f"- Skipped `{item['agent']}` because a Codex artifact already exists.")
            else:
                lines.append(f"- No write for `{item['agent']}` (status={item['status']}).")

    lines.extend(["", "## Validation", ""])
    if validations:
        for validation in validations:
            state = "PASS" if validation["passed"] else "FAIL"
            lines.append(f"- `{validation['agent']}`: {state} — {validation['details']}")
    else:
        lines.append("- No post-write validation ran because nothing was written.")

    lines.extend(["", "## Tracker", ""])
    lines.append(f"- Tracker updated: {'yes' if tracker_updated else 'no'}")
    if tracker_output:
        lines.append(f"- Tracker output: `{tracker_output.splitlines()[0]}`")

    lines.extend(["", "## Nativeness Review Handoff", ""])
    for instruction in nativeness_review["instructions"]:
        lines.append(f"- {instruction}")
    if (
        nativeness_review["state"] == "tracker_refresh_required"
        and nativeness_review.get("tracker_refresh_command")
    ):
        lines.append(f"- Tracker refresh command: `{nativeness_review['tracker_refresh_command']}`")
    for example in nativeness_review["record_review_examples"]:
        lines.append(f"- `{example['artifact_id']}` native:")
        lines.append(f"  - `{example['native']}`")
        lines.append(f"- `{example['artifact_id']}` codex_compatible_but_not_native:")
        lines.append(f"  - `{example['codex_compatible_but_not_native']}`")

    if preview and preview_root is not None:
        lines.extend(
            [
                "",
                "## Preview Output",
                "",
                f"- Preview root: `{preview_root}`",
                f"- Preview agents root: `{preview_root / '.codex' / 'agents'}`",
            ]
        )

    lines.extend(["", "## Next Action", ""])
    for action in next_actions:
        lines.append(f"- {action}")
    lines.append("")

    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path


def run_workflow(
    *,
    agent: str | None = None,
    preview: bool = False,
    preview_dir: Path | None = None,
    report_dir: Path | None = None,
    output_format: str = "toml",
    force: bool = False,
) -> tuple[int, dict[str, object]]:
    assessment_exit, assessment = migrator.execute_migration(
        dry_run=True,
        agent=agent,
        all_agents=agent is None,
        force=force,
        output_format=output_format,
    )
    preview_root = _resolve_preview_root(preview_dir) if preview else None
    readiness = _compute_readiness(assessment)
    execution: dict[str, object] | None = None
    exit_code = assessment_exit
    tracker_updated = False
    tracker_output = ""

    if assessment["summary"]["agents_considered"] and readiness != "blocked":
        if preview:
            assert preview_root is not None
            with _patched_output_roots(preview_root):
                exit_code, execution = migrator.execute_migration(
                    dry_run=False,
                    agent=agent,
                    all_agents=agent is None,
                    force=force,
                    output_format=output_format,
                )
        else:
            exit_code, execution = migrator.execute_migration(
                dry_run=False,
                agent=agent,
                all_agents=agent is None,
                force=force,
                output_format=output_format,
            )

    validations = _build_validation_results(execution, output_format, preview_root)
    written_artifact_ids = _written_artifact_ids(execution)
    validation_failed = any(not item["passed"] for item in validations)
    valid_written_artifact_ids = _validated_written_artifact_ids(execution, validations)
    if not preview and valid_written_artifact_ids and not validation_failed:
        tracker_updated, tracker_output = nativeness.run_tracker_write(
            REPO_ROOT, _tracker_script()
        )
    nativeness_review = nativeness.build_nativeness_review_handoff(
        valid_written_artifact_ids if not validation_failed else written_artifact_ids,
        preview=preview,
        validation_failed=validation_failed,
        tracker_updated=tracker_updated,
        tracker_command=_tracker_command(),
    )
    next_actions = _build_next_actions(
        assessment=assessment,
        execution=execution,
        preview=preview,
        nativeness_review=nativeness_review,
    )
    report_path = _write_report(
        assessment=assessment,
        execution=execution,
        validations=validations,
        preview=preview,
        preview_root=preview_root,
        report_dir=report_dir or (Path(tempfile.gettempdir()) / "codex-agent-migration-review-reports"),
        next_actions=next_actions,
        nativeness_review=nativeness_review,
        tracker_updated=tracker_updated,
        tracker_output=tracker_output,
    )

    if validation_failed or (written_artifact_ids and not preview and not tracker_updated):
        exit_code = 1

    result = {
        "mode": "agent_migration_workflow",
        "scope": {
            "target": agent if agent else "all",
            "all_agents": agent is None,
            "format": output_format,
            "preview": preview,
            "force": force,
        },
        "summary": {
            "readiness": readiness,
            "agents_considered": assessment["summary"]["agents_considered"],
            "blocked": assessment["summary"]["blocked"],
            "written": execution["summary"]["written"] if execution else 0,
            "review_required": execution["summary"]["written"] if execution else 0,
        },
        "items": execution["items"] if execution is not None else assessment["items"],
        "blockers": assessment["blockers"],
        "validation": validations,
        "nativeness_review": nativeness_review,
        "tracker": {
            "updated": tracker_updated,
            "output": tracker_output,
        },
        "preview_root": str(preview_root) if preview_root else None,
        "report_path": str(report_path),
        "next_actions": next_actions,
        "assessment": assessment,
    }
    return exit_code, result


def format_workflow_result(result: dict[str, object]) -> str:
    lines = ["Agent Migration Workflow", "========================", ""]
    lines.append(
        f"Readiness: {result['summary']['readiness']} "
        f"agents={result['summary']['agents_considered']} "
        f"written={result['summary']['written']}"
    )
    lines.append("")
    for item in result["items"]:
        lines.append(
            f"  - {item['agent']}: status={item['status']} "
            f"tier={item['classification']['tier']} wrote={item.get('wrote', False)}"
        )
    if result["preview_root"]:
        lines.extend(["", f"Preview root: {result['preview_root']}"])
    if result["tracker"]["updated"]:
        lines.append("Tracker: updated")
    lines.extend(["", f"Report: {result['report_path']}"])
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    exit_code, result = run_workflow(
        agent=args.agent,
        preview=args.preview,
        preview_dir=args.preview_dir,
        report_dir=args.report_dir,
        output_format=args.format,
        force=args.force,
    )
    if args.json_output:
        print(json.dumps(result, indent=2))
    else:
        print(format_workflow_result(result))
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
