# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

import contextlib
import importlib.util
import io
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path
from unittest.mock import patch


SCRIPT_PATH = Path(__file__).resolve().parents[1] / "scripts" / "migrate_claude_agents_to_codex.py"
SPEC = importlib.util.spec_from_file_location("migrate_claude_agents_to_codex", SCRIPT_PATH)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
sys.modules[SPEC.name] = MODULE
SPEC.loader.exec_module(MODULE)


def build_agent_file(tools: str, description: str = "Example agent.") -> str:
    return textwrap.dedent(
        f"""\
        ---
        description: {description}
        tools: {tools}
        ---
        ## Output Format

        - Return structured results.
        """
    )


@contextlib.contextmanager
def temporary_repo(config_text: str, agents: dict[str, str]):
    with tempfile.TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        claude_agents_dir = root / ".claude" / "agents"
        codex_agents_dir = root / ".codex" / "agents"
        codex_skills_dir = root / ".codex" / "skills"
        codex_refs_dir = codex_agents_dir / "references"
        codex_config_path = root / ".codex" / "config.toml"

        claude_agents_dir.mkdir(parents=True)
        codex_agents_dir.mkdir(parents=True)
        codex_skills_dir.mkdir(parents=True)
        codex_refs_dir.mkdir(parents=True)
        codex_config_path.write_text(textwrap.dedent(config_text).lstrip(), encoding="utf-8")

        for name, content in agents.items():
            (claude_agents_dir / f"{name}.md").write_text(content, encoding="utf-8")

        with contextlib.ExitStack() as stack:
            stack.enter_context(patch.object(MODULE, "REPO_ROOT", root))
            stack.enter_context(patch.object(MODULE, "SOURCE_AGENTS_DIR", claude_agents_dir))
            stack.enter_context(patch.object(MODULE, "TARGET_AGENTS_DIR", codex_agents_dir))
            stack.enter_context(patch.object(MODULE, "TARGET_SKILLS_DIR", codex_skills_dir))
            stack.enter_context(patch.object(MODULE, "CODEX_REFS_DIR", codex_refs_dir))
            stack.enter_context(patch.object(MODULE, "CODEX_CONFIG_PATH", codex_config_path))
            yield root


class MigrationScriptUnitTests(unittest.TestCase):
    def test_python_version_gate_rejects_python_310(self) -> None:
        with self.assertRaises(SystemExit) as exc:
            MODULE._require_supported_python((3, 10, 14))

        self.assertIn("Python 3.11+", str(exc.exception))
        self.assertIn("3.10.14", str(exc.exception))

    def test_agent_without_mcp_tools_has_no_blockers(self) -> None:
        required, configured, missing, unsupported = MODULE.resolve_mcp_dependencies(
            "Read, Write, Bash",
            ["example-server-f", "example-server-g"],
        )
        self.assertEqual(required, [])
        self.assertEqual(configured, [])
        self.assertEqual(missing, [])
        self.assertEqual(unsupported, [])

    def test_deduplicates_multiple_tools_on_same_server(self) -> None:
        required, configured, missing, unsupported = MODULE.resolve_mcp_dependencies(
            "Read, mcp__example_server_f__find_symbol, mcp__example_server_f__read_note, mcp__example_server_f__save_note",
            ["example-server-f"],
        )
        self.assertEqual(required, ["example-server-f"])
        self.assertEqual(configured, ["example-server-f"])
        self.assertEqual(missing, [])
        self.assertEqual(unsupported, [])

    def test_underscore_hyphen_normalization_matches_config_ids(self) -> None:
        required, configured, missing, unsupported = MODULE.resolve_mcp_dependencies(
            "Read, mcp__example_server_g__ask_model, mcp__chrome_devtools__click",
            ["example-server-g", "chrome-devtools"],
        )
        self.assertEqual(required, ["chrome-devtools", "example-server-g"])
        self.assertEqual(configured, ["chrome-devtools", "example-server-g"])
        self.assertEqual(missing, [])
        self.assertEqual(unsupported, [])

    def test_ide_is_treated_as_unsupported_not_missing(self) -> None:
        required, configured, missing, unsupported = MODULE.resolve_mcp_dependencies(
            "Read, mcp__ide__getDiagnostics, mcp__example_server_f__find_symbol",
            ["example-server-f"],
        )
        self.assertEqual(required, ["example-server-f"])
        self.assertEqual(configured, ["example-server-f"])
        self.assertEqual(missing, [])
        self.assertEqual(unsupported, ["ide"])

    def test_load_project_mcp_servers_ignores_nested_tool_entries(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            config_path = Path(tmpdir) / "config.toml"
            config_path.write_text(
                textwrap.dedent(
                    """\
                    [mcp_servers.example-server-g]
                    command = "node"

                    [mcp_servers.example-server-g.tools.ask_model]
                    approval_mode = "approve"

                    [mcp_servers.example-server-f]
                    url = "https://example.invalid/mcp"
                    """
                ),
                encoding="utf-8",
            )

            self.assertEqual(
                MODULE.load_project_mcp_server_ids(config_path),
                sorted(["example-server-g", "example-server-f"]),
            )


class MigrationScriptBehaviorTests(unittest.TestCase):
    def test_execute_migration_returns_structured_contract(self) -> None:
        config_text = """
        [mcp_servers.chrome-devtools]
        command = "npx"
        """
        agents = {
            "satisfied-agent": build_agent_file("Read, mcp__chrome_devtools__click"),
        }

        with temporary_repo(config_text, agents):
            exit_code, result = MODULE.execute_migration(
                dry_run=True,
                agent="satisfied-agent",
                all_agents=False,
                force=False,
                output_format="toml",
            )

        self.assertEqual(exit_code, 0)
        self.assertEqual(result["mode"], "agent_migration")
        self.assertEqual(result["summary"]["agents_considered"], 1)
        self.assertEqual(result["items"][0]["agent"], "satisfied-agent")
        self.assertEqual(
            result["items"][0]["classification"]["configured_mcp_servers"],
            ["chrome-devtools"],
        )
        self.assertTrue(result["next_actions"])

    def test_execute_migration_surfaces_missing_skill_refs_as_medium_blockers(self) -> None:
        config_text = """
        [mcp_servers.example-server-f]
        url = "https://example.invalid/mcp"
        """
        agents = {
            "skill-gap-agent": """---
description: Example agent.
tools: Read
skills:
  - missing-skill
---
## Output Format

- Return structured results.
""",
        }

        with temporary_repo(config_text, agents):
            exit_code, result = MODULE.execute_migration(
                dry_run=True,
                agent="skill-gap-agent",
                all_agents=False,
                force=False,
                output_format="toml",
            )

        self.assertEqual(exit_code, 0)
        self.assertEqual(
            result["items"][0]["classification"]["missing_skill_refs"],
            [".codex/skills/missing-skill/SKILL.md"],
        )
        self.assertIn(
            {
                "severity": "medium",
                "type": "skill_reference",
                "agent": "skill-gap-agent",
                "detail": "Referenced Codex skill is missing: .codex/skills/missing-skill/SKILL.md",
            },
            result["blockers"],
        )

    def test_single_agent_dry_run_reports_status_for_satisfied_and_blocked_agents(self) -> None:
        config_text = """
        [mcp_servers.chrome-devtools]
        command = "npx"
        """
        agents = {
            "satisfied-agent": build_agent_file("Read, mcp__chrome_devtools__click"),
            "blocked-agent": build_agent_file("Read, mcp__ide__getDiagnostics"),
        }

        with temporary_repo(config_text, agents):
            for agent_name, expected_missing, expected_unsupported in (
                ("satisfied-agent", "none", "none"),
                ("blocked-agent", "none", "ide"),
            ):
                with self.subTest(agent=agent_name):
                    stdout = io.StringIO()
                    with contextlib.redirect_stdout(stdout):
                        exit_code = MODULE.run(
                            dry_run=True,
                            agent=agent_name,
                            all_agents=False,
                            force=False,
                            output_format="toml",
                        )
                    output = stdout.getvalue()
                    self.assertEqual(exit_code, 0)
                    self.assertIn("Required MCP servers:", output)
                    self.assertIn("Configured MCP servers:", output)
                    self.assertIn(f"Missing MCP servers: {expected_missing}", output)
                    self.assertIn(f"Unsupported source MCP servers: {expected_unsupported}", output)
                    self.assertIn('name = "', output)

    def test_single_agent_non_dry_run_allows_unsupported_ide_and_writes_output(self) -> None:
        config_text = """
        [mcp_servers.chrome-devtools]
        command = "npx"
        """
        agents = {
            "blocked-agent": build_agent_file("Read, mcp__ide__getDiagnostics"),
        }

        with temporary_repo(config_text, agents) as root:
            stdout = io.StringIO()
            with contextlib.redirect_stdout(stdout):
                exit_code = MODULE.run(
                    dry_run=False,
                    agent="blocked-agent",
                    all_agents=False,
                    force=False,
                    output_format="toml",
                )
            self.assertEqual(exit_code, 0)
            output = stdout.getvalue()
            self.assertNotIn("MCP PREFLIGHT BLOCKED", output)
            self.assertIn("pending_native_review", output)
            written = root / ".codex" / "agents" / "blocked-agent.toml"
            self.assertTrue(written.exists())
            written_text = written.read_text(encoding="utf-8")
            self.assertIn("AUTO-GENERATED FILE", written_text)
            self.assertIn("Recorded manual nativeness review is required", written_text)
            self.assertNotIn("mcp__ide__", written_text)
            self.assertNotIn("Unsupported source MCP servers removed from migration", written_text)

    def test_single_agent_dry_run_reports_pending_native_review_state(self) -> None:
        config_text = """
        [mcp_servers.chrome-devtools]
        command = "npx"
        """
        agents = {
            "satisfied-agent": build_agent_file("Read, mcp__chrome_devtools__click"),
        }

        with temporary_repo(config_text, agents):
            stdout = io.StringIO()
            with contextlib.redirect_stdout(stdout):
                exit_code = MODULE.run(
                    dry_run=True,
                    agent="satisfied-agent",
                    all_agents=False,
                    force=False,
                    output_format="toml",
                )
            output = stdout.getvalue()
            self.assertEqual(exit_code, 0)
            self.assertIn("Post-write review state: pending_native_review", output)

    def test_all_dry_run_reports_all_blocked_agents_and_missing_servers(self) -> None:
        config_text = """
        [mcp_servers.chrome-devtools]
        command = "npx"
        """
        agents = {
            "blocked-ide": build_agent_file("Read, mcp__ide__getDiagnostics"),
            "blocked-memory": build_agent_file("Read, mcp__memory__search_nodes"),
            "satisfied-agent": build_agent_file("Read, mcp__chrome_devtools__click"),
        }

        with temporary_repo(config_text, agents):
            stdout = io.StringIO()
            with contextlib.redirect_stdout(stdout):
                exit_code = MODULE.run(
                    dry_run=True,
                    agent=None,
                    all_agents=True,
                    force=False,
                    output_format="toml",
                )
            output = stdout.getvalue()
            self.assertEqual(exit_code, 0)
            self.assertIn("[DRY RUN] blocked-ide", output)
            self.assertIn("Missing MCP servers: none", output)
            self.assertIn("Unsupported source MCP servers: ide", output)
            self.assertIn("[DRY RUN] blocked-memory", output)
            self.assertIn("Missing MCP servers: memory", output)
            self.assertIn("MIGRATION SUMMARY", output)

    def test_all_non_dry_run_with_any_blocker_writes_nothing_for_batch(self) -> None:
        config_text = """
        [mcp_servers.chrome-devtools]
        command = "npx"
        """
        agents = {
            "blocked-agent": build_agent_file("Read, mcp__ide__getDiagnostics"),
            "satisfied-agent": build_agent_file("Read, mcp__chrome_devtools__click"),
        }

        with temporary_repo(config_text, agents) as root:
            stdout = io.StringIO()
            with contextlib.redirect_stdout(stdout):
                exit_code = MODULE.run(
                    dry_run=False,
                    agent=None,
                    all_agents=True,
                    force=False,
                    output_format="toml",
                )
            self.assertEqual(exit_code, 0)
            output = stdout.getvalue()
            self.assertNotIn("MCP PREFLIGHT BLOCKED", output)
            self.assertTrue((root / ".codex" / "agents" / "blocked-agent.toml").exists())
            self.assertTrue((root / ".codex" / "agents" / "satisfied-agent.toml").exists())

    def test_all_non_dry_run_still_blocks_on_real_missing_servers(self) -> None:
        config_text = """
        [mcp_servers.chrome-devtools]
        command = "npx"
        """
        agents = {
            "blocked-memory": build_agent_file("Read, mcp__memory__search_nodes"),
            "unsupported-ide": build_agent_file("Read, mcp__ide__getDiagnostics"),
        }

        with temporary_repo(config_text, agents) as root:
            stdout = io.StringIO()
            with contextlib.redirect_stdout(stdout):
                exit_code = MODULE.run(
                    dry_run=False,
                    agent=None,
                    all_agents=True,
                    force=False,
                    output_format="toml",
                )
            self.assertEqual(exit_code, 1)
            self.assertIn("MCP PREFLIGHT BLOCKED", stdout.getvalue())
            self.assertFalse((root / ".codex" / "agents" / "blocked-memory.toml").exists())
            self.assertFalse((root / ".codex" / "agents" / "unsupported-ide.toml").exists())



if __name__ == "__main__":
    unittest.main()
