#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Validate migrated Codex skills and related docs for migration drift."""

from __future__ import annotations

import argparse
import json
import re
import shlex
import shutil
import sys
from pathlib import Path
from typing import Callable

import tomllib
import yaml


def _find_repo_root() -> Path:
    p = Path(__file__).resolve().parent
    while p != p.parent:
        if (p / ".git").exists() or (p / "package.json").exists():
            return p
        p = p.parent
    raise RuntimeError("Repository root not found")


REPO_ROOT = _find_repo_root()
_SUPPORT_SRC = REPO_ROOT / "tools"
if str(_SUPPORT_SRC) not in sys.path:
    sys.path.insert(0, str(_SUPPORT_SRC))

from migration_support.safety import describe_path_for_display as shared_describe_path_for_display  # noqa: E402

DEFAULT_SCAN_DIRS = (
    REPO_ROOT / ".codex" / "skills",
    REPO_ROOT / ".codex" / "agents",
)
ENVIRONMENT_READINESS_CODEX_HOME = REPO_ROOT / ".codex"
ENVIRONMENT_READINESS_STRICT = False
REQUIRED_FRONTMATTER_FIELDS = {"name", "description"}
PROHIBITED_FRONTMATTER_FIELDS = {"allowed-tools", "effort", "metadata"}
LINE_COUNT_WARNING_THRESHOLD = 500
PROVENANCE_LINE_PATTERNS = (
    re.compile(r"Source:"),
    re.compile(r"Generated by:"),
    re.compile(r"Migrated by:"),
    re.compile(r"AUTO-GENERATED"),
    re.compile(r"HAND-AUTHORED"),
)
HYPHENATED_MCP_PATTERN = re.compile(r"mcp__[a-z0-9_]*-[a-z0-9_\-]*__")
EXECUTABLE_CLAUDE_PATTERN = re.compile(
    r"\b("
    r"AskUserQuestion|TaskCreate|TaskUpdate|TaskList|TaskGet|TaskStop|TaskOutput|"
    r"TeamCreate|EnterPlanMode|ExitPlanMode|TodoWrite|NotebookEdit|"
    r"SendMessage|CronCreate|CronDelete|CronList"
    r")\b|(?<![-\w])(?:Agent|Task)\s*\("
)
MAPPING_TABLE_PATTERN = re.compile(
    r"(→|->|NO_CODEX_EQUIVALENT|RUNTIME_DEPENDENT|Codex Equivalent|Claude Primitive|fabricated|Previously|Does not exist)"
)
STALE_PATH_PATTERN = re.compile(r"\.claude/(skills|scripts)/")
LEGACY_PATH_COMPATIBILITY_CONTEXT_PATTERN = re.compile(
    r"\b(symlinks?|backward[- ]compat|compatibility|source tree|legacy source|shared reference)\b",
    re.IGNORECASE,
)
LEGACY_SKILL_CALL_PATTERN = re.compile(r"""\bSkill\s*\(\s*['"]""")
OPERATOR_PATH_TOKEN_PATTERN = re.compile(r"`([^`\n]+)`")
SLASH_SKILL_INVOCATION_PATTERN = re.compile(r"(?<![\w:])/(?:([a-z0-9][a-z0-9-]+))(?![\w/.-])")
SKILL_CALL_PATTERN = re.compile(r"""`?Skill\(['"]([a-z0-9][a-z0-9\-_]*)['"]\)`?""")
SKILL_REFERENCE_PATTERN = re.compile(r"`([^`\n]+)`")
SKILL_CONTEXT_PATTERN = re.compile(
    r"unknown skill references?|related skills?|integration with other skills|"
    r"Use Instead|Use OTHER skills instead|see also|deep dive|\bsee\b",
    re.IGNORECASE,
)
SKILL_TABLE_CONTEXT_PATTERN = re.compile(r"\bskills?\b", re.IGNORECASE)
SKILL_PATH_REFERENCE_PATTERN = re.compile(
    r"\.(?:claude|codex)/skills/([a-z0-9][a-z0-9\-_]*)/",
    re.IGNORECASE,
)
KNOWN_EXTERNAL_SKILLS = {
    "find-skills",
    "gh-address-comments",
    "gh-fix-ci",
    "github",
    "imagegen",
    "openai-docs",
    "pdf",
    "plugin-creator",
    "skill-creator",
    "skill-installer",
    "yeet",
}
AGENT_PATH_REFERENCE_PATTERN = re.compile(r"\.codex/agents/([a-z0-9_-]+)\.(md|toml)", re.IGNORECASE)
SUBAGENT_TYPE_PATTERN = re.compile(
    r"""subagent_type\s*[:=]\s*["']([a-z0-9][a-z0-9\-_]*)["']""",
    re.IGNORECASE,
)
GENERIC_AGENT_TYPES = {
    "",
    "default",
    "explorer",
    "general-purpose",
    "general_purpose",
    "implementation",
    "read-only",
    "sub-agent",
    "subagent",
    "worker",
    "write",
}
MODEL_INTENT_PATTERN = re.compile(r"\b(opus(?:\[1m\])?|sonnet|haiku(?:\[.*?\])?)\b", re.IGNORECASE)
SPAWN_AGENT_PATTERN = re.compile(r"\bspawn_agent\s*\(")
WAIT_AGENT_LEGACY_SHAPE_PATTERN = re.compile(r"\bwait_agent\s*\(\s*\[")
OPERATIONAL_HINT_PATTERN = re.compile(
    r"\b(run|use|call|launch|execute|workflow|template|command|approval|gate|must|should|step|phase)\b",
    re.IGNORECASE,
)
COMPARISON_CONTEXT_PATTERN = re.compile(
    r"\b(claude|migration|mapping|taxonomy|comparison|equivalent|replaces|not\b|bad:|good:|anti-pattern)\b",
    re.IGNORECASE,
)
MODEL_IDENTIFIER_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*-\d+(?:@[a-z0-9._-]+)?$", re.IGNORECASE)
REPO_OPERATOR_PATH_PREFIXES = (
    ".codex/",
    ".claude/",
    "example-admin/",
    "example-service/",
    "example-worker/",
    "docs/",
    "infra/",
    "packages/",
    "example-app/",
    "scripts/",
    "tests/",
)
SKILL_LOCAL_OPERATOR_PATH_PREFIXES = ("references/", "scripts/")
MIGRATION_FAMILY_SKILLS = {
    "migrate-agents-to-codex",
    "migrate-to-codex",
    "migration-dashboard",
    "verify-skill-migration",
}
PLACEHOLDER_OR_GLOB_PATTERN = re.compile(r"[*?{}\[\]<>]")
SHELL_BUILTIN_COMMANDS = {"echo", "printf", "test", "true", "false", "[", "[["}
SCRIPT_INTERPRETERS = {"node", "python", "python3", "bash", "sh", "zsh"}


def describe_path_for_display(path: Path, *, codex_home: Path | None = None) -> str:
    named_roots: tuple[tuple[str, Path], ...] = ()
    if codex_home is not None:
        named_roots = (("codex-home", codex_home),)
    return shared_describe_path_for_display(
        path,
        repo_root=REPO_ROOT,
        named_roots=named_roots,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate migrated Codex skills and agents for migration drift."
    )
    parser.add_argument(
        "--scan-dir",
        action="append",
        default=[],
        help="Relative directory to scan. When omitted, scans .codex/skills and .codex/agents.",
    )
    parser.add_argument(
        "--check",
        action="append",
        choices=[
            "structural-integrity",
            "frontmatter",
            "line-count",
            "references",
            "cross-references",
            "skill-remnants",
            "stale-paths",
            "operator-guidance",
            "agent-dependencies",
            "agent-flattening",
            "agent-api-shape",
            "executable-primitives",
            "environment-readiness",
        ],
        help="Run only specific checks. Can be repeated.",
    )
    parser.add_argument(
        "--codex-home",
        type=Path,
        default=ENVIRONMENT_READINESS_CODEX_HOME,
        help="Codex configuration root to inspect for environment-readiness checks.",
    )
    parser.add_argument(
        "--strict-environment-readiness",
        action="store_true",
        help="Promote environment-readiness host warnings to failures.",
    )
    parser.add_argument(
        "--list-checks",
        action="store_true",
        help="List available checks and exit.",
    )
    return parser.parse_args()


def determine_scan_dirs(scan_dir_args: list[str]) -> tuple[Path, ...]:
    if scan_dir_args:
        return tuple(REPO_ROOT / rel for rel in scan_dir_args)
    return DEFAULT_SCAN_DIRS


def collect_markdown_files(scan_dirs: tuple[Path, ...]) -> list[Path]:
    files: list[Path] = []
    for directory in scan_dirs:
        if not directory.exists():
            continue
        files.extend(path for path in directory.rglob("*.md") if path.is_file())
    return sorted(set(files))


def collect_skill_entrypoints(scan_dirs: tuple[Path, ...]) -> list[Path]:
    files: list[Path] = []
    for directory in scan_dirs:
        if not directory.exists():
            continue
        files.extend(path for path in directory.rglob("SKILL.md") if path.is_file())
    return sorted(set(files))


def extract_frontmatter_block(path: Path) -> tuple[str | None, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None, text
    end_marker = text.find("\n---\n", 4)
    if end_marker == -1:
        return None, text
    return text[4:end_marker], text


def parse_frontmatter(path: Path) -> tuple[dict[str, object] | None, list[str]]:
    problems: list[str] = []
    frontmatter_text, full_text = extract_frontmatter_block(path)
    if frontmatter_text is None:
        stripped = full_text.lstrip()
        if stripped.startswith("---"):
            problems.append(
                f"{path.as_posix()}: YAML frontmatter must start at line 1 and close with '---'"
            )
        else:
            problems.append(
                f"{path.as_posix()}: missing YAML frontmatter at top of SKILL.md"
            )
        return None, problems

    try:
        data = yaml.safe_load(frontmatter_text)
    except yaml.YAMLError as exc:
        problems.append(f"{path.as_posix()}: invalid YAML frontmatter: {exc}")
        return None, problems

    if not isinstance(data, dict):
        problems.append(
            f"{path.as_posix()}: YAML frontmatter must parse to a mapping/object"
        )
        return None, problems

    missing = REQUIRED_FRONTMATTER_FIELDS - set(data.keys())
    if missing:
        problems.append(
            f"{path.as_posix()}: missing required frontmatter fields: {', '.join(sorted(missing))}"
        )

    prohibited = PROHIBITED_FRONTMATTER_FIELDS & set(data.keys())
    if prohibited:
        problems.append(
            f"{path.as_posix()}: prohibited frontmatter fields present: {', '.join(sorted(prohibited))}"
        )

    return data, problems


def is_provenance_line(line: str) -> bool:
    return any(pattern.search(line) for pattern in PROVENANCE_LINE_PATTERNS)


def discover_valid_skill_names() -> set[str]:
    valid_names: set[str] = set(KNOWN_EXTERNAL_SKILLS)
    candidate_roots = (
        REPO_ROOT / ".codex" / "skills",
        REPO_ROOT / ".claude" / "skills",
        REPO_ROOT / ".agents" / "skills",
    )
    for root in candidate_roots:
        if not root.exists():
            continue
        for skill_dir in root.iterdir():
            if skill_dir.is_dir():
                valid_names.add(skill_dir.name)
    return valid_names


def discover_codex_skill_names() -> set[str]:
    valid_names: set[str] = set(KNOWN_EXTERNAL_SKILLS)
    root = REPO_ROOT / ".codex" / "skills"
    if not root.exists():
        return valid_names
    for skill_dir in root.iterdir():
        if skill_dir.is_dir():
            valid_names.add(skill_dir.name)
    return valid_names


def discover_claude_skill_names() -> set[str]:
    valid_names: set[str] = set()
    root = REPO_ROOT / ".claude" / "skills"
    if not root.exists():
        return valid_names
    for skill_dir in root.iterdir():
        if skill_dir.is_dir():
            valid_names.add(skill_dir.name)
    return valid_names


def discover_known_agent_names() -> set[str]:
    known_agents: set[str] = set()
    candidate_roots = (
        (REPO_ROOT / ".claude" / "agents", "*.md"),
        (REPO_ROOT / ".codex" / "agents", "*.toml"),
    )
    for root, pattern in candidate_roots:
        if not root.exists():
            continue
        known_agents.update(path.stem for path in root.glob(pattern))
    return known_agents


def codex_agent_contract_path(agent_name: str) -> Path:
    return REPO_ROOT / ".codex" / "agents" / f"{agent_name}.toml"


def is_migration_reference(path: Path) -> bool:
    normalized = path.as_posix()
    return "/migrate-to-codex/" in normalized or "/verify-skill-migration/" in normalized


def skill_root_for_path(path: Path) -> Path | None:
    try:
        relative = path.resolve().relative_to((REPO_ROOT / ".codex" / "skills").resolve())
    except ValueError:
        return None
    if not relative.parts:
        return None
    return REPO_ROOT / ".codex" / "skills" / relative.parts[0]


def is_migration_family_path(path: Path) -> bool:
    skill_root = skill_root_for_path(path)
    return skill_root is not None and skill_root.name in MIGRATION_FAMILY_SKILLS


def is_tier3_migrated_skill(path: Path, lines: list[str]) -> bool:
    if path.name != "SKILL.md":
        return False
    header = "\n".join(lines[:30])
    return "Tier 3 migration" in header or "Migrated by:" in header


def looks_like_skill_reference(token: str, valid_skill_names: set[str]) -> bool:
    normalized = token.lstrip("$")
    if normalized in valid_skill_names:
        return True
    if (
        not normalized
        or normalized.startswith("-")
        or any(char.isspace() for char in normalized)
        or PLACEHOLDER_OR_GLOB_PATTERN.search(normalized)
    ):
        return False
    if MODEL_IDENTIFIER_PATTERN.fullmatch(normalized):
        return False
    return (
        normalized in valid_skill_names
        or (
            (":" in normalized or "-" in normalized)
            and "/" not in normalized
            and "." not in normalized
            and "__" not in normalized
            and not normalized.endswith(":")
            and not any(char.isdigit() for char in normalized)
        )
    )


def table_row_looks_like_skill_reference_context(lines: list[str], line_number: int) -> bool:
    line_index = line_number - 1
    line = lines[line_index]
    if not line.lstrip().startswith("|"):
        return False

    table_start = line_index
    while table_start > 0 and lines[table_start - 1].lstrip().startswith("|"):
        table_start -= 1

    table_context = "\n".join(lines[max(0, table_start - 3) : line_index + 1])
    return bool(
        SKILL_CONTEXT_PATTERN.search(table_context)
        or SKILL_TABLE_CONTEXT_PATTERN.search(table_context)
    )


def extract_skill_reference_tokens(
    lines: list[str],
    line_number: int,
    known_skill_names: set[str],
) -> set[str]:
    line = lines[line_number - 1]
    context = "\n".join(lines[max(0, line_number - 3) : min(len(lines), line_number + 2)])
    tokens = {match.group(1).strip() for match in SKILL_CALL_PATTERN.finditer(line)}
    tokens.update(match.group(1).strip() for match in SKILL_PATH_REFERENCE_PATTERN.finditer(line))
    table_skill_context = table_row_looks_like_skill_reference_context(lines, line_number)

    if SKILL_CONTEXT_PATTERN.search(context) or table_skill_context or tokens:
        for token in SKILL_REFERENCE_PATTERN.findall(line):
            candidate = token.strip()
            if looks_like_skill_reference(candidate, known_skill_names):
                tokens.add(candidate.lstrip("$"))

    return tokens


def validate_structural_integrity(files: list[Path]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []

    for path in files:
        text = path.read_text(encoding="utf-8")
        for line_number, line in enumerate(text.splitlines(), start=1):
            if MAPPING_TABLE_PATTERN.search(line):
                continue
            if HYPHENATED_MCP_PATTERN.search(line):
                errors.append(
                    f"{path.as_posix()}:{line_number}: hyphenated MCP callable namespace: {line.strip()}"
                )

    return errors, warnings


def validate_frontmatter(skill_files: list[Path]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    for path in skill_files:
        _, problems = parse_frontmatter(path)
        errors.extend(problems)
    return errors, []


def validate_line_count(skill_files: list[Path]) -> tuple[list[str], list[str]]:
    warnings: list[str] = []
    for path in skill_files:
        with path.open("r", encoding="utf-8") as handle:
            line_count = sum(1 for _ in handle)
        if line_count >= LINE_COUNT_WARNING_THRESHOLD:
            warnings.append(
                f"{path.as_posix()}: {line_count} lines (>= {LINE_COUNT_WARNING_THRESHOLD})"
            )
    return [], warnings


def validate_reference_files(scan_dirs: tuple[Path, ...]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    seen_dirs: set[Path] = set()

    for directory in scan_dirs:
        if not directory.exists():
            continue
        for reference_dir in directory.rglob("references"):
            if not reference_dir.is_dir() or reference_dir in seen_dirs:
                continue
            seen_dirs.add(reference_dir)
            files = sorted(path for path in reference_dir.rglob("*") if path.is_file())
            if not files:
                errors.append(
                    f"{reference_dir.as_posix()}: references directory exists but contains no files"
                )
                continue
            for path in files:
                if path.stat().st_size == 0:
                    errors.append(f"{path.as_posix()}: empty reference file")

    return errors, []


def validate_cross_references(files: list[Path]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    codex_skill_names = discover_codex_skill_names()
    claude_skill_names = discover_claude_skill_names()
    known_skill_names = codex_skill_names | claude_skill_names
    reported_errors: set[tuple[str, int, str]] = set()
    reported_warnings: set[tuple[str, int, str]] = set()

    for path in files:
        lines = path.read_text(encoding="utf-8").splitlines()
        for line_number, _line in enumerate(lines, start=1):
            for token in extract_skill_reference_tokens(lines, line_number, known_skill_names):
                if token in codex_skill_names:
                    continue
                if token in claude_skill_names:
                    key = (path.as_posix(), line_number, token)
                    if key in reported_errors:
                        continue
                    reported_errors.add(key)
                    errors.append(
                        f"{path.as_posix()}:{line_number}: Claude-only skill dependency: {token}"
                    )
                    continue
                if not looks_like_skill_reference(token, known_skill_names):
                    continue
                key = (path.as_posix(), line_number, token)
                if key in reported_warnings:
                    continue
                reported_warnings.add(key)
                warnings.append(
                    f"{path.as_posix()}:{line_number}: unknown skill reference: {token}"
                )

    return errors, warnings


def validate_skill_remnants(files: list[Path]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    for path in files:
        text = path.read_text(encoding="utf-8")
        for line_number, line in enumerate(text.splitlines(), start=1):
            if LEGACY_SKILL_CALL_PATTERN.search(line):
                errors.append(
                    f"{path.as_posix()}:{line_number}: legacy skill primitive call found: {line.strip()}"
                )
    return errors, []


def validate_stale_paths(files: list[Path]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    for path in files:
        text = path.read_text(encoding="utf-8")
        for line_number, line in enumerate(text.splitlines(), start=1):
            if not STALE_PATH_PATTERN.search(line):
                continue
            if is_provenance_line(line):
                continue
            message = (
                f"{path.as_posix()}:{line_number}: stale legacy path reference: {line.strip()}"
            )
            if LEGACY_PATH_COMPATIBILITY_CONTEXT_PATTERN.search(line):
                warnings.append(message)
            else:
                errors.append(message)
    return errors, warnings


def _is_operator_path_candidate(token: str, line: str) -> bool:
    if "://" in token or "..." in token or PLACEHOLDER_OR_GLOB_PATTERN.search(token):
        return False
    if token in SKILL_LOCAL_OPERATOR_PATH_PREFIXES:
        return False
    if "{" in line and "}" in line:
        return False
    if re.fullmatch(r"/[a-z0-9][a-z0-9-]+", token):
        return False
    if token.startswith(("/tmp", "/var", "/health", "/api/")):
        return False
    return (
        token.startswith("/")
        or token.startswith(("./", "../"))
        or token.startswith(REPO_OPERATOR_PATH_PREFIXES)
        or token.startswith(SKILL_LOCAL_OPERATOR_PATH_PREFIXES)
    )


def _repo_relative_operator_hint(token: str) -> str | None:
    stripped = token.lstrip("/")
    if stripped.startswith(REPO_OPERATOR_PATH_PREFIXES) or stripped.startswith(
        SKILL_LOCAL_OPERATOR_PATH_PREFIXES
    ):
        return stripped
    return None


def _operator_path_exists(path: Path, token: str) -> bool:
    skill_root = skill_root_for_path(path)
    if token.startswith(SKILL_LOCAL_OPERATOR_PATH_PREFIXES) and skill_root is not None:
        if (skill_root / token).exists():
            return True
    if token.startswith(("./", "../")):
        return (path.parent / token).resolve().exists()
    return (REPO_ROOT / token).exists()


def validate_operator_guidance(files: list[Path]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    codex_skill_names = discover_codex_skill_names()

    for path in files:
        if not is_migration_family_path(path):
            continue
        lines = path.read_text(encoding="utf-8").splitlines()
        for line_number, line in enumerate(lines, start=1):
            for match in OPERATOR_PATH_TOKEN_PATTERN.finditer(line):
                token = match.group(1).strip()
                if not _is_operator_path_candidate(token, line):
                    continue

                if token.startswith("/"):
                    hint = _repo_relative_operator_hint(token)
                    if hint is not None:
                        errors.append(
                            f"{path.as_posix()}:{line_number}: operator path uses filesystem root; "
                            f"use `{hint}` instead"
                        )
                    else:
                        errors.append(
                            f"{path.as_posix()}:{line_number}: operator path must be repo-relative "
                            f"or skill-local, not filesystem-absolute: `{token}`"
                        )
                    continue

                if _operator_path_exists(path, token):
                    continue

                errors.append(
                    f"{path.as_posix()}:{line_number}: operator path does not resolve: `{token}`"
                )

            for match in SLASH_SKILL_INVOCATION_PATTERN.finditer(line):
                skill_name = match.group(1)
                if skill_name not in codex_skill_names:
                    continue
                errors.append(
                    f"{path.as_posix()}:{line_number}: legacy slash skill invocation `/{skill_name}`; "
                    f"use `${skill_name}` or `{skill_name}`"
                )

    return errors, []


def validate_agent_dependencies(files: list[Path]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    known_agent_names = discover_known_agent_names()
    reported: set[tuple[str, int, str]] = set()

    for path in files:
        if is_migration_reference(path):
            continue
        for line_number, line in enumerate(
            path.read_text(encoding="utf-8").splitlines(), start=1
        ):
            for match in AGENT_PATH_REFERENCE_PATTERN.finditer(line):
                agent_name, ext = match.groups()
                agent_name = agent_name.lower()
                contract_path = codex_agent_contract_path(agent_name)
                if contract_path.exists():
                    continue
                key = (path.as_posix(), line_number, agent_name)
                if key in reported:
                    continue
                reported.add(key)
                reference_note = (
                    "markdown agent reference is legacy-only"
                    if ext == "md"
                    else "referenced TOML contract is missing"
                )
                errors.append(
                    f"{path.as_posix()}:{line_number}: unresolved named agent dependency `{agent_name}`; "
                    f"expected {contract_path.relative_to(REPO_ROOT).as_posix()} ({reference_note})"
                )

            for match in SUBAGENT_TYPE_PATTERN.finditer(line):
                agent_name = match.group(1).strip().lower()
                if agent_name in GENERIC_AGENT_TYPES or agent_name not in known_agent_names:
                    continue
                contract_path = codex_agent_contract_path(agent_name)
                if contract_path.exists():
                    continue
                key = (path.as_posix(), line_number, agent_name)
                if key in reported:
                    continue
                reported.add(key)
                errors.append(
                    f"{path.as_posix()}:{line_number}: unresolved named agent dependency `{agent_name}` from subagent_type; "
                    f"expected {contract_path.relative_to(REPO_ROOT).as_posix()}"
                )

            if "agent" not in line.lower() and "contract" not in line.lower():
                continue
            for agent_name in sorted(known_agent_names):
                if agent_name not in line:
                    continue
                contract_path = codex_agent_contract_path(agent_name)
                if contract_path.exists():
                    continue
                key = (path.as_posix(), line_number, agent_name)
                if key in reported:
                    continue
                reported.add(key)
                errors.append(
                    f"{path.as_posix()}:{line_number}: unresolved named agent dependency `{agent_name}` in role/contract guidance; "
                    f"expected {contract_path.relative_to(REPO_ROOT).as_posix()}"
                )
    return errors, []


def validate_agent_flattening(files: list[Path]) -> tuple[list[str], list[str]]:
    warnings: list[str] = []
    for path in files:
        if is_migration_reference(path):
            continue
        lines = path.read_text(encoding="utf-8").splitlines()
        for line_number, line in enumerate(lines, start=1):
            if not SPAWN_AGENT_PATTERN.search(line):
                continue

            block_lines = lines[line_number - 1 : min(len(lines), line_number + 7)]
            block_text = "\n".join(block_lines)
            has_override = "model=" in block_text or "model:" in block_text
            has_effort = "reasoning_effort" in block_text
            if has_override and has_effort:
                continue

            start = max(0, line_number - 12)
            end = min(len(lines), line_number + 12)
            context = "\n".join(lines[start:end])
            model_intent = MODEL_INTENT_PATTERN.search(context)
            if not model_intent:
                continue

            warnings.append(
                f"{path.as_posix()}:{line_number}: spawn_agent may flatten `{model_intent.group(1)}` runtime intent "
                "without model/reasoning_effort override"
            )
    return [], warnings


def validate_agent_api_shape(files: list[Path]) -> tuple[list[str], list[str]]:
    warnings: list[str] = []
    for path in files:
        lines = path.read_text(encoding="utf-8").splitlines()
        if not (is_migration_reference(path) or is_tier3_migrated_skill(path, lines)):
            continue
        for line_number, line in enumerate(lines, start=1):
            if not WAIT_AGENT_LEGACY_SHAPE_PATTERN.search(line):
                continue
            warnings.append(
                f"{path.as_posix()}:{line_number}: non-canonical wait_agent call shape; "
                'prefer wait_agent({"targets": [agent["id"]]})'
            )
    return [], warnings


def _is_operational_primitive_context(path: Path, lines: list[str], line_number: int, line: str) -> bool:
    if MAPPING_TABLE_PATTERN.search(line):
        return False
    if line.lstrip().startswith(("BAD:", "GOOD:")):
        return False
    if COMPARISON_CONTEXT_PATTERN.search(line):
        return False
    path_str = path.as_posix()
    if is_migration_reference(path):
        return False

    window_start = max(0, line_number - 3)
    window_end = min(len(lines), line_number + 2)
    context = "\n".join(lines[window_start:window_end])
    if COMPARISON_CONTEXT_PATTERN.search(context):
        return False

    if path.name == "SKILL.md":
        return True
    if "references/" in path_str and OPERATIONAL_HINT_PATTERN.search(context):
        return True
    return False


def validate_executable_primitives(files: list[Path]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    for path in files:
        lines = path.read_text(encoding="utf-8").splitlines()
        for line_number, line in enumerate(lines, start=1):
            if not EXECUTABLE_CLAUDE_PATTERN.search(line):
                continue
            if not _is_operational_primitive_context(path, lines, line_number, line):
                continue
            errors.append(
                f"{path.as_posix()}:{line_number}: Claude primitive in operational Codex guidance: {line.strip()}"
            )
    return errors, []


def _read_toml(path: Path) -> tuple[dict[str, object] | None, str | None]:
    try:
        return tomllib.loads(path.read_text(encoding="utf-8")), None
    except (OSError, tomllib.TOMLDecodeError) as exc:
        return None, str(exc)


def _read_json(path: Path) -> tuple[object | None, str | None]:
    try:
        return json.loads(path.read_text(encoding="utf-8")), None
    except (OSError, json.JSONDecodeError) as exc:
        return None, str(exc)


def _environment_check(
    checks: list[dict[str, object]],
    *,
    name: str,
    status: str,
    detail: str,
    strict_promotes_warning: bool = False,
) -> None:
    effective_status = (
        "fail"
        if status == "warn" and strict_promotes_warning and ENVIRONMENT_READINESS_STRICT
        else status
    )
    checks.append({"name": name, "status": effective_status, "detail": detail})


def _environment_state(checks: list[dict[str, object]]) -> str:
    if not checks:
        return "not_applicable"
    if any(check["status"] == "fail" for check in checks):
        return "failed"
    if any(check["status"] == "warn" for check in checks):
        return "warnings"
    return "ok"


def _iter_hook_commands(payload: object) -> list[str]:
    commands: list[str] = []

    def walk(value: object) -> None:
        if isinstance(value, dict):
            command = value.get("command")
            if isinstance(command, str):
                commands.append(command)
            for nested in value.values():
                walk(nested)
        elif isinstance(value, list):
            for item in value:
                walk(item)

    walk(payload)
    return commands


def _resolve_relative_command_path(token: str, codex_home: Path) -> Path:
    candidate = Path(token)
    if candidate.is_absolute():
        return candidate
    repo_relative = REPO_ROOT / candidate
    if repo_relative.exists():
        return repo_relative
    return codex_home / candidate


def _display_command_token(token: str, codex_home: Path) -> str:
    if token.startswith(("/", "./", "../")):
        return describe_path_for_display(
            _resolve_relative_command_path(token, codex_home),
            codex_home=codex_home,
        )
    return token


def _display_command(command: str, codex_home: Path) -> str:
    try:
        parts = shlex.split(command)
    except ValueError:
        return command
    display_parts = [
        _display_command_token(part, codex_home)
        if part.startswith(("/", "./", "../"))
        else part
        for part in parts
    ]
    return " ".join(display_parts)


def _check_hook_command(command: str, codex_home: Path) -> tuple[str, str, str] | None:
    try:
        parts = shlex.split(command)
    except ValueError as exc:
        return ("hook-command", "warn", f"hook command could not be parsed: {exc}")
    if not parts or parts[0] in SHELL_BUILTIN_COMMANDS:
        return None

    executable = parts[0]
    if executable.startswith(("/", "./", "../")):
        executable_path = _resolve_relative_command_path(executable, codex_home)
        display_executable = _display_command_token(executable, codex_home)
        if not executable_path.exists():
            return (
                "hook-command",
                "warn",
                f"hook executable path is missing: {display_executable}",
            )
        if not executable_path.is_file():
            return (
                "hook-command",
                "warn",
                f"hook executable path is not a file: {display_executable}",
            )
    elif shutil.which(executable) is None:
        return ("hook-command", "warn", f"hook executable is not on PATH: {executable}")

    if executable in SCRIPT_INTERPRETERS and len(parts) > 1:
        script_token = parts[1]
        if script_token.startswith("-") or "://" in script_token:
            return None
        script_path = _resolve_relative_command_path(script_token, codex_home)
        display_script = _display_command_token(script_token, codex_home)
        if not script_path.exists():
            return (
                "hook-command",
                "warn",
                f"hook script path is missing: {display_script}",
            )
    return None


def build_environment_readiness_report(codex_home: Path | None = None) -> dict[str, object]:
    codex_home = (codex_home or ENVIRONMENT_READINESS_CODEX_HOME).resolve()
    checks: list[dict[str, object]] = []

    config_path = codex_home / "config.toml"
    if config_path.exists():
        display_config_path = describe_path_for_display(config_path, codex_home=codex_home)
        config, error = _read_toml(config_path)
        if error:
            _environment_check(
                checks,
                name="codex-config",
                status="fail",
                detail=f"{display_config_path}: invalid TOML: {error}",
            )
        else:
            _environment_check(
                checks,
                name="codex-config",
                status="pass",
                detail=f"{display_config_path}: TOML parsed",
            )
            mcp_servers = config.get("mcp_servers", {}) if isinstance(config, dict) else {}
            if isinstance(mcp_servers, dict):
                for server_name, server_config in sorted(mcp_servers.items()):
                    if not isinstance(server_config, dict):
                        continue
                    command = server_config.get("command")
                    if not isinstance(command, str) or not command:
                        continue
                    display_command = _display_command_token(command, codex_home)
                    if command.startswith(("/", "./", "../")):
                        command_path = _resolve_relative_command_path(command, codex_home)
                        missing = not command_path.exists()
                    else:
                        missing = shutil.which(command) is None
                    _environment_check(
                        checks,
                        name="mcp-command",
                        status="warn" if missing else "pass",
                        detail=(
                            f"{server_name}: command not found: {display_command}"
                            if missing
                            else f"{server_name}: command available: {display_command}"
                        ),
                        strict_promotes_warning=True,
                    )
    else:
        _environment_check(
            checks,
            name="codex-config",
            status="warn",
            detail=(
                f"{describe_path_for_display(config_path, codex_home=codex_home)}: "
                "config not found"
            ),
            strict_promotes_warning=True,
        )

    hooks_path = codex_home / "hooks.json"
    if hooks_path.exists():
        display_hooks_path = describe_path_for_display(hooks_path, codex_home=codex_home)
        hooks_payload, error = _read_json(hooks_path)
        if error:
            _environment_check(
                checks,
                name="hooks-config",
                status="fail",
                detail=f"{display_hooks_path}: invalid JSON: {error}",
            )
        else:
            _environment_check(
                checks,
                name="hooks-config",
                status="pass",
                detail=f"{display_hooks_path}: JSON parsed",
            )
            for command in _iter_hook_commands(hooks_payload):
                hook_issue = _check_hook_command(command, codex_home)
                if hook_issue is None:
                    _environment_check(
                        checks,
                        name="hook-command",
                        status="pass",
                        detail=f"hook command looks runnable: {_display_command(command, codex_home)}",
                    )
                else:
                    name, status, detail = hook_issue
                    _environment_check(
                        checks,
                        name=name,
                        status=status,
                        detail=detail,
                        strict_promotes_warning=True,
                    )

    for instruction_path in sorted(
        {REPO_ROOT / "AGENTS.md", codex_home / "AGENTS.md"}
    ):
        if not instruction_path.exists():
            continue
        display_instruction_path = describe_path_for_display(
            instruction_path,
            codex_home=codex_home,
        )
        try:
            size_bytes = instruction_path.stat().st_size
            text = instruction_path.read_text(encoding="utf-8")
        except OSError as exc:
            _environment_check(
                checks,
                name="instructions",
                status="warn",
                detail=f"{display_instruction_path}: could not inspect instructions: {exc}",
                strict_promotes_warning=True,
            )
            continue
        _environment_check(
            checks,
            name="instructions-size",
            status="warn" if size_bytes > 32768 else "pass",
            detail=f"{display_instruction_path}: {size_bytes} bytes",
            strict_promotes_warning=True,
        )
        if "CLAUDE.md" in text or ".claude/" in text:
            _environment_check(
                checks,
                name="instructions-legacy-reference",
                status="warn",
                detail=f"{display_instruction_path}: contains legacy Claude-oriented references",
                strict_promotes_warning=True,
            )

    for plugins_root in (codex_home / "plugins", REPO_ROOT / ".agents" / "plugins"):
        if not plugins_root.exists():
            continue
        manifest_paths = list(plugins_root.glob("*/.codex-plugin/plugin.json"))
        marketplace_path = plugins_root / "marketplace.json"
        if marketplace_path.exists():
            manifest_paths.append(marketplace_path)
        for manifest_path in sorted(manifest_paths):
            display_manifest_path = describe_path_for_display(
                manifest_path,
                codex_home=codex_home,
            )
            _, error = _read_json(manifest_path)
            _environment_check(
                checks,
                name="plugin-manifest",
                status="fail" if error else "pass",
                detail=(
                    f"{display_manifest_path}: invalid JSON: {error}"
                    if error
                    else f"{display_manifest_path}: JSON parsed"
                ),
            )

    return {
        "codex_home": describe_path_for_display(codex_home, codex_home=codex_home),
        "state": _environment_state(checks),
        "checks": checks,
        "failures": sum(1 for check in checks if check["status"] == "fail"),
        "warnings": sum(1 for check in checks if check["status"] == "warn"),
    }


def validate_environment_readiness() -> tuple[list[str], list[str]]:
    report = build_environment_readiness_report(ENVIRONMENT_READINESS_CODEX_HOME)
    errors = [
        f"{check['name']}: {check['detail']}"
        for check in report["checks"]
        if check["status"] == "fail"
    ]
    warnings = [
        f"{check['name']}: {check['detail']}"
        for check in report["checks"]
        if check["status"] == "warn"
    ]
    return errors, warnings


CHECKS: dict[
    str, Callable[[tuple[Path, ...], list[Path], list[Path]], tuple[list[str], list[str]]]
] = {
    "structural-integrity": lambda scan_dirs, markdown_files, skill_files: validate_structural_integrity(
        markdown_files
    ),
    "frontmatter": lambda scan_dirs, markdown_files, skill_files: validate_frontmatter(
        skill_files
    ),
    "line-count": lambda scan_dirs, markdown_files, skill_files: validate_line_count(
        skill_files
    ),
    "references": lambda scan_dirs, markdown_files, skill_files: validate_reference_files(
        scan_dirs
    ),
    "cross-references": lambda scan_dirs, markdown_files, skill_files: validate_cross_references(
        markdown_files
    ),
    "skill-remnants": lambda scan_dirs, markdown_files, skill_files: validate_skill_remnants(
        markdown_files
    ),
    "stale-paths": lambda scan_dirs, markdown_files, skill_files: validate_stale_paths(
        markdown_files
    ),
    "operator-guidance": lambda scan_dirs, markdown_files, skill_files: validate_operator_guidance(
        markdown_files
    ),
    "agent-dependencies": lambda scan_dirs, markdown_files, skill_files: validate_agent_dependencies(
        markdown_files
    ),
    "agent-flattening": lambda scan_dirs, markdown_files, skill_files: validate_agent_flattening(
        markdown_files
    ),
    "agent-api-shape": lambda scan_dirs, markdown_files, skill_files: validate_agent_api_shape(
        markdown_files
    ),
    "executable-primitives": lambda scan_dirs, markdown_files, skill_files: validate_executable_primitives(
        markdown_files
    ),
    "environment-readiness": lambda scan_dirs, markdown_files, skill_files: validate_environment_readiness(),
}
DEFAULT_CHECK_NAMES = tuple(
    check_name for check_name in CHECKS if check_name != "environment-readiness"
)


def main() -> int:
    args = parse_args()
    global ENVIRONMENT_READINESS_CODEX_HOME
    global ENVIRONMENT_READINESS_STRICT
    ENVIRONMENT_READINESS_CODEX_HOME = args.codex_home
    ENVIRONMENT_READINESS_STRICT = args.strict_environment_readiness

    if args.list_checks:
        for check_name in CHECKS:
            print(check_name)
        return 0

    scan_dirs = determine_scan_dirs(args.scan_dir)
    markdown_files = collect_markdown_files(scan_dirs)
    skill_files = collect_skill_entrypoints(scan_dirs)
    selected_checks = args.check or list(DEFAULT_CHECK_NAMES)

    all_errors: list[str] = []
    all_warnings: list[str] = []

    for check_name in selected_checks:
        errors, warnings = CHECKS[check_name](scan_dirs, markdown_files, skill_files)
        all_errors.extend(errors)
        all_warnings.extend(warnings)

    if all_warnings:
        print(f"Warnings ({len(all_warnings)}):")
        for warning in all_warnings:
            print(f"  ⚠ {warning}")

    if all_errors:
        print(f"\nErrors ({len(all_errors)}):")
        for error in all_errors:
            print(f"  ✗ {error}")
        print("\nValidation FAILED.")
        return 1

    if all_warnings:
        print("\nValidation PASSED with warnings.")
    else:
        print("Validation OK: no migration drift detected.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
