#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Deterministic migration of source skills into Codex artifacts.

This is the skill-owned implementation behind the stable root wrapper:
`scripts/migrate_claude_workflows_to_codex.py`.

Behavioral contract:
  - `--skill <name>` migrates a single source skill
  - `--all` migrates every non-archived source skill
  - zero-argument invocation behaves as `--all`
  - `--dry-run` computes work without writing files
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

import yaml


def _find_repo_root() -> Path:
    p = Path(__file__).resolve().parent
    while p != p.parent:
        if (p / ".git").exists() or (p / "package.json").exists():
            return p
        p = p.parent
    raise RuntimeError("Repository root not found")


REPO_ROOT = _find_repo_root()

# Import shared migration support primitives.
_SUPPORT_SRC = REPO_ROOT / "tools"
if str(_SUPPORT_SRC) not in sys.path:
    sys.path.append(str(_SUPPORT_SRC))

from migration_support.safety import (  # noqa: E402
    resolve_within_root,
    safe_provenance_value,
    validate_identifier,
)
from migration_support.paths import (  # noqa: E402
    default_user_claude_home,
    default_user_codex_home,
    discover_claude_plugin_skill_names,
    discover_plugin_skill_names,
    find_claude_plugin_skill_dir,
)
from migration_support.codex_runtime import (  # noqa: E402
    RuntimeFileCopy,
    RuntimeFileWrite,
    RuntimeInstallPlan,
    install_runtime_assets,
)
from migration_support.skill_dependencies import BatchPlan, build_skill_batch_plan  # noqa: E402
SOURCE_SKILLS_DIR = REPO_ROOT / ".claude" / "skills"
TARGET_SKILLS_DIR = REPO_ROOT / ".codex" / "skills"
SOURCE_AGENTS_DIR = REPO_ROOT / ".claude" / "agents"
TARGET_AGENTS_DIR = REPO_ROOT / ".codex" / "agents"
USER_CODEX_HOME = default_user_codex_home()
USER_CLAUDE_HOME = default_user_claude_home()
GENERIC_AGENT_TYPES = {"", "general-purpose", "general_purpose", "sub-agent", "subagent"}
PROHIBITED_FRONTMATTER_FIELDS = {"allowed-tools", "effort", "metadata"}
SKILL_TOKEN_PATTERN = r"[a-z0-9][a-z0-9\-_]*(?::[a-z0-9][a-z0-9\-_]*)?"

PRIMITIVE_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    (
        "AskUserQuestion",
        "# RUNTIME_DEPENDENT: request_user_input (Plan mode only) or approval workflow",
    ),
    ("TaskCreate", "spawn_agent"),
    ("TaskUpdate", "update_plan"),
    ("TaskList", "# NO_CODEX_EQUIVALENT: track locally or via update_plan"),
    ("TaskGet", "wait_agent"),
    ("TaskOutput", "wait_agent"),
    ("TaskStop", "close_agent"),
    ("TeamCreate", "spawn_agent"),
    ("EnterPlanMode", "# NO_CODEX_EQUIVALENT: use inline planning"),
    ("ExitPlanMode", "# NO_CODEX_EQUIVALENT: use inline planning"),
    ("TodoWrite", "update_plan"),
    ("NotebookEdit", "# NO_CODEX_EQUIVALENT: not supported"),
    ("SendMessage", "send_input"),
    ("CronCreate", "# NO_CODEX_EQUIVALENT: use external scheduler"),
    ("CronDelete", "# NO_CODEX_EQUIVALENT: use external scheduler"),
    ("CronList", "# NO_CODEX_EQUIVALENT: use external scheduler"),
)

MAPPING_TABLE_PATTERN = re.compile(
    r"(→|->|NO_CODEX_EQUIVALENT|RUNTIME_DEPENDENT|Codex Equivalent|Claude Primitive|fabricated|Previously|Does not exist)"
)
INLINE_AGENT_PATTERN = re.compile(r"\bAgent\s*\(")
INLINE_TASK_PATTERN = re.compile(r"\bTask\s*\(")
SKILL_CALL_PATTERN = re.compile(rf"""`?Skill\(['"]({SKILL_TOKEN_PATTERN})['"]\)`?""")
SKILL_REFERENCE_PATTERN = re.compile(r"`([^`\n]+)`")
SKILL_PATH_REFERENCE_PATTERN = re.compile(
    r"\.(?:claude|codex)/skills/([a-z0-9][a-z0-9\-_]*)/",
    re.IGNORECASE,
)
SUBAGENT_TYPE_PATTERN = re.compile(
    r"""subagent_type\s*[:=]\s*["']([a-z0-9][a-z0-9\-_]*)["']""",
    re.IGNORECASE,
)
ROUTING_TABLE_PATTERN = re.compile(
    r"\|\s*Keywords\s*\|\s*(?:Agent|Sub-?Agent|subagent_type|Mode)\s*\|",
    re.IGNORECASE,
)
ORCHESTRATION_PRIMITIVE_PATTERN = re.compile(r"\b(TaskCreate|TeamCreate|EnterPlanMode)\b")
MULTI_PHASE_HEADING_PATTERN = re.compile(r"^###\s+(Phase|Step)\b", re.IGNORECASE)
MODEL_HINT_PATTERN = re.compile(
    r"""model\s*[:=]\s*["']([A-Za-z0-9_.\-]*(?:opus|sonnet|haiku)[A-Za-z0-9_.\-]*)["']""",
    re.IGNORECASE,
)
SKILL_REFERENCE_CONTEXT_PATTERN = re.compile(
    r"(Use OTHER skills instead|related skills?|integration with other skills|cross-references?|deep dive|see\b|for full\b|for advanced\b|"
    r"for styling\b|general implementation guidance|framework patterns|debugging)",
    re.IGNORECASE,
)
SKILL_EXAMPLE_CONTEXT_PATTERN = re.compile(
    r"(example|examples|manual invocation|invocation|usage|syntax|mapping|equivalent|primitive|comparison|"
    r"anti-pattern|bad:|good:|trigger rules?|patterns to detect)",
    re.IGNORECASE,
)
SKILL_OPERATIONAL_CONTEXT_PATTERN = re.compile(
    r"(\b(call|invoke|run|launch|load)\s+`?Skill\s*\(|\buse\s+`?Skill\s*\(|"
    r"\b(do not|don't|never)\s+call\s+`?Skill\s*\(|^\s*`?Skill\s*\()",
    re.IGNORECASE,
)
SKILL_CALL_CONTEXT_REFERENCE = "cross_reference"
SKILL_CALL_CONTEXT_EXAMPLE = "example_only"
SKILL_CALL_CONTEXT_OPERATIONAL = "operational_invocation"
STATUS_ARCHIVED = "ARCHIVED"
STATUS_BLOCKED = "BLOCKED"
STATUS_MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
STATUS_MECHANICAL_SAFE = "MECHANICAL_SAFE"
STATUS_REDIRECTED = "REDIRECTED"
STATUS_REFACTOR_REQUIRED = "REFACTOR_REQUIRED"
KNOWN_EXTERNAL_SKILLS = {
    "find-skills",
    "gh-address-comments",
    "gh-fix-ci",
    "github",
    "imagegen",
    "openai-docs",
    "pdf",
    "plugin-creator",
    "skill-creator",
    "skill-installer",
    "yeet",
}
MANUAL_REVIEW_REQUIRED_SKILLS: set[str] = set()
NON_BLOCKING_SKILL_SECTION_HEADING_PATTERN = re.compile(
    r"^#+\s+(Troubleshooting|Related Skills|Progressive Disclosure|Evolution History|"
    r"Source Skills|Integration with Other Skills|Report|Single-mode report format|Both-mode conflict resolution|"
    r"Integration with Observation System|Cost Comparison|Full Report Template|"
    r"Cross-References(?: to Specialized Skills)?)\b",
    re.IGNORECASE,
)
SKILL_RELATIONSHIP_REFERENCE_PATTERN = re.compile(
    r"(downstream|support|sibling|relationship|replacement|merged from|what moved|"
    r"query syntax|documentation lifecycle|artifact lifecycle|catalog consolidation|historical record|source mode)",
    re.IGNORECASE,
)
BARE_SKILL_OPERATIONAL_CONTEXT_PATTERN = re.compile(
    r"\b(run|use|load|invoke|call|activate|trigger|required?|must use|before continuing|"
    r"before proceeding|continue with)\b",
    re.IGNORECASE,
)
SKILL_REFERENCE_CONTEXT_AMBIGUOUS = "ambiguous_reference"


@dataclass(frozen=True)
class Finding:
    trigger: str
    file: str
    next_action: str


@dataclass(frozen=True)
class SkillClassification:
    skill: str
    status: str
    findings: list[Finding]
    named_agents: list[str]
    missing_agents: list[str]
    referenced_skills: list[str]
    missing_skills: list[str]
    planned_claude_plugin_skills: list[str]
    ambiguous_references: list[AmbiguousSkillReference]


@dataclass(frozen=True)
class MigrationResult:
    skill: str
    status: str
    action: str
    classification: SkillClassification


@dataclass(frozen=True)
class SkillReferenceCandidate:
    token: str
    context: str


@dataclass(frozen=True)
class AmbiguousSkillReference:
    token: str
    file: str
    line: int
    heading: str | None
    snippet: str
    source_has_claude_skill: bool
    source_has_codex_skill: bool


def _normalize_agent_token(value: str) -> str:
    return value.strip().lower()


def _is_named_agent_dependency(token: str) -> bool:
    normalized = _normalize_agent_token(token)
    if normalized in GENERIC_AGENT_TYPES:
        return False
    return (SOURCE_AGENTS_DIR / f"{normalized}.md").exists()


def _codex_agent_resolved(token: str) -> bool:
    normalized = _normalize_agent_token(token)
    return (TARGET_AGENTS_DIR / f"{normalized}.toml").exists()


def _iter_markdown_files(skill_dir: Path) -> list[Path]:
    return sorted(
        path for path in skill_dir.rglob("*.md") if path.is_file() and not path.is_symlink()
    )


def _known_claude_agent_names() -> list[str]:
    if not SOURCE_AGENTS_DIR.exists():
        return []
    return sorted(path.stem.lower() for path in SOURCE_AGENTS_DIR.glob("*.md") if path.is_file())


def _known_claude_skill_names() -> set[str]:
    if not SOURCE_SKILLS_DIR.exists():
        return set()
    return {
        path.name
        for path in SOURCE_SKILLS_DIR.iterdir()
        if path.is_dir() and (path / "SKILL.md").exists()
    }


def _known_codex_skill_names() -> set[str]:
    names = set(KNOWN_EXTERNAL_SKILLS)
    names.update(discover_plugin_skill_names(codex_home=USER_CODEX_HOME, repo_root=REPO_ROOT))
    if not TARGET_SKILLS_DIR.exists():
        return names
    names.update(
        path.name
        for path in TARGET_SKILLS_DIR.iterdir()
        if path.is_dir() and (path / "SKILL.md").exists()
    )
    return names


def _collect_source_skill_dependency_edges(source_skill_names: set[str]) -> dict[str, set[str]]:
    """Collect operational source-skill dependencies between Claude skill packages."""
    known_codex_skills = _known_codex_skill_names()
    known_skill_names = source_skill_names | known_codex_skills
    edges: dict[str, set[str]] = {skill: set() for skill in source_skill_names}

    for skill in sorted(source_skill_names):
        skill_dir = SOURCE_SKILLS_DIR / skill
        if not skill_dir.exists():
            continue
        for markdown_file in _iter_markdown_files(skill_dir):
            text = markdown_file.read_text(encoding="utf-8")
            lines = text.splitlines()
            fenced_states = _compute_fenced_code_states(lines)
            for line_number, line in enumerate(lines, start=1):
                if not SKILL_CALL_PATTERN.search(line):
                    continue
                # Batch planning must treat `Skill('x')` invocations as dependencies even
                # when the wording isn't caught by the operational keyword heuristic.
                context = _classify_skill_call_context(
                    markdown_file, lines, line_number, fenced_states
                )
                if context in {
                    None,
                    SKILL_CALL_CONTEXT_REFERENCE,
                    SKILL_CALL_CONTEXT_EXAMPLE,
                }:
                    continue
                for match in SKILL_CALL_PATTERN.finditer(line):
                    token = match.group(1).strip()
                    if token == skill:
                        continue
                    if token not in known_skill_names:
                        continue
                    if token not in source_skill_names:
                        continue
                    if token in known_codex_skills:
                        continue
                    edges[skill].add(token)

    return edges


def plan_skill_batch(requested_skills: list[str]) -> BatchPlan:
    """Plan a safe migration batch for the requested source skills."""
    source_skill_names = {path.name for path in iter_source_skill_dirs()}
    dependency_edges = _collect_source_skill_dependency_edges(source_skill_names)
    return build_skill_batch_plan(
        requested_skills=list(requested_skills),
        source_skill_names=source_skill_names,
        dependency_edges=dependency_edges,
        available_codex_skills=_known_codex_skill_names(),
    )


def _find_named_agent_mentions(line: str) -> list[str]:
    mentions: list[str] = []
    normalized_line = line.lower()
    for agent_name in _known_claude_agent_names():
        pattern = rf"(?<![a-z0-9]){re.escape(agent_name)}(?![a-z0-9])"
        if re.search(pattern, normalized_line):
            mentions.append(agent_name)
    return mentions


def _append_finding(
    findings: list[Finding],
    seen: set[tuple[str, str, str]],
    *,
    category: str,
    file: str,
    trigger: str,
    next_action: str,
) -> None:
    key = (category, file, trigger)
    if key in seen:
        return
    seen.add(key)
    findings.append(Finding(trigger=trigger, file=file, next_action=next_action))


def _serialize_classification(classification: SkillClassification) -> dict[str, object]:
    return {
        "skill": classification.skill,
        "status": classification.status,
        "findings": [asdict(finding) for finding in classification.findings],
        "named_agents": classification.named_agents,
        "missing_agents": classification.missing_agents,
        "referenced_skills": classification.referenced_skills,
        "missing_skills": classification.missing_skills,
        "planned_claude_plugin_skills": classification.planned_claude_plugin_skills,
        "ambiguous_references": [asdict(reference) for reference in classification.ambiguous_references],
    }


def _serialize_result(result: MigrationResult) -> dict[str, object]:
    return {
        "skill": result.skill,
        "status": result.status,
        "action": result.action,
        "classification": _serialize_classification(result.classification),
    }


def _compute_fenced_code_states(lines: list[str]) -> list[bool]:
    states: list[bool] = []
    in_fenced_code = False
    for line in lines:
        states.append(in_fenced_code)
        if line.strip().startswith("```"):
            in_fenced_code = not in_fenced_code
    return states


def _nearest_heading(lines: list[str], line_number: int) -> str | None:
    for index in range(line_number - 1, -1, -1):
        candidate = lines[index].strip()
        if candidate.startswith("#"):
            return candidate
    return None


def _heading_level(heading: str) -> int | None:
    stripped = heading.lstrip()
    if not stripped.startswith("#"):
        return None
    return len(stripped) - len(stripped.lstrip("#"))


def _is_nested_under_non_blocking_heading(lines: list[str], line_number: int) -> bool:
    current_level: int | None = None
    for index in range(line_number - 1, -1, -1):
        candidate = lines[index].strip()
        if not candidate.startswith("#"):
            continue
        candidate_level = _heading_level(candidate)
        if candidate_level is None:
            continue
        if current_level is None or candidate_level < current_level:
            if NON_BLOCKING_SKILL_SECTION_HEADING_PATTERN.search(candidate):
                return True
            current_level = candidate_level
    return False


def _classify_skill_call_context(
    path: Path, lines: list[str], line_number: int, fenced_states: list[bool]
) -> str | None:
    line = lines[line_number - 1]
    if not SKILL_CALL_PATTERN.search(line):
        return None
    if MAPPING_TABLE_PATTERN.search(line):
        return SKILL_CALL_CONTEXT_EXAMPLE

    context = "\n".join(lines[max(0, line_number - 3) : min(len(lines), line_number + 2)])
    if fenced_states[line_number - 1]:
        return SKILL_CALL_CONTEXT_EXAMPLE
    if SKILL_EXAMPLE_CONTEXT_PATTERN.search(context):
        return SKILL_CALL_CONTEXT_EXAMPLE
    if _is_nested_under_non_blocking_heading(lines, line_number):
        return SKILL_CALL_CONTEXT_REFERENCE
    if path.as_posix().endswith("/SKILL.md") and line.lstrip().startswith("|"):
        return SKILL_CALL_CONTEXT_REFERENCE
    if SKILL_REFERENCE_CONTEXT_PATTERN.search(context):
        return SKILL_CALL_CONTEXT_REFERENCE
    if SKILL_OPERATIONAL_CONTEXT_PATTERN.search(context):
        return SKILL_CALL_CONTEXT_OPERATIONAL
    return SKILL_REFERENCE_CONTEXT_AMBIGUOUS


def _classify_skill_reference_context(
    path: Path,
    lines: list[str],
    line_number: int,
    fenced_states: list[bool],
) -> str:
    line = lines[line_number - 1]
    context = "\n".join(lines[max(0, line_number - 3) : min(len(lines), line_number + 2)])
    heading = _nearest_heading(lines, line_number)
    in_fenced_code = fenced_states[line_number - 1]

    if SKILL_CALL_PATTERN.search(line):
        skill_call_context = _classify_skill_call_context(path, lines, line_number, fenced_states)
        if skill_call_context in {
            SKILL_CALL_CONTEXT_REFERENCE,
            SKILL_CALL_CONTEXT_EXAMPLE,
        }:
            return SKILL_CALL_CONTEXT_REFERENCE
        return skill_call_context or SKILL_REFERENCE_CONTEXT_AMBIGUOUS

    if in_fenced_code:
        return SKILL_CALL_CONTEXT_REFERENCE

    if heading and NON_BLOCKING_SKILL_SECTION_HEADING_PATTERN.search(heading):
        return SKILL_CALL_CONTEXT_REFERENCE

    if _is_nested_under_non_blocking_heading(lines, line_number):
        return SKILL_CALL_CONTEXT_REFERENCE

    if path.as_posix().endswith("/SKILL.md") and line.lstrip().startswith("|"):
        if SKILL_RELATIONSHIP_REFERENCE_PATTERN.search(line) or SKILL_REFERENCE_CONTEXT_PATTERN.search(
            context
        ):
            return SKILL_CALL_CONTEXT_REFERENCE
        return SKILL_REFERENCE_CONTEXT_AMBIGUOUS

    if SKILL_REFERENCE_CONTEXT_PATTERN.search(context):
        return SKILL_CALL_CONTEXT_REFERENCE

    if SKILL_RELATIONSHIP_REFERENCE_PATTERN.search(context):
        return SKILL_CALL_CONTEXT_REFERENCE

    if BARE_SKILL_OPERATIONAL_CONTEXT_PATTERN.search(context):
        return SKILL_CALL_CONTEXT_OPERATIONAL

    return SKILL_REFERENCE_CONTEXT_AMBIGUOUS


def _extract_skill_reference_candidates(
    path: Path,
    lines: list[str],
    line_number: int,
    fenced_states: list[bool],
    known_skill_names: set[str],
) -> list[SkillReferenceCandidate]:
    line = lines[line_number - 1]
    context = "\n".join(lines[max(0, line_number - 3) : min(len(lines), line_number + 2)])
    tokens = {match.group(1).strip() for match in SKILL_CALL_PATTERN.finditer(line)}
    tokens.update(match.group(1).strip() for match in SKILL_PATH_REFERENCE_PATTERN.finditer(line))
    inline_reference_tokens = {
        candidate.strip()
        for candidate in SKILL_REFERENCE_PATTERN.findall(line)
        if candidate.strip() in known_skill_names
    }
    is_skill_table_row = path.as_posix().endswith("/SKILL.md") and line.lstrip().startswith("|")

    if (
        not tokens
        and not inline_reference_tokens
        and not is_skill_table_row
        and not SKILL_REFERENCE_CONTEXT_PATTERN.search(context)
    ):
        return []

    tokens.update(inline_reference_tokens)

    if fenced_states[line_number - 1] and not SKILL_CALL_PATTERN.search(line):
        return [
            SkillReferenceCandidate(token=token, context=SKILL_CALL_CONTEXT_REFERENCE)
            for token in sorted(tokens)
        ]

    context_kind = _classify_skill_reference_context(path, lines, line_number, fenced_states)
    return [
        SkillReferenceCandidate(token=token, context=context_kind) for token in sorted(tokens)
    ]


def neutralize_skill_references(text: str, src: Path) -> str:
    """Replace non-operational Skill('x') mentions with plain skill-name references."""

    lines = text.splitlines(keepends=True)
    bare_lines = [line.rstrip("\n") for line in lines]
    fenced_states = _compute_fenced_code_states(bare_lines)
    transformed: list[str] = []

    for line_number, line in enumerate(lines, start=1):
        context = _classify_skill_call_context(src, bare_lines, line_number, fenced_states)
        if context in {None, SKILL_CALL_CONTEXT_OPERATIONAL}:
            transformed.append(line)
            continue

        replaced = SKILL_CALL_PATTERN.sub(lambda match: f"`{match.group(1)}`", line)
        transformed.append(replaced)

    return "".join(transformed)


def classify_skill(
    skill_dir: Path,
    *,
    batch_source_skills: set[str] | None = None,
    claude_plugin_skills: set[str] | None = None,
    known_codex_skills: set[str] | None = None,
    known_claude_skills: set[str] | None = None,
) -> SkillClassification:
    findings: list[Finding] = []
    seen_findings: set[tuple[str, str, str]] = set()
    named_agents: set[str] = set()
    missing_agents: set[str] = set()
    referenced_skills: set[str] = set()
    missing_skills: set[str] = set()
    planned_claude_plugin_skills: set[str] = set()
    ambiguous_references: list[AmbiguousSkillReference] = []
    seen_ambiguous_references: set[tuple[str, str, int]] = set()
    has_refactor_risk = False
    known_claude_skills = known_claude_skills or _known_claude_skill_names()
    known_codex_skills = known_codex_skills or _known_codex_skill_names()
    claude_plugin_skills = claude_plugin_skills or set()
    known_skill_names = known_claude_skills | known_codex_skills | set(claude_plugin_skills)

    for markdown_file in _iter_markdown_files(skill_dir):
        relative_file = markdown_file.relative_to(skill_dir).as_posix()
        text = markdown_file.read_text(encoding="utf-8")
        lines = text.splitlines()
        fenced_states = _compute_fenced_code_states(lines)
        multi_phase_hits = 0
        file_has_orchestration_signal = False

        for line_number, line in enumerate(lines, start=1):
            if INLINE_AGENT_PATTERN.search(line):
                has_refactor_risk = True
                file_has_orchestration_signal = True
                _append_finding(
                    findings,
                    seen_findings,
                    category="inline-agent",
                    file=f"{relative_file}:{line_number}",
                    trigger="inline Claude Agent() site",
                    next_action=(
                        "hand-author using .codex/skills/migrate-agents-to-codex/"
                        "SKILL.md guidance for delegated behavior"
                    ),
                )
            if INLINE_TASK_PATTERN.search(line):
                has_refactor_risk = True
                file_has_orchestration_signal = True
                _append_finding(
                    findings,
                    seen_findings,
                    category="inline-task",
                    file=f"{relative_file}:{line_number}",
                    trigger="inline Claude Task() site",
                    next_action="hand-author; do not mechanically preserve inline delegated semantics",
                )
            if MAPPING_TABLE_PATTERN.search(line):
                continue

            for match in SUBAGENT_TYPE_PATTERN.finditer(line):
                token = _normalize_agent_token(match.group(1))
                if not _is_named_agent_dependency(token):
                    continue
                file_has_orchestration_signal = True
                named_agents.add(token)
                if not _codex_agent_resolved(token):
                    missing_agents.add(token)
                    _append_finding(
                        findings,
                        seen_findings,
                        category=f"missing-agent:{token}",
                        file=f"{relative_file}:{line_number}",
                        trigger=f"named agent dependency: {token} (.codex/agents/{token}.toml missing)",
                        next_action=(
                            "run python3 .codex/skills/migrate-agents-to-codex/scripts/"
                            f"migrate_claude_agents_to_codex.py --agent {token} first"
                        ),
                    )

            line_agent_mentions = _find_named_agent_mentions(line)
            if line_agent_mentions and (
                line.lstrip().startswith("|")
                or "agent" in line.lower()
                or "subagent" in line.lower()
                or "route" in line.lower()
                or "launch" in line.lower()
                or "spawn" in line.lower()
            ):
                file_has_orchestration_signal = True
                for token in line_agent_mentions:
                    if not _is_named_agent_dependency(token):
                        continue
                    named_agents.add(token)
                    if not _codex_agent_resolved(token):
                        missing_agents.add(token)
                        _append_finding(
                            findings,
                            seen_findings,
                            category=f"missing-agent-line:{token}",
                            file=f"{relative_file}:{line_number}",
                            trigger=f"named agent dependency: {token} (.codex/agents/{token}.toml missing)",
                            next_action=(
                                "run python3 .codex/skills/migrate-agents-to-codex/scripts/"
                                f"migrate_claude_agents_to_codex.py --agent {token} first"
                            ),
                        )

            if ROUTING_TABLE_PATTERN.search(line):
                has_refactor_risk = True
                file_has_orchestration_signal = True
                _append_finding(
                    findings,
                    seen_findings,
                    category="routing-table",
                    file=f"{relative_file}:{line_number}",
                    trigger="routing table detected",
                    next_action=(
                        "hand-author dependency resolution and ensure all named agents are migrated via "
                        ".codex/skills/migrate-agents-to-codex/SKILL.md"
                    ),
                )

            if ORCHESTRATION_PRIMITIVE_PATTERN.search(line):
                has_refactor_risk = True
                file_has_orchestration_signal = True
                _append_finding(
                    findings,
                    seen_findings,
                    category="orchestration-primitive",
                    file=f"{relative_file}:{line_number}",
                    trigger="orchestration complexity primitive detected",
                    next_action="hand-author Tier 3 native skill",
                )

            for candidate in _extract_skill_reference_candidates(
                markdown_file, lines, line_number, fenced_states, known_skill_names
            ):
                token = candidate.token
                if token == skill_dir.name:
                    continue
                referenced_skills.add(token)
                if token in KNOWN_EXTERNAL_SKILLS:
                    continue
                token_has_claude_skill = token in known_claude_skills
                token_has_codex_skill = token in known_codex_skills
                if candidate.context == SKILL_REFERENCE_CONTEXT_AMBIGUOUS:
                    if not token_has_claude_skill or token_has_codex_skill:
                        continue
                    ambiguous_key = (token, relative_file, line_number)
                    if ambiguous_key not in seen_ambiguous_references:
                        seen_ambiguous_references.add(ambiguous_key)
                        ambiguous_references.append(
                            AmbiguousSkillReference(
                                token=token,
                                file=relative_file,
                                line=line_number,
                                heading=_nearest_heading(lines, line_number),
                                snippet=line.strip(),
                                source_has_claude_skill=True,
                                source_has_codex_skill=False,
                            )
                        )
                    _append_finding(
                        findings,
                        seen_findings,
                        category=f"ambiguous-skill:{token}",
                        file=f"{relative_file}:{line_number}",
                        trigger=f"AMBIGUOUS skill reference: {token}",
                        next_action=(
                            "review manually or route this candidate through the mini-auditor pass "
                            "before treating it as a runtime dependency"
                        ),
                    )
                    continue
                if (
                    candidate.context == SKILL_CALL_CONTEXT_OPERATIONAL
                ):
                    if token in KNOWN_EXTERNAL_SKILLS or token_has_codex_skill:
                        continue
                    if batch_source_skills and token in batch_source_skills:
                        continue
                    if token_has_claude_skill and not token_has_codex_skill:
                        missing_skills.add(token)
                        _append_finding(
                            findings,
                            seen_findings,
                            category=f"missing-skill:{token}",
                            file=f"{relative_file}:{line_number}",
                            trigger=(
                                f"hard skill dependency: {token} "
                                f"(.codex/skills/{token}/ missing; only .claude/skills/{token}/ exists)"
                            ),
                            next_action=(
                                "cannot proceed with migration because there is a hard dependency on "
                                f"`{token}`. Please migrate that skill first."
                            ),
                        )
                        continue
                    if token in claude_plugin_skills:
                        planned_claude_plugin_skills.add(token)
                        _append_finding(
                            findings,
                            seen_findings,
                            category=f"claude-plugin-skill:{token}",
                            file=f"{relative_file}:{line_number}",
                            trigger=f"Claude plugin skill dependency: {token}",
                            next_action=(
                                "this dependency can be satisfied by migrating the Claude plugin skill "
                                "into a Codex plugin (on-demand)"
                            ),
                        )
                        continue

                    missing_skills.add(token)
                    _append_finding(
                        findings,
                        seen_findings,
                        category=f"missing-skill:{token}",
                        file=f"{relative_file}:{line_number}",
                        trigger=f"missing operational skill dependency: {token}",
                        next_action=(
                            "install or migrate the missing dependency, or rewrite the guidance to avoid "
                            "an operational Skill() invocation"
                        ),
                    )

            skill_call_context = _classify_skill_call_context(
                markdown_file, lines, line_number, fenced_states
            )
            if skill_call_context == SKILL_CALL_CONTEXT_OPERATIONAL:
                has_refactor_risk = True
                _append_finding(
                    findings,
                    seen_findings,
                    category="legacy-skill-invocation",
                    file=f"{relative_file}:{line_number}",
                    trigger="legacy Skill() invocation in operational guidance",
                    next_action=(
                        "rewrite to Codex-native skill-file guidance or neutralized wording; "
                        "do not preserve Skill() syntax"
                    ),
                )

            model_match = MODEL_HINT_PATTERN.search(line)
            if model_match:
                _append_finding(
                    findings,
                    seen_findings,
                    category=f"model-hint:{model_match.group(1).lower()}",
                    file=f"{relative_file}:{line_number}",
                    trigger=f'NOTE: model hint "{model_match.group(1)}"',
                    next_action=(
                        "when hand-authoring, use intent-based mapping from "
                        ".codex/skills/migrate-agents-to-codex/references/"
                        "subagent-migration-guide.md"
                    ),
                )

            if MULTI_PHASE_HEADING_PATTERN.search(line):
                multi_phase_hits += 1

        if multi_phase_hits >= 3 and file_has_orchestration_signal:
            has_refactor_risk = True
            _append_finding(
                findings,
                seen_findings,
                category="multi-phase",
                file=relative_file,
                trigger=f"orchestration complexity: multi-phase structure ({multi_phase_hits} headings)",
                next_action="hand-author Tier 3 native skill",
            )

    if skill_dir.name in MANUAL_REVIEW_REQUIRED_SKILLS:
        has_refactor_risk = True
        _append_finding(
            findings,
            seen_findings,
            category=f"manual-review:{skill_dir.name}",
            file="SKILL.md",
            trigger="manual override: treat this migration as not mechanically safe",
            next_action=(
                "fragile workflow semantics require manual review or hand-authoring; "
                "do not use deterministic migration for this skill"
            ),
        )

    if missing_agents or missing_skills:
        status = STATUS_BLOCKED
    elif has_refactor_risk:
        status = STATUS_REFACTOR_REQUIRED
    elif ambiguous_references:
        status = STATUS_MANUAL_REVIEW_REQUIRED
    else:
        status = STATUS_MECHANICAL_SAFE

    return SkillClassification(
        skill=skill_dir.name,
        status=status,
        findings=findings,
        named_agents=sorted(named_agents),
        missing_agents=sorted(missing_agents),
        referenced_skills=sorted(referenced_skills),
        missing_skills=sorted(missing_skills),
        planned_claude_plugin_skills=sorted(planned_claude_plugin_skills),
        ambiguous_references=sorted(
            ambiguous_references,
            key=lambda reference: (reference.file, reference.line, reference.token),
        ),
    )


def print_classification(classification: SkillClassification) -> None:
    print(f"{classification.skill}: {classification.status}")
    if not classification.findings:
        print("  ✓ no risky orchestration patterns detected")
        print("    → deterministic migration is safe to run")
        return

    for finding in classification.findings:
        bullet = (
            "⚠"
            if finding.trigger.startswith("NOTE:") or finding.trigger.startswith("AMBIGUOUS")
            else "✗"
        )
        print(f"  {bullet} {finding.trigger} ({finding.file})")
        print(f"    → {finding.next_action}")


def normalize_mcp_namespaces(text: str) -> str:
    """Normalize server segment in callable MCP namespaces."""

    def repl(match: re.Match[str]) -> str:
        segment = match.group(1)
        return f"mcp__{segment.replace('-', '_')}__"

    return re.sub(r"mcp__([a-z0-9][a-z0-9\-]*)__", repl, text)


def rewrite_self_skill_paths(text: str, src: Path) -> str:
    """Rewrite legacy self-package skill paths to portable relative paths."""

    parts = src.parts
    try:
        skills_index = parts.index("skills")
    except ValueError:
        return text
    if skills_index + 1 >= len(parts):
        return text

    skill_name = parts[skills_index + 1]
    skill_root = Path(*parts[: skills_index + 2])
    current_dir = src.parent
    pattern = re.compile(
        rf"\.(?:claude|codex)/skills/{re.escape(skill_name)}"
        rf"(?=/|[^A-Za-z0-9._-]|$)(?:/([A-Za-z0-9._/\-]+))?"
    )

    def repl(match: re.Match[str]) -> str:
        suffix = match.group(1)
        target = skill_root / suffix if suffix else skill_root
        portable = Path(os.path.relpath(target, current_dir)).as_posix()
        return "." if portable == "" else portable

    return pattern.sub(repl, text)


def apply_primitive_mappings(text: str) -> str:
    """Replace source primitives only in executable-like contexts."""

    lines = text.splitlines(keepends=True)
    result: list[str] = []
    for line in lines:
        if MAPPING_TABLE_PATTERN.search(line):
            result.append(line)
            continue
        modified = line
        for old, new in PRIMITIVE_REPLACEMENTS:
            modified = re.sub(rf"\b{re.escape(old)}\b", new, modified)
        result.append(modified)
    return "".join(result)


def make_banner(src: Path) -> str:
    """Create a provenance banner without leaking old-source path literals."""

    source_name = src.parent.name if src.name == "SKILL.md" else src.name
    safe_name = safe_provenance_value(source_name)
    return (
        "<!--\n"
        "AUTO-GENERATED FILE\n"
        f"Source artifact: {safe_name}\n"
        "Generated by: .codex/skills/migrate-to-codex/scripts/migrate_claude_workflows_to_codex.py\n"
        "Notes:\n"
        "- Namespace and orchestration primitives were mechanically normalized.\n"
        "- Recorded manual nativeness review is required before this artifact may be treated as native Codex.\n"
        "-->\n\n"
    )


def insert_banner_after_frontmatter(text: str, banner: str) -> str:
    stripped = text.lstrip()
    if not stripped.startswith("---"):
        return banner + text

    first_end = stripped.find("\n---", 3)
    if first_end == -1:
        return banner + text

    leading_ws = text[: len(text) - len(stripped)]
    frontmatter_end = first_end + len("\n---")
    frontmatter = leading_ws + stripped[:frontmatter_end]
    body = stripped[frontmatter_end:]
    return frontmatter + "\n\n" + banner + body


def sanitize_frontmatter(text: str) -> str:
    stripped = text.lstrip()
    if not stripped.startswith("---\n"):
        return text

    end_marker = stripped.find("\n---\n", 4)
    if end_marker == -1:
        return text

    leading_ws = text[: len(text) - len(stripped)]
    frontmatter_text = stripped[4:end_marker]
    body = stripped[end_marker + len("\n---\n") :]

    try:
        data = yaml.safe_load(frontmatter_text)
    except yaml.YAMLError:
        return text

    if not isinstance(data, dict):
        return text

    sanitized = {
        key: value for key, value in data.items() if key not in PROHIBITED_FRONTMATTER_FIELDS
    }
    dumped = yaml.safe_dump(sanitized, sort_keys=False, allow_unicode=True).strip()
    return f"{leading_ws}---\n{dumped}\n---\n{body}"


def transform_markdown(content: str, src: Path) -> str:
    transformed = normalize_mcp_namespaces(content)
    transformed = rewrite_self_skill_paths(transformed, src)
    transformed = apply_primitive_mappings(transformed)
    transformed = neutralize_skill_references(transformed, src)
    transformed = sanitize_frontmatter(transformed)
    return insert_banner_after_frontmatter(transformed, make_banner(src))


def write_transformed_file(src_file: Path, dst_file: Path, dry_run: bool) -> None:
    if src_file.is_symlink():
        raise ValueError(f"Refusing to migrate symlinked source file: {src_file}")
    content = src_file.read_text(encoding="utf-8")
    transformed = transform_markdown(content, src_file)
    if dry_run:
        return
    dst_file.parent.mkdir(parents=True, exist_ok=True)
    dst_file.write_text(transformed, encoding="utf-8")


def migrate_path(src: Path, dst: Path, dry_run: bool) -> None:
    if not src.exists():
        raise FileNotFoundError(f"Source path does not exist: {src}")

    src = resolve_within_root(SOURCE_SKILLS_DIR, src, kind="skill source path")
    if src.is_file():
        if src.suffix.lower() == ".md":
            write_transformed_file(src, dst, dry_run=dry_run)
        elif not dry_run:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
        return

    for src_file in src.rglob("*"):
        if src_file.is_dir():
            continue
        if src_file.is_symlink():
            raise ValueError(f"Refusing to migrate symlinked source file: {src_file}")
        rel = src_file.relative_to(src)
        dst_file = dst / rel
        if src_file.suffix.lower() == ".md":
            write_transformed_file(src_file, dst_file, dry_run=dry_run)
        elif not dry_run:
            dst_file.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_file, dst_file)


def is_archived_or_redirected(skill_md: Path) -> bool:
    first_lines = skill_md.read_text(encoding="utf-8")[:500].upper()
    return "ARCHIVED" in first_lines or "REDIRECTED" in first_lines


def redirected_or_archived_summary(skill_md: Path) -> tuple[str, str | None]:
    text = skill_md.read_text(encoding="utf-8")
    first_lines = text[:500].upper()
    if "REDIRECTED" in first_lines:
        replacement_match = re.search(r"\*\*Replacement\*\*:\s*(.+)", text)
        replacement = replacement_match.group(1).strip() if replacement_match else None
        return (STATUS_REDIRECTED, replacement)
    if "ARCHIVED" in first_lines:
        return (STATUS_ARCHIVED, None)
    raise ValueError(f"{skill_md} is not archived or redirected")


def iter_source_skill_dirs() -> list[Path]:
    skill_dirs: list[Path] = []
    for skill_dir in sorted(SOURCE_SKILLS_DIR.iterdir()):
        if not skill_dir.is_dir():
            continue
        if skill_dir.is_symlink():
            continue
        if skill_dir.name == "migrate-to-codex":
            continue
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            continue
        if is_archived_or_redirected(skill_md):
            continue
        skill_dirs.append(skill_dir)
    return skill_dirs


def _find_symlinked_source_files(skill_dir: Path) -> list[Path]:
    """Return symlinked files within a source skill tree."""
    return sorted(path for path in skill_dir.rglob("*") if path.is_symlink())


def _blocked_classification(skill: str, trigger: str, next_action: str) -> SkillClassification:
    return SkillClassification(
        skill=skill,
        status=STATUS_BLOCKED,
        findings=[Finding(trigger=trigger, file="SKILL.md", next_action=next_action)],
        named_agents=[],
        missing_agents=[],
        referenced_skills=[],
        missing_skills=[],
        planned_claude_plugin_skills=[],
        ambiguous_references=[],
    )


def _print_batch_plan(plan: BatchPlan) -> None:
    print("Batch plan:")
    print(f"  Requested: {', '.join(plan.requested_skills) if plan.requested_skills else '<none>'}")
    print(f"  Expanded: {', '.join(plan.expanded_skills) if plan.expanded_skills else '<none>'}")
    if plan.cycles:
        print("  Cycle groups:")
        for component in plan.cycles:
            print(f"    - {', '.join(component)}")
    if plan.execution_groups:
        print("  Execution groups:")
        for component in plan.execution_groups:
            print(f"    - {', '.join(component)}")


def _plugin_token_parts(token: str) -> tuple[str, str] | None:
    if ":" not in token:
        return None
    plugin, skill = (part.strip() for part in token.split(":", 1))
    if not plugin or not skill:
        return None
    return plugin, skill


def _build_runtime_install_plan(
    *,
    plugin_skill_tokens: set[str],
    claude_home: Path,
) -> RuntimeInstallPlan:
    writes: list[RuntimeFileWrite] = []
    copies: list[RuntimeFileCopy] = []
    hook_commands: list[str] = []
    config_plugins: dict[str, dict[str, object]] = {}

    notify_path = claude_home / "notify.sh"
    if notify_path.is_file():
        copies.append(RuntimeFileCopy(source=notify_path, relative_target=Path("notify.sh")))
        hook_commands.append("bash ~/.codex/notify.sh")

    for token in sorted(plugin_skill_tokens):
        parts = _plugin_token_parts(token)
        if parts is None:
            continue
        plugin, skill = parts
        source_dir = find_claude_plugin_skill_dir(token, claude_home=claude_home)
        if source_dir is None:
            raise FileNotFoundError(f"Claude plugin skill not found on disk: {token}")

        plugin_root = Path("plugins") / "claude-migrated" / plugin
        manifest_rel = plugin_root / ".codex-plugin" / "plugin.json"
        writes.append(
            RuntimeFileWrite(
                relative_target=manifest_rel,
                content=json.dumps({"name": plugin, "skills": "./skills/"}, indent=2, sort_keys=True),
            )
        )
        config_plugins.setdefault(plugin, {})["enabled"] = True

        for src_file in sorted(source_dir.rglob("*")):
            if src_file.is_dir():
                continue
            if src_file.is_symlink():
                raise ValueError(f"Refusing to install symlinked Claude plugin file: {src_file}")
            rel = src_file.relative_to(source_dir)
            target_rel = plugin_root / "skills" / skill / rel
            copies.append(RuntimeFileCopy(source=src_file, relative_target=target_rel))

    return RuntimeInstallPlan(
        files=copies,
        writes=writes,
        hook_commands=hook_commands,
        config_plugins=config_plugins,
    )


def _migrate_skill_once(
    skill: str,
    dry_run: bool,
    analysis_only: bool,
    *,
    target_skills_dir: Path | None = None,
    emit_text: bool = True,
    batch_source_skills: set[str] | None = None,
    claude_plugin_skills: set[str] | None = None,
    planned_plugin_tokens: set[str] | None = None,
) -> MigrationResult:
    dst_root = target_skills_dir or TARGET_SKILLS_DIR
    invalid_skill = validate_identifier(skill, kind="skill")
    if invalid_skill is not None:
        if emit_text:
            print(f"{skill}: {STATUS_BLOCKED}")
            print(f"  → {invalid_skill}")
        classification = _blocked_classification(
            skill,
            trigger=invalid_skill,
            next_action="rename the source skill to a safe slug before rerunning migration",
        )
        return MigrationResult(
            skill=skill,
            status=classification.status,
            action="blocked",
            classification=classification,
        )

    src = resolve_within_root(
        SOURCE_SKILLS_DIR,
        SOURCE_SKILLS_DIR / skill,
        kind="skill source path",
    )
    dst = resolve_within_root(
        dst_root,
        dst_root / skill,
        kind="skill target path",
    )
    if not src.exists():
        raise FileNotFoundError(f"Source path does not exist: {src}")
    skill_md = src / "SKILL.md"
    if skill_md.exists() and is_archived_or_redirected(skill_md):
        status, replacement = redirected_or_archived_summary(skill_md)
        if emit_text:
            print(f"{skill}: {status}")
            if status == STATUS_REDIRECTED:
                print("  → source skill is redirected; do not migrate the legacy artifact directly")
                if replacement:
                    print(f"  → replacement: {replacement}")
            else:
                print("  → source skill is archived; no migration should be generated")
            print("  → no transform executed")
        return MigrationResult(
            skill=skill,
            status=status,
            action="redirected" if status == STATUS_REDIRECTED else "archived",
            classification=SkillClassification(
                skill=skill,
                status=status,
                findings=[],
                named_agents=[],
                missing_agents=[],
                referenced_skills=[],
                missing_skills=[],
                planned_claude_plugin_skills=[],
                ambiguous_references=[],
            ),
        )

    symlinked_files = _find_symlinked_source_files(src)
    if symlinked_files:
        trigger = f"symlinked source file detected: {symlinked_files[0].relative_to(src).as_posix()}"
        classification = _blocked_classification(
            skill,
            trigger=trigger,
            next_action="remove or replace symlinked files before rerunning migration",
        )
        if emit_text:
            print_classification(classification)
            print("  → blocked; remove symlinked files and rerun")
        return MigrationResult(
            skill=skill,
            status=classification.status,
            action="blocked",
            classification=classification,
        )

    classification = classify_skill(
        src,
        batch_source_skills=batch_source_skills,
        claude_plugin_skills=claude_plugin_skills,
    )
    if planned_plugin_tokens is not None:
        planned_plugin_tokens.update(classification.planned_claude_plugin_skills)
    if emit_text:
        print_classification(classification)

    if analysis_only:
        if emit_text:
            print("  → analysis only; no transform executed")
        return MigrationResult(
            skill=skill,
            status=classification.status,
            action="analysis-only",
            classification=classification,
        )

    if classification.status == STATUS_MECHANICAL_SAFE:
        migrate_path(src, dst, dry_run=dry_run)
        if emit_text:
            if dry_run:
                print("  → dry run complete; deterministic migration would proceed")
                print(
                    "    post-write state: pending_native_review until manual nativeness review is recorded"
                )
            else:
                print("  → deterministic migration completed")
                print(
                    "    post-write state: pending_native_review; record manual nativeness review before treating as native"
                )
        return MigrationResult(
            skill=skill,
            status=classification.status,
            action="migrated" if not dry_run else "dry-run",
            classification=classification,
        )

    if emit_text:
        if classification.status == STATUS_BLOCKED:
            print("  → blocked; resolve hard skill or agent dependencies and rerun")
        elif classification.status == STATUS_MANUAL_REVIEW_REQUIRED:
            print("  → manual review required; adjudicate ambiguous skill references before rerunning")
        else:
            print("  → skipped; hand-author this migration before rerunning")
    return MigrationResult(
        skill=skill,
        status=classification.status,
        action=(
            "blocked"
            if classification.status == STATUS_BLOCKED
            else (
                "manual-review-required"
                if classification.status == STATUS_MANUAL_REVIEW_REQUIRED
                else "refactor-required"
            )
        ),
        classification=classification,
    )


def migrate_batch(
    requested_skills: list[str],
    dry_run: bool,
    analysis_only: bool,
    *,
    target_skills_dir: Path | None = None,
    emit_text: bool = True,
    install_runtime: bool = False,
) -> list[MigrationResult]:
    plan = plan_skill_batch(requested_skills)
    batch_source_skills = set(plan.expanded_skills)
    claude_plugin_skills = set(discover_claude_plugin_skill_names(claude_home=USER_CLAUDE_HOME))

    if emit_text:
        _print_batch_plan(plan)
        print("")

    dst_root = target_skills_dir or TARGET_SKILLS_DIR
    results: list[MigrationResult] = []
    planned_plugin_tokens: set[str] = set()

    for component in plan.execution_groups:
        for skill in component:
            result = _migrate_skill_once(
                skill,
                dry_run=dry_run,
                analysis_only=analysis_only,
                target_skills_dir=dst_root,
                emit_text=emit_text,
                batch_source_skills=batch_source_skills,
                claude_plugin_skills=claude_plugin_skills,
                planned_plugin_tokens=planned_plugin_tokens,
            )
            results.append(result)
            if emit_text:
                print("")

    if install_runtime and not dry_run and not analysis_only:
        runtime_plan = _build_runtime_install_plan(
            plugin_skill_tokens=planned_plugin_tokens,
            claude_home=USER_CLAUDE_HOME,
        )
        if (
            runtime_plan.files
            or runtime_plan.writes
            or runtime_plan.hook_commands
            or runtime_plan.config_plugins
        ):
            install_runtime_assets(runtime_plan, codex_home=USER_CODEX_HOME, dry_run=False)
            # Plugin discovery is cached; clear to make future runs reflect newly installed skills.
            discover_plugin_skill_names.cache_clear()

    return results


def migrate_skill(
    skill: str,
    dry_run: bool,
    analysis_only: bool,
    *,
    target_skills_dir: Path | None = None,
    emit_text: bool = True,
    install_runtime: bool = False,
) -> MigrationResult:
    invalid_skill = validate_identifier(skill, kind="skill")
    if invalid_skill is not None:
        if emit_text:
            print(f"{skill}: {STATUS_BLOCKED}")
            print(f"  → {invalid_skill}")
        classification = _blocked_classification(
            skill,
            trigger=invalid_skill,
            next_action="rename the source skill to a safe slug before rerunning migration",
        )
        return MigrationResult(
            skill=skill,
            status=classification.status,
            action="blocked",
            classification=classification,
        )

    src = resolve_within_root(
        SOURCE_SKILLS_DIR,
        SOURCE_SKILLS_DIR / skill,
        kind="skill source path",
    )
    if not src.exists():
        raise FileNotFoundError(f"Source path does not exist: {src}")
    skill_md = src / "SKILL.md"
    if skill_md.exists() and is_archived_or_redirected(skill_md):
        # Preserve existing behavior: redirected/archived short-circuit returns a single result.
        return _migrate_skill_once(
            skill,
            dry_run=dry_run,
            analysis_only=analysis_only,
            target_skills_dir=target_skills_dir,
            emit_text=emit_text,
        )

    symlinked_files = _find_symlinked_source_files(src)
    if symlinked_files:
        # Preserve existing behavior: do not migrate unrelated dependencies if the requested target is unsafe.
        return _migrate_skill_once(
            skill,
            dry_run=dry_run,
            analysis_only=analysis_only,
            target_skills_dir=target_skills_dir,
            emit_text=emit_text,
        )

    batch_results = migrate_batch(
        [skill],
        dry_run=dry_run,
        analysis_only=analysis_only,
        target_skills_dir=target_skills_dir,
        emit_text=emit_text,
        install_runtime=install_runtime,
    )
    for result in batch_results:
        if result.skill == skill:
            return result
    raise RuntimeError(f"Requested skill {skill!r} missing from batch results")


def migrate_all(
    dry_run: bool,
    analysis_only: bool,
    *,
    target_skills_dir: Path | None = None,
    emit_text: bool = True,
    install_runtime: bool = False,
) -> list[MigrationResult]:
    results = migrate_batch(
        [path.name for path in iter_source_skill_dirs()],
        dry_run=dry_run,
        analysis_only=analysis_only,
        target_skills_dir=target_skills_dir,
        emit_text=emit_text,
        install_runtime=install_runtime,
    )

    by_status = {
        STATUS_MECHANICAL_SAFE: 0,
        STATUS_REFACTOR_REQUIRED: 0,
        STATUS_MANUAL_REVIEW_REQUIRED: 0,
        STATUS_BLOCKED: 0,
    }
    migrated = 0
    dry_runs = 0
    refactor_required = 0
    manual_review_required = 0
    blocked = 0
    for result in results:
        by_status[result.status] += 1
        if result.action == "migrated":
            migrated += 1
        elif result.action == "dry-run":
            dry_runs += 1
        elif result.action == "refactor-required":
            refactor_required += 1
        elif result.action == "manual-review-required":
            manual_review_required += 1
        elif result.action == "blocked":
            blocked += 1

    if emit_text:
        print("\nSummary:")
        print(f"  Total analyzed: {len(results)}")
        print(f"  Mechanical safe: {by_status[STATUS_MECHANICAL_SAFE]}")
        print(f"  Refactor required: {by_status[STATUS_REFACTOR_REQUIRED]}")
        print(f"  Manual review required: {by_status[STATUS_MANUAL_REVIEW_REQUIRED]}")
        print(f"  Blocked: {by_status[STATUS_BLOCKED]}")
        if analysis_only:
            print("  Mode: analysis-only")
        else:
            print(f"  Migrated: {migrated}")
            print(f"  Dry run ready: {dry_runs}")
            print(f"  Refactor-required skips: {refactor_required}")
            print(f"  Manual-review-required skips: {manual_review_required}")
            print(f"  Blocked skips: {blocked}")
            if migrated:
                print(
                    "  Review required: all mechanically generated artifacts enter pending_native_review"
                )
    return results


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Migrate source skills to Codex-compatible artifacts."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Compute transformations without writing files.",
    )
    parser.add_argument(
        "--analysis-only",
        action="store_true",
        help="Classify skills and print findings without transforming files.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        dest="json_output",
        help="Emit structured JSON output instead of human-readable text.",
    )
    parser.add_argument(
        "--no-install-runtime",
        action="store_true",
        dest="no_install_runtime",
        help="Do not install runtime assets (hooks/config/plugins) into the user's CODEX_HOME.",
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--skill",
        type=str,
        default=None,
        help="Migrate a single source skill by name.",
    )
    group.add_argument(
        "--all",
        action="store_true",
        dest="all_skills",
        help="Migrate all non-archived source skills.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.skill:
        result = migrate_skill(
            args.skill,
            dry_run=args.dry_run,
            analysis_only=args.analysis_only,
            emit_text=not args.json_output,
            install_runtime=not args.no_install_runtime,
        )
        if args.json_output:
            print(json.dumps(_serialize_result(result), indent=2))
        return 0

    results = migrate_all(
        dry_run=args.dry_run,
        analysis_only=args.analysis_only,
        emit_text=not args.json_output,
        install_runtime=not args.no_install_runtime,
    )
    if args.json_output:
        by_status = {
            STATUS_MECHANICAL_SAFE: 0,
            STATUS_REFACTOR_REQUIRED: 0,
            STATUS_MANUAL_REVIEW_REQUIRED: 0,
            STATUS_BLOCKED: 0,
        }
        for result in results:
            if result.status in by_status:
                by_status[result.status] += 1
        print(
            json.dumps(
                {
                    "results": [_serialize_result(result) for result in results],
                    "summary": {
                        "total_analyzed": len(results),
                        "by_status": by_status,
                        "mode": "analysis-only" if args.analysis_only else "transform",
                    },
                },
                indent=2,
            )
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
