#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Orchestrate deterministic Codex migration through nativeness-review handoff."""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path


def _find_repo_root() -> Path:
    p = Path(__file__).resolve().parent
    while p != p.parent:
        if (p / ".git").exists() or (p / "package.json").exists():
            return p
        p = p.parent
    raise RuntimeError("Repository root not found")


REPO_ROOT = _find_repo_root()
_SUPPORT_SRC = REPO_ROOT / "tools"
if str(_SUPPORT_SRC) not in sys.path:
    sys.path.insert(0, str(_SUPPORT_SRC))

from migration_support import nativeness  # noqa: E402
from migration_support.safety import describe_path_for_display  # noqa: E402

MIGRATOR_PATH = Path(__file__).with_name("migrate_claude_workflows_to_codex.py")
DOCTOR_PATH = Path(__file__).with_name("migration_doctor.py")
VALIDATOR_PATH = (
    REPO_ROOT
    / ".codex"
    / "skills"
    / "verify-skill-migration"
    / "scripts"
    / "validate_skill_migration.py"
)
DASHBOARD_PATH = (
    REPO_ROOT
    / ".codex"
    / "skills"
    / "migration-dashboard"
    / "scripts"
    / "analyze_migration.py"
)


def _load_module(module_name: str, path: Path):
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load module from {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


migrator = _load_module("migration_workflow_migrator", MIGRATOR_PATH)
doctor = _load_module("migration_workflow_doctor", DOCTOR_PATH)
validator = _load_module("migration_workflow_validator", VALIDATOR_PATH)
dashboard = _load_module("migration_workflow_dashboard", DASHBOARD_PATH)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run deterministic Codex migration through structural validation and "
            "nativeness-review handoff."
        )
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--skill", type=str, help="Run the workflow for one source skill.")
    group.add_argument(
        "--all",
        action="store_true",
        dest="all_skills",
        help="Run the workflow for every non-archived source skill (default).",
    )
    parser.add_argument(
        "--preview",
        action="store_true",
        help="Materialize generated output into a preview tree instead of .codex/skills.",
    )
    parser.add_argument(
        "--preview-dir",
        type=Path,
        help="Explicit preview root. Defaults to a new /tmp directory when --preview is used.",
    )
    parser.add_argument(
        "--report-dir",
        type=Path,
        default=Path(tempfile.gettempdir()) / "codex-migration-evidence",
        help="Directory for live-run markdown evidence reports (default: /tmp/codex-migration-evidence).",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        dest="json_output",
        help="Emit structured JSON instead of human-readable text.",
    )
    return parser.parse_args()


def _resolve_preview_root(preview_dir: Path | None) -> Path:
    if preview_dir is not None:
        return preview_dir
    return Path(tempfile.mkdtemp(prefix="codex-migration-preview-"))


def _validate_scan_dir(scan_dir: Path) -> dict[str, object]:
    scan_dirs = (scan_dir,)
    markdown_files = validator.collect_markdown_files(scan_dirs)
    skill_files = validator.collect_skill_entrypoints(scan_dirs)
    errors: list[str] = []
    warnings: list[str] = []
    for check_fn in validator.CHECKS.values():
        check_errors, check_warnings = check_fn(scan_dirs, markdown_files, skill_files)
        errors.extend(check_errors)
        warnings.extend(check_warnings)
    return {"passed": not errors, "errors": errors, "warnings": warnings}


def _collect_written_skill_dirs(
    results: list[object],
    target_root: Path,
) -> list[Path]:
    dirs: list[Path] = []
    for result in results:
        if result.action == "migrated":
            dirs.append(target_root / result.skill)
    return dirs


def _collect_written_skill_ids(results: list[object]) -> list[str]:
    return [f"skill:{result.skill}" for result in results if result.action == "migrated"]


def _run_tracker_write() -> tuple[bool, str]:
    tracker_script = REPO_ROOT / "tools" / "migration_support" / "tracker.py"
    return nativeness.run_tracker_write(REPO_ROOT, tracker_script)


def _tracker_command() -> str:
    tracker_script = REPO_ROOT / "tools" / "migration_support" / "tracker.py"
    return f"python3 {tracker_script.relative_to(REPO_ROOT)}"


def _display_path(path: Path | None, *, preview_root: Path | None = None) -> str | None:
    if path is None:
        return None
    named_roots: tuple[tuple[str, Path], ...] = ()
    if preview_root is not None:
        named_roots = (("preview-root", preview_root),)
    return describe_path_for_display(path, repo_root=REPO_ROOT, named_roots=named_roots)


def _dashboard_status_text() -> str | None:
    try:
        tracker_data = dashboard.load_tracker()
    except (OSError, ValueError, json.JSONDecodeError):
        return None
    if tracker_data is None:
        return None
    drifted = dashboard.detect_drift(tracker_data.get("artifacts", []))
    velocity = dashboard.compute_velocity(tracker_data.get("events", []))
    return dashboard.format_status(tracker_data, drifted, velocity)


def _result_counts(results: list[object]) -> dict[str, int]:
    counts = {
        "migrated": 0,
        "blocked": 0,
        "manual_review_required": 0,
        "refactor_required": 0,
        "archived": 0,
        "redirected": 0,
    }
    for result in results:
        if result.action in counts:
            counts[result.action] += 1
        elif result.status == migrator.STATUS_MANUAL_REVIEW_REQUIRED:
            counts["manual_review_required"] += 1
        elif result.status == migrator.STATUS_REFACTOR_REQUIRED:
            counts["refactor_required"] += 1
    return counts


def _next_action(
    report: dict[str, object],
    counts: dict[str, int],
    preview: bool,
    validation_results: list[dict[str, object]],
    tracker_updated: bool,
    nativeness_review: dict[str, object],
) -> str:
    summary = report["summary"]
    if counts["blocked"] or counts["manual_review_required"] or counts["refactor_required"]:
        return "Resolve blockers or hand-author the flagged migrations before rerunning."
    if any(result["passed"] is False for result in validation_results):
        return "Patch the generated Codex artifacts and rerun the validator before rollout."
    if preview:
        return "Inspect the preview tree and rerun without --preview once the generated package looks correct."
    if counts["migrated"] and not tracker_updated:
        return (
            "Refresh the tracker manually. After tracker write, run the required "
            "nativeness-review audit and record review outcomes with evidence."
        )
    if nativeness_review["required"] or summary["pending_native_review"]:
        return (
            "Run the nativeness-review audit next. Clean `NO_FINDINGS` reviews should "
            "auto-record `native`; only MEDIUM-only outcomes, audit-only requests, or "
            "tracker-write failures should require manual close-out."
        )
    return "No immediate blockers detected."


def _write_report(
    *,
    doctor_report: dict[str, object],
    results: list[object],
    validation_results: list[dict[str, object]],
    preview: bool,
    preview_root: Path | None,
    report_dir: Path,
    tracker_updated: bool,
    tracker_output: str,
    dashboard_text: str | None,
    nativeness_review: dict[str, object],
) -> Path:
    counts = _result_counts(results)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    if preview:
        assert preview_root is not None
        report_path = preview_root / "migration-evidence.md"
        report_path.parent.mkdir(parents=True, exist_ok=True)
    else:
        report_dir.mkdir(parents=True, exist_ok=True)
        report_path = report_dir / f"migration-evidence-{timestamp}.md"

    next_action = _next_action(
        doctor_report,
        counts,
        preview,
        validation_results,
        tracker_updated,
        nativeness_review,
    )

    lines = [
        "# Codex Migration Evidence Report",
        "",
        f"- Generated: {datetime.now(timezone.utc).isoformat()}",
        f"- Mode: {'preview' if preview else 'live'}",
        f"- Readiness: {doctor_report['summary']['readiness']} ({doctor_report['summary']['score']}/100)",
        f"- Recommended action: {doctor_report['summary']['recommended_action']}",
        "",
        "## Doctor Summary",
        "",
        f"- Skills considered: {doctor_report['summary']['skills_considered']}",
        f"- Mechanical safe: {doctor_report['summary']['mechanical_safe']}",
        f"- Blocked: {doctor_report['summary']['blocked']}",
        f"- Manual review required: {doctor_report['summary']['manual_review_required']}",
        f"- Refactor required: {doctor_report['summary']['refactor_required']}",
        f"- Existing validator failures: {doctor_report['summary']['validator_failures']}",
        f"- Drifted artifacts: {doctor_report['summary']['drifted']}",
        f"- Pending native review: {doctor_report['summary']['pending_native_review']}",
        "",
        "## Environment Readiness",
        "",
        f"- State: {doctor_report['environment_readiness']['state']}",
        f"- Failures: {doctor_report['environment_readiness']['failures']}",
        f"- Warnings: {doctor_report['environment_readiness']['warnings']}",
        f"- Codex home: `{doctor_report['environment_readiness']['codex_home']}`",
        "",
    ]

    for check in doctor_report["environment_readiness"]["checks"][:12]:
        lines.append(f"- [{check['status']}] {check['name']}: {check['detail']}")
    if len(doctor_report["environment_readiness"]["checks"]) > 12:
        lines.append(
            f"- ...and {len(doctor_report['environment_readiness']['checks']) - 12} more checks"
        )

    lines.extend(
        [
            "",
            "## Migration Results",
            "",
        ]
    )

    for result in results:
        lines.append(f"- `{result.skill}`: status={result.status} action={result.action}")

    if validation_results:
        lines.extend(["", "## Validation", ""])
        for item in validation_results:
            state = "PASS" if item["passed"] else "FAIL"
            lines.append(f"- `{item['skill']}`: {state}")
            for error in item["errors"][:3]:
                lines.append(f"  - error: {error}")
            for warning in item["warnings"][:3]:
                lines.append(f"  - warning: {warning}")
    else:
        lines.extend(["", "## Validation", "", "- No skill packages were written, so validation was skipped."])

    lines.extend(
        [
            "",
            "## Tracker / Dashboard",
            "",
            f"- Tracker updated: {'yes' if tracker_updated else 'no'}",
        ]
    )
    if tracker_output:
        lines.append(f"- Tracker output: `{tracker_output.splitlines()[0]}`")
    if dashboard_text:
        lines.extend(["", "```text", dashboard_text.strip(), "```"])

    lines.extend(["", "## Nativeness Review Handoff", ""])
    for instruction in nativeness_review["instructions"]:
        lines.append(f"- {instruction}")
    if (
        nativeness_review["state"] == "tracker_refresh_required"
        and nativeness_review.get("tracker_refresh_command")
    ):
        lines.append(f"- Tracker refresh command: `{nativeness_review['tracker_refresh_command']}`")
    for example in nativeness_review["record_review_examples"]:
        lines.append(f"- `{example['artifact_id']}` native:")
        lines.append(f"  - `{example['native']}`")
        lines.append(f"- `{example['artifact_id']}` codex_compatible_but_not_native:")
        lines.append(f"  - `{example['codex_compatible_but_not_native']}`")

    if preview and preview_root is not None:
        lines.extend(
            [
                "",
                "## Preview Output",
                "",
                f"- Preview root: `{_display_path(preview_root, preview_root=preview_root)}`",
                f"- Preview skills root: `{_display_path(preview_root / '.codex' / 'skills', preview_root=preview_root)}`",
            ]
        )

    lines.extend(["", "## Next Action", "", f"- {next_action}", ""])
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path


def run_workflow(
    *,
    skill: str | None = None,
    preview: bool = False,
    preview_dir: Path | None = None,
    report_dir: Path | None = None,
) -> dict[str, object]:
    doctor_report = doctor.build_doctor_report(skill=skill)
    preview_root = _resolve_preview_root(preview_dir) if preview else None
    target_root = (
        (preview_root / ".codex" / "skills") if preview_root is not None else migrator.TARGET_SKILLS_DIR
    )
    target_root.mkdir(parents=True, exist_ok=True)

    if skill:
        results = [
            migrator.migrate_skill(
                skill,
                dry_run=False,
                analysis_only=False,
                target_skills_dir=target_root,
                emit_text=False,
            )
        ]
    else:
        results = migrator.migrate_all(
            dry_run=False,
            analysis_only=False,
            target_skills_dir=target_root,
            emit_text=False,
        )

    written_dirs = _collect_written_skill_dirs(results, target_root)
    validation_results: list[dict[str, object]] = []
    for skill_dir in written_dirs:
        validation = _validate_scan_dir(skill_dir)
        validation_results.append(
            {
                "skill": skill_dir.name,
                "passed": validation["passed"],
                "errors": validation["errors"],
                "warnings": validation["warnings"],
            }
        )

    tracker_updated = False
    tracker_output = ""
    dashboard_text = None
    if not preview and any(result.action == "migrated" for result in results):
        tracker_updated, tracker_output = _run_tracker_write()
        if tracker_updated:
            dashboard_text = _dashboard_status_text()

    nativeness_review = nativeness.build_nativeness_review_handoff(
        _collect_written_skill_ids(results),
        preview=preview,
        tracker_updated=tracker_updated,
        tracker_command=_tracker_command(),
    )

    report_path = _write_report(
        doctor_report=doctor_report,
        results=results,
        validation_results=validation_results,
        preview=preview,
        preview_root=preview_root,
        report_dir=report_dir or (Path(tempfile.gettempdir()) / "codex-migration-evidence"),
        tracker_updated=tracker_updated,
        tracker_output=tracker_output,
        dashboard_text=dashboard_text,
        nativeness_review=nativeness_review,
    )

    return {
        "mode": "skill_migration_workflow",
        "scope": {
            "skill": skill,
            "all_skills": skill is None,
            "preview": preview,
        },
        "summary": {
            "readiness": doctor_report["summary"]["readiness"],
            "skills_considered": doctor_report["summary"]["skills_considered"],
            "blocked": doctor_report["summary"]["blocked"],
            "written": sum(1 for item in results if item.action == "migrated"),
            "validation_failures": sum(1 for item in validation_results if item["passed"] is False),
            "environment_readiness_state": doctor_report["summary"][
                "environment_readiness_state"
            ],
        },
        "items": [migrator._serialize_result(result) for result in results],
        "blockers": [
            {
                "severity": risk["severity"],
                "type": "risk",
                "detail": f"{risk['title']}: {risk['detail']}",
            }
            for risk in doctor_report["risks"]
        ],
        "next_actions": [
            _next_action(
                doctor_report,
                _result_counts(results),
                preview,
                validation_results,
                tracker_updated,
                nativeness_review,
            )
        ],
        "doctor_report": doctor_report,
        "results": [migrator._serialize_result(result) for result in results],
        "validation": validation_results,
        "preview": {
            "enabled": preview,
            "root": _display_path(preview_root, preview_root=preview_root),
            "skills_root": _display_path(target_root, preview_root=preview_root),
        },
        "tracker": {
            "updated": tracker_updated,
            "output": tracker_output,
        },
        "nativeness_review": nativeness_review,
        "environment_readiness": doctor_report["environment_readiness"],
        "report_path": _display_path(report_path, preview_root=preview_root),
    }


def format_workflow_result(result: dict[str, object]) -> str:
    lines = ["Migration Workflow", "==================", ""]
    doctor_summary = result["doctor_report"]["summary"]
    lines.append(
        f"Readiness: {doctor_summary['readiness']} ({doctor_summary['score']}/100) "
        f"recommended_action={doctor_summary['recommended_action']}"
    )
    lines.append("")
    lines.append("Results:")
    for item in result["results"]:
        lines.append(
            f"  - {item['skill']}: status={item['status']} action={item['action']}"
        )

    if result["validation"]:
        lines.append("")
        lines.append("Validation:")
        for item in result["validation"]:
            lines.append(
                f"  - {item['skill']}: {'PASS' if item['passed'] else 'FAIL'} "
                f"errors={len(item['errors'])} warnings={len(item['warnings'])}"
            )

    lines.append("")
    if result["preview"]["enabled"]:
        lines.append(f"Preview root: {result['preview']['root']}")
    lines.append(f"Report: {result['report_path']}")
    if result["tracker"]["updated"]:
        lines.append("Tracker: updated")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    result = run_workflow(
        skill=args.skill,
        preview=args.preview,
        preview_dir=args.preview_dir,
        report_dir=args.report_dir,
    )
    if args.json_output:
        print(json.dumps(result, indent=2))
    else:
        print(format_workflow_result(result))
    if result["summary"]["readiness"] == "blocked":
        return 1
    if result["summary"]["validation_failures"] > 0:
        return 1
    if (
        result["summary"]["written"] > 0
        and not result["preview"]["enabled"]
        and not result["tracker"]["updated"]
    ):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
