#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Stable skill-local entrypoint for Codex skill migration validation."""

from __future__ import annotations

import runpy
from pathlib import Path


def _find_repo_root() -> Path:
    p = Path(__file__).resolve().parent
    while p != p.parent:
        if (p / ".git").exists() or (p / "package.json").exists():
            return p
        p = p.parent
    raise RuntimeError("Repository root not found")


REPO_ROOT = _find_repo_root()
VALIDATOR = (
    REPO_ROOT
    / ".codex"
    / "skills"
    / "verify-skill-migration"
    / "scripts"
    / "validate_skill_migration.py"
)


if __name__ == "__main__":
    runpy.run_path(str(VALIDATOR), run_name="__main__")
