#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

"""Intelligent migration dashboard for Claude→Codex skill/agent migration.

Reads migration-state.json and provides actionable analysis:
  (default / --status)  Progress overview, drift detection, velocity metrics
  --plan [--batch N]    Next batch recommendation with dependency ordering
  --validate            Run Codex validator on migrated skills, report quality
  --refresh             Re-run tracker --write then show status

Location: .codex/skills/migration-dashboard/scripts/analyze_migration.py
REPO_ROOT: 4 levels up (scripts -> migration-dashboard -> skills -> .codex -> repo)
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

# ── Path resolution ────────────────────────────────────────────────────────────

def _find_repo_root() -> Path:
    p = Path(__file__).resolve().parent
    while p != p.parent:
        if (p / ".git").exists() or (p / "package.json").exists():
            return p
        p = p.parent
    raise RuntimeError("Repository root not found")


REPO_ROOT = _find_repo_root()
_SUPPORT_SRC = REPO_ROOT / "tools"
if str(_SUPPORT_SRC) not in sys.path:
    sys.path.append(str(_SUPPORT_SRC))

from migration_support.tracker_state import (  # noqa: E402
    ARCHIVED_STATE_FILE,
    default_tracker_integrity,
    load_effective_tracker_state,
)

SOURCE_SKILLS_DIR = REPO_ROOT / ".claude" / "skills"
SOURCE_AGENTS_DIR = REPO_ROOT / ".claude" / "agents"
TARGET_SKILLS_DIR = REPO_ROOT / ".codex" / "skills"
STATE_FILE = REPO_ROOT / "migration-state.json"
TRACKER_SCRIPT = REPO_ROOT / "tools" / "migration_support" / "tracker.py"
VALIDATOR_SCRIPT = REPO_ROOT / "tools" / "migration_support" / "validate_names.py"

# ── Tier classification signals ────────────────────────────────────────────────

# Any of these in allowed-tools or body → Tier 3
_TIER3_SIGNALS = frozenset(
    [
        "TaskCreate",
        "TeamCreate",
        "CronCreate",
        "EnterPlanMode",
        "ExitPlanMode",
        "mcp__example_server_f__save_note",
        "mcp__example_server_f__create_entities",
        "mcp__example_server_f__add_observations",
    ]
)

# Any of these → at least Tier 2 (unless already Tier 3)
_TIER2_SIGNALS = frozenset(
    [
        "Agent(",
        "Agent tool",
        "mcp__example_server_f__read_note",
        "mcp__example_server_f__list_notes",
        "mcp__example_server_f__find_symbol",
        "mcp__example_server_g__ask_model",
        "mcp__example_server_g__codex_review",
    ]
)

_SKILL_CALL_RE = re.compile(r"""Skill\(['"]([^'"]+)['"]\)""")

# ── Data loading ───────────────────────────────────────────────────────────────


def load_tracker() -> dict | None:
    """Load the tracker JSON. Returns None if missing."""
    tracker_data, _ = load_effective_tracker_state(STATE_FILE, ARCHIVED_STATE_FILE)
    return tracker_data


def load_tracker_state() -> tuple[dict | None, dict[str, object], str | None]:
    """Load tracker data while preserving malformed-file context for UX flows."""
    try:
        tracker_data, tracker_integrity = load_effective_tracker_state(
            STATE_FILE, ARCHIVED_STATE_FILE
        )
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return None, default_tracker_integrity(), f"Tracker could not be loaded: {exc}"
    if tracker_data is None:
        return (
            None,
            default_tracker_integrity(),
            f"Tracker file not found at {STATE_FILE}",
        )
    return tracker_data, tracker_integrity, None


def count_trust_levels(artifacts: list[dict], artifact_type: str) -> dict[str, int]:
    """Count migrated artifacts by trust level for a specific artifact type."""
    counts = {
        "trusted_recent": 0,
        "legacy_unverified": 0,
    }
    for artifact in artifacts:
        if artifact.get("artifact_type") != artifact_type:
            continue
        if artifact.get("status") != "migrated":
            continue
        trust_level = artifact.get("trust_level")
        if trust_level in counts:
            counts[trust_level] += 1
    return counts


def count_review_states(artifacts: list[dict], artifact_type: str) -> dict[str, int]:
    """Count nativeness-review lifecycle states for an artifact type."""
    counts = {
        "pending_native_review": 0,
        "codex_compatible_but_not_native": 0,
        "native": 0,
        "not_applicable": 0,
    }
    for artifact in artifacts:
        if artifact.get("artifact_type") != artifact_type:
            continue
        review_state = artifact.get("review", {}).get("state", "not_applicable")
        if review_state in counts:
            counts[review_state] += 1
    return counts


# ── Tier classification ────────────────────────────────────────────────────────


def classify_skill_tier(name: str) -> tuple[int, list[str]]:
    """Classify a Claude skill into tier 1/2/3 based on SKILL.md content signals.

    Returns (tier, signals) where signals are the matched marker strings.
    Tier 0 = unclassifiable (SKILL.md not found).
    """
    skill_md = SOURCE_SKILLS_DIR / name / "SKILL.md"
    if not skill_md.exists():
        return (0, ["skill_md_not_found"])

    content = skill_md.read_text(encoding="utf-8", errors="ignore")

    # Count distinct MCP server families (mcp__foo__bar → "foo")
    mcp_families = set(re.findall(r"mcp__([a-z0-9_-]+)__", content))

    signals: list[str] = []

    skill_call_count = len(_SKILL_CALL_RE.findall(content))
    if skill_call_count:
        signals.append(f"DEP:Skill_calls={skill_call_count}")

    # Tier 3 check
    for marker in _TIER3_SIGNALS:
        if marker in content:
            signals.append(f"T3:{marker}")
    if len(mcp_families) >= 4:
        signals.append(f"T3:mcp_families={len(mcp_families)}")

    if any(s.startswith("T3:") for s in signals):
        return (3, signals)

    # Tier 2 check
    for marker in _TIER2_SIGNALS:
        if marker in content:
            signals.append(f"T2:{marker}")
    if "Bash" in content and "allowed-tools" in content:
        signals.append("T2:Bash_in_allowed_tools")
    if len(mcp_families) >= 2:
        signals.append(f"T2:mcp_families={len(mcp_families)}")

    if any(s.startswith("T2:") for s in signals):
        return (2, signals)

    return (1, [*signals, "T1:read_only_pattern"])


# ── Dependency extraction ──────────────────────────────────────────────────────


def extract_skill_deps(name: str) -> set[str]:
    """Return skill names referenced via Skill('x') calls in a Claude skill's files."""
    skill_dir = SOURCE_SKILLS_DIR / name
    if not skill_dir.exists():
        return set()

    deps: set[str] = set()
    for fpath in skill_dir.rglob("*"):
        if not fpath.is_file():
            continue
        try:
            text = fpath.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for m in _SKILL_CALL_RE.finditer(text):
            dep = m.group(1)
            if dep != name:
                deps.add(dep)

    return deps


def extract_agent_skill_deps(name: str) -> set[str]:
    """Return skill names listed in the Claude agent's skills: frontmatter."""
    agent_path = SOURCE_AGENTS_DIR / f"{name}.md"
    if not agent_path.exists():
        return set()

    try:
        content = agent_path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return set()

    deps: set[str] = set()
    in_skills = False
    for line in content.splitlines():
        if line.strip() == "skills:":
            in_skills = True
            continue
        if in_skills:
            # YAML list item under skills:
            m = re.match(r"^\s+-\s+(.+)", line)
            if m:
                deps.add(m.group(1).strip())
            elif line and not line[0].isspace():
                # Left-indent = new key, skills: block ended
                break

    return deps


# ── Drift detection ────────────────────────────────────────────────────────────


def _compute_sha256(paths: list[Path]) -> str:
    """SHA-256 of sorted file contents — mirrors compute_version() in tracker."""
    hasher = hashlib.sha256()
    for path in sorted(paths):
        if path.exists():
            hasher.update(path.read_bytes())
    return hasher.hexdigest()


def _tracked_files_for(name: str, artifact_type: str) -> list[Path]:
    """Return the tracked files for an artifact (mirrors tracker version inputs)."""
    if artifact_type == "skill":
        paths: list[Path] = []
        claude_dir = SOURCE_SKILLS_DIR / name
        if claude_dir.exists():
            paths.extend(sorted(p for p in claude_dir.rglob("*") if p.is_file()))
        codex_dir = TARGET_SKILLS_DIR / name
        if codex_dir.exists():
            paths.extend(sorted(p for p in codex_dir.rglob("*") if p.is_file()))
        return sorted(paths)
    else:
        paths: list[Path] = []
        claude_path = SOURCE_AGENTS_DIR / f"{name}.md"
        if claude_path.exists():
            paths.append(claude_path)
        for suffix in (".toml", ".md"):
            codex_path = REPO_ROOT / ".codex" / "agents" / f"{name}{suffix}"
            if codex_path.exists():
                paths.append(codex_path)
        if paths:
            return sorted(paths)
    return []


def detect_drift(artifacts: list[dict]) -> list[dict]:
    """Find migrated artifacts whose tracked files changed since last tracker write.

    Returns list of {artifact_id, name, artifact_type, stored_sha, current_sha}.
    """
    drifted = []
    for a in artifacts:
        if a["status"] not in {"migrated", "native_codex"}:
            continue
        stored_sha = a["version"]["content_sha256"]
        tracked_paths = _tracked_files_for(a["name"], a["artifact_type"])
        current_sha = _compute_sha256(tracked_paths)
        if current_sha != stored_sha:
            drifted.append(
                {
                    "artifact_id": a["artifact_id"],
                    "name": a["name"],
                    "artifact_type": a["artifact_type"],
                    "stored_sha": stored_sha[:12],
                    "current_sha": current_sha[:12],
                }
            )
    return drifted


# ── Velocity ───────────────────────────────────────────────────────────────────

_WINDOW_DAYS = 28


def compute_velocity(events: list[dict]) -> dict:
    """Compute migration velocity from the events timeline.

    Returns {count_window, per_week, eta_weeks, window_days}.
    """
    now = datetime.now(timezone.utc)
    window_migrations = 0
    total_migrations = 0

    for ev in events:
        if ev.get("event_type") == "status_changed" and ev.get("to_status") == "migrated":
            total_migrations += 1
            try:
                ts = datetime.fromisoformat(ev["timestamp"])
                age_days = (now - ts).total_seconds() / 86400
                if age_days <= _WINDOW_DAYS:
                    window_migrations += 1
            except (ValueError, KeyError):
                pass

    per_week = round(window_migrations / (_WINDOW_DAYS / 7), 1) if window_migrations > 0 else 0.0

    return {
        "count_window": window_migrations,
        "total_migrations": total_migrations,
        "per_week": per_week,
        "window_days": _WINDOW_DAYS,
    }


def eta_weeks(pending_count: int, per_week: float) -> str:
    """Return a human-readable ETA string."""
    if per_week == 0:
        return "N/A (no recent migrations)"
    weeks = pending_count / per_week
    if weeks <= 4:
        return f"~{round(weeks)} weeks"
    months = weeks / 4.33
    return f"~{round(months)} months ({round(weeks)} weeks)"


# ── Batch planning ─────────────────────────────────────────────────────────────


def build_batch_plan(
    tracker_data: dict,
    batch_size: int = 8,
    show_all_blocked: bool = False,
) -> dict:
    """Build next-batch recommendations based on dependency graph and tier.

    Returns:
      {
        "ready": [{"artifact_id", "name", "artifact_type", "tier", "signals",
                   "unblocks", "score"}],
        "blocked": [{"artifact_id", "name", "dependency", "dep_status"}],
        "ignored": [{"artifact_id", "name", "blocking_reason"}],
        "total_pending": int,
      }
    """
    artifacts_by_id = {a["artifact_id"]: a for a in tracker_data.get("artifacts", [])}
    pending_ids: set[str] = {
        a["artifact_id"]
        for a in tracker_data.get("artifacts", [])
        if a["status"] == "pending"
    }

    # Build dependency map: artifact_id → set of artifact_ids it depends on
    deps_map: dict[str, set[str]] = {}
    for a in tracker_data.get("artifacts", []):
        aid = a["artifact_id"]
        name = a["name"]
        atype = a["artifact_type"]

        if atype == "skill":
            raw_deps = extract_skill_deps(name)
        else:
            raw_deps = extract_agent_skill_deps(name)

        # Resolve dep names to artifact_ids that exist in tracker
        resolved: set[str] = set()
        for dep_name in raw_deps:
            skill_dep_id = f"skill:{dep_name}"
            if skill_dep_id in artifacts_by_id:
                resolved.add(skill_dep_id)
        deps_map[aid] = resolved

    # Reverse map: artifact_id → set of artifact_ids that depend on it
    reverse_deps: dict[str, set[str]] = defaultdict(set)
    for aid, deps in deps_map.items():
        for dep_id in deps:
            reverse_deps[dep_id].add(aid)

    ready: list[dict] = []
    blocked: list[dict] = []
    ignored: list[dict] = []

    for artifact in tracker_data.get("artifacts", []):
        if artifact["status"] == "ignored":
            ignored.append(
                {
                    "artifact_id": artifact["artifact_id"],
                    "name": artifact["name"],
                    "artifact_type": artifact["artifact_type"],
                    "blocking_reason": artifact.get("status_reason", "manual migration ignore"),
                    "all_blockers": 1,
                }
            )
            continue

        if artifact["status"] != "pending":
            continue

        aid = artifact["artifact_id"]
        name = artifact["name"]
        atype = artifact["artifact_type"]
        my_deps = deps_map.get(aid, set())

        # Check if any dependency is still pending (blocking)
        blocking_deps = [(dep_id, artifacts_by_id[dep_id]["status"]) for dep_id in my_deps if dep_id in pending_ids]

        if blocking_deps:
            dep_id, dep_status = blocking_deps[0]
            blocked.append(
                {
                    "artifact_id": aid,
                    "name": name,
                    "artifact_type": atype,
                    "blocking_dep": dep_id,
                    "dep_status": dep_status,
                    "all_blockers": len(blocking_deps),
                }
            )
        else:
            if atype == "skill":
                tier, signals = classify_skill_tier(name)
            else:
                tier, signals = (2, ["T2:agent"])

            unblocks_names = [
                artifacts_by_id[dep_of_me]["artifact_id"]
                for dep_of_me in reverse_deps.get(aid, set())
                if dep_of_me in pending_ids
            ]

            unblock_count = len(unblocks_names)
            score = (unblock_count * 10) + max(0, (4 - tier) * 3)

            ready.append(
                {
                    "artifact_id": aid,
                    "name": name,
                    "artifact_type": atype,
                    "tier": tier,
                    "signals": signals[:3],
                    "unblocks": unblocks_names,
                    "score": score,
                }
            )

    ready.sort(key=lambda x: (-x["score"], x["tier"], x["name"]))

    return {
        "ready": ready[:batch_size],
        "ready_total": len(ready),
        "blocked": blocked if show_all_blocked else blocked[:5],
        "blocked_total": len(blocked),
        "ignored": ignored,
        "ignored_total": len(ignored),
        "total_pending": len(pending_ids),
    }


# ── Validation ─────────────────────────────────────────────────────────────────


def run_validators(tracker_data: dict) -> list[dict]:
    """Run validate_names.py against each migrated skill.

    Returns list of {name, passed, output}.
    """
    if not VALIDATOR_SCRIPT.exists():
        return [{"name": "_error", "passed": None, "output": f"Validator not found: {VALIDATOR_SCRIPT}"}]

    results = []
    for a in tracker_data.get("artifacts", []):
        if a["status"] not in {"migrated", "native_codex"} or a["artifact_type"] != "skill":
            continue

        skill_dir = TARGET_SKILLS_DIR / a["name"]
        if not skill_dir.exists():
            results.append({"name": a["name"], "passed": False, "output": "no .codex/skills/ directory"})
            continue

        try:
            proc = subprocess.run(
                [sys.executable, str(VALIDATOR_SCRIPT), "--scan-dir", str(skill_dir)],
                capture_output=True,
                text=True,
                timeout=30,
                cwd=str(REPO_ROOT),
            )
            passed = proc.returncode == 0
            output = (proc.stdout + proc.stderr).strip()
            results.append({
                "name": a["name"],
                "passed": passed,
                "output": output[:200],
                "review_state": a.get("review", {}).get("state", "not_applicable"),
            })
        except subprocess.TimeoutExpired:
            results.append({
                "name": a["name"],
                "passed": None,
                "output": "timeout",
                "review_state": a.get("review", {}).get("state", "not_applicable"),
            })
        except OSError as e:
            results.append({
                "name": a["name"],
                "passed": None,
                "output": str(e),
                "review_state": a.get("review", {}).get("state", "not_applicable"),
            })

    return results


def run_environment_readiness_validation() -> dict[str, object]:
    """Run the migration validator's environment-readiness check once per dashboard pass."""
    if not VALIDATOR_SCRIPT.exists():
        return {
            "state": "not_applicable",
            "output": f"Validator not found: {VALIDATOR_SCRIPT}",
        }
    try:
        proc = subprocess.run(
            [
                sys.executable,
                str(VALIDATOR_SCRIPT),
                "--check",
                "environment-readiness",
                "--codex-home",
                str(REPO_ROOT / ".codex"),
            ],
            capture_output=True,
            text=True,
            timeout=30,
            cwd=str(REPO_ROOT),
        )
        output = (proc.stdout + proc.stderr).strip()
        if proc.returncode != 0:
            state = "failed"
        elif "Validation PASSED with warnings." in output:
            state = "warnings"
        else:
            state = "ok"
        return {"state": state, "output": output[:500]}
    except subprocess.TimeoutExpired:
        return {"state": "failed", "output": "timeout"}
    except OSError as exc:
        return {"state": "failed", "output": str(exc)}


# ── Formatting ─────────────────────────────────────────────────────────────────

_BOLD = "\033[1m"
_RESET = "\033[0m"
_YELLOW = "\033[33m"
_GREEN = "\033[32m"
_RED = "\033[31m"
_DIM = "\033[2m"

TIER_LABELS = {
    0: "? Unclassified",
    1: "T1 Mechanical",
    2: "T2 Assisted",
    3: "T3 Hand-authored",
}

_NATIVE_REVIEWABLE_STATUSES = frozenset({"migrated", "native_codex"})
_PENDING_NATIVE_REVIEW = "pending_native_review"
_TRUST_BACKLOG_PRIORITY = {
    "legacy_unverified": 0,
    "trusted_recent": 1,
    "not_applicable": 2,
}
_SKILL_TIER_BACKLOG_PRIORITY = {
    3: 0,
    2: 1,
    1: 2,
    0: 3,
}
_QUEUE_SHOW_ALL_MAX = 25
_QUEUE_TRUNCATE_TO = 15
_ARTIFACT_STATUS_LABELS = {
    "migrated": "migrated",
    "native_codex": "native",
    "pending": "pending",
    "blocked": "blocked",
    "ignored": "ignored",
    "archived": "archived",
    "redirected": "redirected",
    "removed": "removed",
}
_REVIEW_STATE_LABELS = {
    "pending_native_review": "pending review",
    "codex_compatible_but_not_native": "compatible",
    "native": "reviewed native",
    "not_applicable": "n/a",
}
_WARNING_COUNT_RE = re.compile(r"Warnings \((\d+)\):")


def _bar(value: int, total: int, width: int = 24) -> str:
    filled = round(width * value / total) if total else 0
    return "█" * filled + "░" * (width - filled)


def _artifact_status_label(status: str) -> str:
    return _ARTIFACT_STATUS_LABELS.get(status, status)


def _review_state_label(review_state: str) -> str:
    return _REVIEW_STATE_LABELS.get(review_state, review_state)


def _warning_count(result: dict) -> int:
    output = result.get("output") or ""
    match = _WARNING_COUNT_RE.search(output)
    if match:
        return int(match.group(1))
    if output.startswith("Validation OK"):
        return 0
    return sum(1 for line in output.splitlines() if "⚠" in line)


def _actionable_pending_total(tracker_data: dict) -> int:
    summary = tracker_data.get("summary", {})
    return sum(
        summary.get(artifact_type, {}).get("pending", 0)
        + summary.get(artifact_type, {}).get("blocked", 0)
        for artifact_type in ("skill", "agent")
    )


def _pending_review_total(tracker_data: dict) -> int:
    return len(_nativeness_review_items(tracker_data))


def _review_backlog_is_primary_action(tracker_data: dict) -> bool:
    return _actionable_pending_total(tracker_data) == 0 and _pending_review_total(
        tracker_data
    ) > 0


def _recommended_action(
    *,
    key: str,
    label: str,
    reason: str,
    command: str | None = None,
    reply: str | None = None,
    artifact_id: str | None = None,
) -> dict[str, object]:
    payload: dict[str, object] = {
        "key": key,
        "label": label,
        "reason": reason,
    }
    if command is not None:
        payload["command"] = command
    if reply is not None:
        payload["reply"] = reply
    if artifact_id is not None:
        payload["artifact_id"] = artifact_id
    return payload


def _normalized_tracker_integrity(
    tracker_integrity: dict[str, object] | None,
) -> dict[str, object]:
    normalized = default_tracker_integrity()
    if tracker_integrity:
        normalized.update(tracker_integrity)
    normalized["recovered_review_artifact_ids"] = list(
        normalized.get("recovered_review_artifact_ids", [])
    )
    normalized["recovery_conflicts"] = list(normalized.get("recovery_conflicts", []))
    return normalized


def _tracker_integrity_blockers(
    tracker_integrity: dict[str, object],
) -> list[dict[str, str]]:
    if tracker_integrity.get("actionability") != "blocked":
        return []
    conflicts = tracker_integrity.get("recovery_conflicts", [])
    if conflicts:
        return [
            {
                "severity": "high",
                "type": "tracker_integrity",
                "detail": detail,
            }
            for detail in conflicts
        ]
    return [
        {
            "severity": "high",
            "type": "tracker_integrity",
            "detail": "Archived tracker recovery is ambiguous; repair the live tracker before using nativeness queues.",
        }
    ]


def _tracker_warning_lines(tracker_integrity: dict[str, object]) -> list[str]:
    if tracker_integrity.get("actionability") == "blocked":
        return [
            "Tracker review recovery is ambiguous; run "
            "`python3 tools/migration_support/tracker.py --write` before using nativeness queues."
        ]
    recovered_ids = tracker_integrity.get("recovered_review_artifact_ids", [])
    if recovered_ids:
        return [
            "Recovered archived nativeness reviews into the effective tracker view. "
            "Run `python3 tools/migration_support/tracker.py --write` to persist them."
        ]
    return []


def _nativeness_review_items(tracker_data: dict) -> list[dict]:
    """Return artifacts that are ready for nativeness review."""
    items: list[dict] = []
    for artifact in tracker_data.get("artifacts", []):
        if artifact.get("status") not in _NATIVE_REVIEWABLE_STATUSES:
            continue
        review_state = artifact.get("review", {}).get("state", "not_applicable")
        if review_state != _PENDING_NATIVE_REVIEW:
            continue

        item = {
            "artifact_id": artifact["artifact_id"],
            "name": artifact["name"],
            "artifact_type": artifact["artifact_type"],
            "status": artifact["status"],
            "review_state": review_state,
            "trust_level": artifact.get("trust_level", "not_applicable"),
        }
        if artifact["artifact_type"] == "skill":
            tier, signals = classify_skill_tier(artifact["name"])
            item["tier"] = tier
            item["tier_label"] = TIER_LABELS[tier]
            item["signals"] = signals[:3]
        items.append(item)
    return items


def build_review_backlog(tracker_data: dict) -> list[dict]:
    """Return nativeness backlog sorted by priority."""
    items = _nativeness_review_items(tracker_data)

    def sort_key(item: dict) -> tuple[int, int, int, str]:
        artifact_priority = 0 if item["artifact_type"] == "agent" else 1
        trust_priority = _TRUST_BACKLOG_PRIORITY.get(item.get("trust_level"), 2)
        skill_tier_priority = (
            _SKILL_TIER_BACKLOG_PRIORITY.get(item.get("tier", 0), 3)
            if item["artifact_type"] == "skill"
            else 0
        )
        return (artifact_priority, trust_priority, skill_tier_priority, item["name"])

    return sorted(items, key=sort_key)


def build_unreviewed_artifacts(tracker_data: dict) -> list[dict]:
    """Return all pending nativeness-review artifacts grouped by type then name."""
    items = _nativeness_review_items(tracker_data)
    return sorted(items, key=lambda item: (item["artifact_type"], item["name"]))


def build_agent_nativeness_queue(tracker_data: dict) -> list[dict]:
    """Return pending nativeness-review agents."""
    items = _nativeness_review_items(tracker_data)
    return sorted(
        (item for item in items if item["artifact_type"] == "agent"),
        key=lambda item: item["name"],
    )


def build_skill_nativeness_queue(tracker_data: dict) -> list[dict]:
    """Return pending nativeness-review skills."""
    items = _nativeness_review_items(tracker_data)
    return sorted(
        (item for item in items if item["artifact_type"] == "skill"),
        key=lambda item: item["name"],
    )


def _queue_window(items: list[dict]) -> list[dict]:
    """Return the items that should be shown in the current response."""
    if len(items) <= _QUEUE_SHOW_ALL_MAX:
        return list(items)
    return list(items[:_QUEUE_TRUNCATE_TO])


def _annotate_display_indices(items: list[dict]) -> list[dict]:
    annotated: list[dict] = []
    for index, item in enumerate(items, start=1):
        annotated.append({**item, "display_index": index})
    return annotated


def _selection_payload(
    displayed_items: list[dict],
    *,
    recommended_item: dict | None,
    tracker_integrity: dict[str, object],
) -> dict[str, object] | None:
    if not displayed_items:
        return None
    if tracker_integrity.get("actionability") == "blocked":
        return None
    examples = ["review next", f"review {min(3, len(displayed_items))}"]
    if recommended_item is not None:
        examples.append(f"review {recommended_item['name']}")
    examples.append("back")
    display_index_map = {
        str(item["display_index"]): item["artifact_id"] for item in displayed_items
    }
    return {
        "kind": "finite_named_queue",
        "recommended_item": recommended_item,
        "recommended_artifact_id": (
            recommended_item["artifact_id"] if recommended_item is not None else None
        ),
        "can_pick_by_index": True,
        "index_scope": "current_response_only",
        "displayed_artifact_ids": [item["artifact_id"] for item in displayed_items],
        "display_index_map": display_index_map,
        "queue_scope": "displayed_items_only",
        "recompute_after_action": False,
        "done_behavior": "queue_complete_requires_back",
        "reply_examples": examples,
    }


def _queue_prompt_lines(
    *,
    recommended_item: dict | None,
    truncated: bool,
    tracker_integrity: dict[str, object],
) -> list[str]:
    lines = ["", f"{_BOLD}NEXT ACTION{_RESET}"]
    if tracker_integrity.get("actionability") == "blocked":
        lines.append(
            "  Repair tracker state first: `python3 tools/migration_support/tracker.py --write`."
        )
        lines.append("  Use `back` to return to the dashboard menu.")
        return lines
    if recommended_item is not None:
        lines.append(
            "  Recommended: "
            f"`review next` for {recommended_item['artifact_type']}:{recommended_item['name']}"
        )
    lines.append("  Or pick one with `review <number>` or `review <name>`.")
    if truncated:
        lines.append("  If the item is not shown, use `review <exact-name>`.")
    lines.append("  Use `back` to return to the dashboard menu.")
    return lines


def _format_nativeness_item(item: dict) -> str:
    prefix = f"{item['artifact_type']}:"
    trust = item.get("trust_level", "not_applicable")
    artifact_status = _artifact_status_label(item.get("status", ""))
    review_state = _review_state_label(item.get("review_state", ""))
    detail = f"artifact={artifact_status}  review={review_state}  trust={trust}"
    if item["artifact_type"] == "skill":
        detail += f"  tier={item.get('tier_label', TIER_LABELS[0])}"
    return f"  {prefix}{item['name']:<34}  {detail}"


def format_status(
    tracker_data: dict,
    drifted: list[dict],
    velocity: dict,
    *,
    tracker_integrity: dict[str, object] | None = None,
) -> str:
    summary = tracker_data.get("summary", {})
    trust_policy = tracker_data.get("trust_policy", {})
    artifacts = tracker_data.get("artifacts", [])
    tracker_integrity = _normalized_tracker_integrity(tracker_integrity)
    lines: list[str] = []

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines.append(f"\n{_BOLD}Migration Dashboard — {today}{_RESET}")
    lines.append("━" * 60)

    lines.append(f"\n{_BOLD}PROGRESS{_RESET}")
    for atype in ("skill", "agent"):
        s = summary.get(atype, {})
        migrated = s.get("migrated", 0)
        redirected = s.get("redirected", 0)
        archived = s.get("archived", 0)
        native = s.get("native_codex", 0)
        pending = s.get("pending", 0)
        blocked = s.get("blocked", 0)
        ignored = s.get("ignored", 0)
        removed = s.get("removed", 0)
        done = migrated + native
        total = done + pending + blocked
        pct = round(100 * done / total) if total else 0
        bar = _bar(done, total)
        lines.append(
            f"  {atype.capitalize():6}  {done:3}/{total:3}  {bar}  {pct}%"
        )
        lines.append(
            f"           artifact lifecycle: pending: {pending}  │ migrated: {migrated}  │ "
            f"native: {native}  │ redirected: {redirected}  │ archived: {archived}"
        )
        if blocked:
            lines.append(f"           blocked: {blocked}")
        if ignored:
            lines.append(f"           ignored: {ignored}")
        if removed:
            lines.append(f"           removed: {removed}")
        review_counts = count_review_states(artifacts, atype)
        review_applicable = (
            review_counts["pending_native_review"]
            + review_counts["codex_compatible_but_not_native"]
            + review_counts["native"]
        )
        if review_applicable:
            lines.append(
                "           review lifecycle: "
                f"{review_counts['pending_native_review']} pending review  │ "
                f"{review_counts['codex_compatible_but_not_native']} compatible  │ "
                f"{review_counts['native']} reviewed native"
            )
        trust_counts = count_trust_levels(artifacts, atype)
        if migrated > 0:
            cutoff = trust_policy.get("recent_review_cutoff", "<migration-trust-cutoff-date>")
            lines.append(
                "           trust: "
                f"{trust_counts['trusted_recent']} trusted_recent  │ "
                f"{trust_counts['legacy_unverified']} legacy_unverified"
                f"  │ cutoff: {cutoff}"
            )

    skill_pending = [
        a for a in tracker_data.get("artifacts", [])
        if a["artifact_type"] == "skill" and a["status"] == "pending"
    ]
    if skill_pending:
        lines.append(f"\n{_BOLD}PENDING SKILLS — TIER BREAKDOWN{_RESET}")
        tier_counts: dict[int, int] = {1: 0, 2: 0, 3: 0, 0: 0}
        for a in skill_pending:
            tier, _ = classify_skill_tier(a["name"])
            tier_counts[tier] += 1

        for t in (1, 2, 3, 0):
            count = tier_counts[t]
            if count:
                label = TIER_LABELS[t]
                lines.append(f"  {label:22}  {count:3} skills")

    lines.append(f"\n{_BOLD}VELOCITY  (last {velocity['window_days']} days){_RESET}")
    if velocity["count_window"] > 0:
        all_pending = sum(
            a["status"] in {"pending", "blocked"}
            for a in tracker_data.get("artifacts", [])
        )
        lines.append(
            f"  {velocity['count_window']} migrations  →  {velocity['per_week']}/week"
        )
        lines.append(f"  ETA (skills + agents): {eta_weeks(all_pending, velocity['per_week'])}")
    else:
        lines.append(f"  {_YELLOW}No recent migrations tracked in events.{_RESET}")
        lines.append(
            f"  {_DIM}Tip: velocity is derived from tracker events. "
            f"If tracker was just initialized, events history is sparse.{_RESET}"
        )

    lines.append(f"\n{_BOLD}DRIFT ALERTS{_RESET}  (migrated artifacts whose tracked files changed)")
    if drifted:
        for d in drifted:
            atype_label = "skill" if d["artifact_type"] == "skill" else "agent"
            lines.append(
                f"  {_YELLOW}⚠{_RESET}  {atype_label}:{d['name']:<35}  "
                f"sha: {d['stored_sha']}→{d['current_sha']}"
            )
        lines.append(
            f"\n  {_DIM}Run /migrate-to-codex for drifted skills to re-sync .codex/ versions.{_RESET}"
        )
    else:
        lines.append(f"  {_GREEN}✓{_RESET}  No drift detected — all migrated tracked files match stored SHAs.")

    tracker_warnings = _tracker_warning_lines(tracker_integrity)
    if tracker_warnings:
        lines.append(f"\n{_BOLD}TRACKER INTEGRITY{_RESET}")
        for warning in tracker_warnings:
            lines.append(f"  {_YELLOW}⚠{_RESET}  {warning}")

    lines.append(f"\n{_BOLD}NEXT ACTION{_RESET}")
    if drifted:
        lines.append("  Recommended: re-run the relevant migration flow for drifted artifacts.")
    elif tracker_integrity.get("actionability") == "blocked":
        lines.append(
            "  Recommended: `python3 tools/migration_support/tracker.py --write`."
        )
    elif _review_backlog_is_primary_action(tracker_data):
        lines.append(
            "  Recommended: `python3 .codex/skills/migration-dashboard/scripts/analyze_migration.py --review-backlog`."
        )
    else:
        lines.append(
            "  Recommended: `python3 .codex/skills/migration-dashboard/scripts/analyze_migration.py --plan`."
        )
    lines.append(
        f"  {_DIM}Secondary: `python3 .codex/skills/migration-dashboard/scripts/analyze_migration.py --validate` or `--refresh`.{_RESET}"
    )

    return "\n".join(lines)


def format_plan(plan: dict, batch_size: int, *, pending_review_total: int = 0) -> str:
    lines: list[str] = []
    lines.append(f"\n{_BOLD}Next Batch Plan (batch-size: {batch_size}){_RESET}")
    lines.append("━" * 60)

    ready = plan["ready"]
    blocked = plan["blocked"]
    ignored = plan["ignored"]

    if not ready:
        lines.append(f"\n  {_YELLOW}No ready pending artifacts found.{_RESET}")
        if blocked:
            lines.append("  All pending artifacts have unmet dependencies — migrate blockers first.")
        elif plan["total_pending"] == 0:
            lines.append("  No actionable pending artifacts remain.")
            if pending_review_total:
                lines.append(
                    f"  Nativeness review backlog remains: {pending_review_total} artifact(s)."
                )
    else:
        lines.append(f"\n{_BOLD}READY{_RESET} — {plan['ready_total']} artifacts with no unmet dependencies (showing {len(ready)})")

        by_tier: dict[int, list[dict]] = defaultdict(list)
        for item in ready:
            by_tier[item["tier"]].append(item)

        rank = 1
        for tier in (1, 2, 3, 0):
            group = by_tier.get(tier, [])
            if not group:
                continue
            tier_label = TIER_LABELS[tier]
            lines.append(f"\n  {_BOLD}{tier_label}{_RESET}")
            for item in group:
                unblocks_str = ""
                if item["unblocks"]:
                    names = ", ".join(item["unblocks"][:3])
                    suffix = f" +{len(item['unblocks'])-3} more" if len(item["unblocks"]) > 3 else ""
                    unblocks_str = f"  {_GREEN}→ unblocks:{_RESET} {names}{suffix}"
                lines.append(f"  {rank:2}. {item['name']:<40}{unblocks_str}")
                rank += 1

    if blocked:
        lines.append(f"\n{_BOLD}BLOCKED{_RESET} — {plan['blocked_total']} artifacts have unmet dependencies (showing {len(blocked)})")
        for item in blocked:
            atype_prefix = f"{item['artifact_type']}:" if item["artifact_type"] == "agent" else ""
            extra = f" (+{item['all_blockers']-1} more)" if item["all_blockers"] > 1 else ""
            lines.append(
                f"  {_RED}x{_RESET}  {atype_prefix}{item['name']:<38}  needs: {item['blocking_dep']}{extra}"
            )
        if plan["blocked_total"] > len(blocked):
            remaining = plan["blocked_total"] - len(blocked)
            lines.append(f"  {_DIM}... and {remaining} more. Run --plan --all to see full list.{_RESET}")

    if ignored:
        lines.append(f"\n{_BOLD}IGNORED{_RESET} — {plan['ignored_total']} artifacts are intentionally excluded from migration")
        for item in ignored:
            atype_prefix = f"{item['artifact_type']}:" if item["artifact_type"] == "agent" else ""
            lines.append(
                f"  {_DIM}·{_RESET}  {atype_prefix}{item['name']:<38}  reason: {item['blocking_reason']}"
            )

    lines.append(f"\n{_BOLD}NEXT ACTION{_RESET}")
    if ready:
        top_item = ready[0]
        lines.append(
            f"  Recommended: migrate {top_item['artifact_type']}:{top_item['name']} first."
        )
    elif blocked:
        lines.append("  Recommended: resolve the first dependency blocker, then rerun planning.")
    elif pending_review_total:
        lines.append(
            "  Recommended: `python3 .codex/skills/migration-dashboard/scripts/analyze_migration.py --review-backlog`."
        )
    else:
        lines.append("  Recommended: no actionable migration work remains in this dashboard.")
    lines.append("")
    return "\n".join(lines)


def format_validate(
    results: list[dict],
    *,
    pending_review_total: int = 0,
    tracker_integrity: dict[str, object] | None = None,
    environment_readiness: dict[str, object] | None = None,
) -> str:
    tracker_integrity = _normalized_tracker_integrity(tracker_integrity)
    lines: list[str] = []
    lines.append(f"\n{_BOLD}Migration Quality Report{_RESET}")
    lines.append("━" * 60)

    passed = [r for r in results if r["passed"] is True]
    failed = [r for r in results if r["passed"] is False]
    unknown = [r for r in results if r["passed"] is None]

    total = len(results)
    lines.append(f"\n  Total migrated skills validated: {total}")
    lines.append(f"  {_GREEN}✓ Pass:{_RESET}  {len(passed)}")
    lines.append(f"  {_RED}✗ Fail:{_RESET}  {len(failed)}")
    lines.append(f"  {_YELLOW}? Skip:{_RESET}  {len(unknown)}")
    review_counts = {
        "pending_native_review": 0,
        "codex_compatible_but_not_native": 0,
        "native": 0,
        "not_applicable": 0,
    }
    for result in results:
        review_state = result.get("review_state", "not_applicable")
        if review_state in review_counts:
            review_counts[review_state] += 1
    if total:
        lines.append(
            "  Review lifecycle: "
            f"pending review={review_counts['pending_native_review']}  │ "
            f"compatible={review_counts['codex_compatible_but_not_native']}  │ "
            f"reviewed native={review_counts['native']}"
        )

    if environment_readiness:
        lines.append(
            "  Environment readiness: "
            f"{environment_readiness.get('state', 'not_applicable')}"
        )
        if environment_readiness.get("state") in {"failed", "warnings"}:
            for detail_line in str(environment_readiness.get("output", "")).splitlines()[:4]:
                lines.append(f"       {_DIM}{detail_line}{_RESET}")

    if failed:
        lines.append(f"\n{_BOLD}FAILURES{_RESET}")
        for r in failed:
            review_suffix = ""
            if r.get("review_state") and r.get("review_state") != "not_applicable":
                review_suffix = f"  [{_review_state_label(r['review_state'])}]"
            lines.append(f"  {_RED}✗{_RESET}  {r['name']}{review_suffix}")
            if r["output"]:
                for detail_line in r["output"].splitlines()[:5]:
                    lines.append(f"       {_DIM}{detail_line}{_RESET}")
    elif pending_review_total:
        lines.append(f"\n{_BOLD}NEXT REVIEW CANDIDATES{_RESET}")
        candidates = sorted(
            (
                result
                for result in results
                if result.get("review_state") == _PENDING_NATIVE_REVIEW
            ),
            key=lambda result: (-_warning_count(result), result["name"]),
        )[:5]
        for result in candidates:
            lines.append(
                f"  {_DIM}·{_RESET}  {result['name']:<35} warnings={_warning_count(result)}"
            )

    if unknown:
        lines.append(f"\n{_BOLD}SKIPPED (missing or timeout){_RESET}")
        for r in unknown:
            review_suffix = ""
            if r.get("review_state") and r.get("review_state") != "not_applicable":
                review_suffix = f"  [{_review_state_label(r['review_state'])}]"
            lines.append(f"  {_YELLOW}?{_RESET}  {r['name']}{review_suffix}  — {r['output']}")

    tracker_warnings = _tracker_warning_lines(tracker_integrity)
    if tracker_warnings:
        lines.append(f"\n{_BOLD}TRACKER INTEGRITY{_RESET}")
        for warning in tracker_warnings:
            lines.append(f"  {_YELLOW}⚠{_RESET}  {warning}")

    lines.append(f"\n{_BOLD}NEXT ACTION{_RESET}")
    if failed:
        lines.append("  Recommended: patch or re-migrate the failing skills before rollout.")
    elif tracker_integrity.get("actionability") == "blocked":
        lines.append(
            "  Recommended: `python3 tools/migration_support/tracker.py --write`."
        )
    elif pending_review_total:
        lines.append(
            "  Recommended: `python3 .codex/skills/migration-dashboard/scripts/analyze_migration.py --review-backlog`."
        )
    else:
        lines.append(
            "  Recommended: `python3 .codex/skills/migration-dashboard/scripts/analyze_migration.py --plan` if you want to inspect migration backlog."
        )
    lines.append("")
    return "\n".join(lines)


def format_review_backlog(
    items: list[dict],
    *,
    recommended_item: dict | None = None,
    tracker_integrity: dict[str, object] | None = None,
) -> str:
    tracker_integrity = _normalized_tracker_integrity(tracker_integrity)
    lines: list[str] = []
    lines.append(f"\n{_BOLD}Nativeness Review Backlog{_RESET}")
    lines.append("━" * 60)

    if not items:
        lines.append(f"\n  {_GREEN}✓{_RESET}  No pending nativeness review items remain.")
        lines.append("")
        return "\n".join(lines)

    displayed_items = _annotate_display_indices(_queue_window(items))
    lines.append(f"\n  Pending nativeness reviews: {len(items)}")
    lines.append("  Priority: agents first, then trust level, then skill tier.")

    for item in displayed_items:
        lines.append(f"  {item['display_index']:2}. {_format_nativeness_item(item).strip()}")

    tracker_warnings = _tracker_warning_lines(tracker_integrity)
    if tracker_warnings:
        lines.append(f"\n{_BOLD}TRACKER INTEGRITY{_RESET}")
        for warning in tracker_warnings:
            lines.append(f"  {_YELLOW}⚠{_RESET}  {warning}")

    lines.extend(
        _queue_prompt_lines(
            recommended_item=recommended_item,
            truncated=len(displayed_items) < len(items),
            tracker_integrity=tracker_integrity,
        )
    )

    lines.append("")
    return "\n".join(lines)


def format_unreviewed(
    items: list[dict],
    *,
    recommended_item: dict | None = None,
    tracker_integrity: dict[str, object] | None = None,
) -> str:
    tracker_integrity = _normalized_tracker_integrity(tracker_integrity)
    lines: list[str] = []
    lines.append(f"\n{_BOLD}Unreviewed Migrated Artifacts{_RESET}")
    lines.append("━" * 60)

    if not items:
        lines.append(f"\n  {_GREEN}✓{_RESET}  No migrated artifacts are waiting on nativeness review.")
        lines.append("")
        return "\n".join(lines)

    displayed_items = _annotate_display_indices(_queue_window(items))
    grouped: dict[str, list[dict]] = defaultdict(list)
    group_counts: dict[str, int] = defaultdict(int)
    for item in items:
        group_counts[item["artifact_type"]] += 1
    for item in displayed_items:
        grouped[item["artifact_type"]].append(item)

    for artifact_type in ("agent", "skill"):
        group = grouped.get(artifact_type, [])
        if not group:
            continue
        lines.append(
            f"\n{_BOLD}{artifact_type.upper()}S{_RESET} — {group_counts[artifact_type]} pending review"
        )
        for item in group:
            lines.append(f"  {item['display_index']:2}. {_format_nativeness_item(item).strip()}")

    tracker_warnings = _tracker_warning_lines(tracker_integrity)
    if tracker_warnings:
        lines.append(f"\n{_BOLD}TRACKER INTEGRITY{_RESET}")
        for warning in tracker_warnings:
            lines.append(f"  {_YELLOW}⚠{_RESET}  {warning}")

    lines.extend(
        _queue_prompt_lines(
            recommended_item=recommended_item,
            truncated=len(displayed_items) < len(items),
            tracker_integrity=tracker_integrity,
        )
    )

    lines.append("")
    return "\n".join(lines)


def format_agent_nativeness(
    items: list[dict],
    *,
    recommended_item: dict | None = None,
    tracker_integrity: dict[str, object] | None = None,
) -> str:
    tracker_integrity = _normalized_tracker_integrity(tracker_integrity)
    lines: list[str] = []
    lines.append(f"\n{_BOLD}Migrated Agents Needing Nativeness Review{_RESET}")
    lines.append("━" * 60)

    if not items:
        lines.append(f"\n  {_GREEN}✓{_RESET}  No agents are waiting on nativeness review.")
        lines.append("")
        return "\n".join(lines)

    displayed_items = _annotate_display_indices(_queue_window(items))
    for item in displayed_items:
        lines.append(f"  {item['display_index']:2}. {_format_nativeness_item(item).strip()}")

    tracker_warnings = _tracker_warning_lines(tracker_integrity)
    if tracker_warnings:
        lines.append(f"\n{_BOLD}TRACKER INTEGRITY{_RESET}")
        for warning in tracker_warnings:
            lines.append(f"  {_YELLOW}⚠{_RESET}  {warning}")

    lines.extend(
        _queue_prompt_lines(
            recommended_item=recommended_item,
            truncated=len(displayed_items) < len(items),
            tracker_integrity=tracker_integrity,
        )
    )

    lines.append("")
    return "\n".join(lines)


def format_skill_nativeness(
    items: list[dict],
    *,
    recommended_item: dict | None = None,
    tracker_integrity: dict[str, object] | None = None,
) -> str:
    tracker_integrity = _normalized_tracker_integrity(tracker_integrity)
    lines: list[str] = []
    lines.append(f"\n{_BOLD}Migrated Skills Needing Nativeness Review{_RESET}")
    lines.append("━" * 60)

    if not items:
        lines.append(f"\n  {_GREEN}✓{_RESET}  No skills are waiting on nativeness review.")
        lines.append("")
        return "\n".join(lines)

    displayed_items = _annotate_display_indices(_queue_window(items))
    for item in displayed_items:
        lines.append(f"  {item['display_index']:2}. {_format_nativeness_item(item).strip()}")

    tracker_warnings = _tracker_warning_lines(tracker_integrity)
    if tracker_warnings:
        lines.append(f"\n{_BOLD}TRACKER INTEGRITY{_RESET}")
        for warning in tracker_warnings:
            lines.append(f"  {_YELLOW}⚠{_RESET}  {warning}")

    lines.extend(
        _queue_prompt_lines(
            recommended_item=recommended_item,
            truncated=len(displayed_items) < len(items),
            tracker_integrity=tracker_integrity,
        )
    )

    lines.append("")
    return "\n".join(lines)


# ── Refresh (re-run tracker then status) ───────────────────────────────────────


def run_tracker_write() -> bool:
    """Run tools/migration_support/tracker.py --write. Returns True on success."""
    if not TRACKER_SCRIPT.exists():
        print(f"ERROR: Tracker script not found: {TRACKER_SCRIPT}", file=sys.stderr)
        return False
    result = subprocess.run(
        [sys.executable, str(TRACKER_SCRIPT), "--write"],
        cwd=str(REPO_ROOT),
    )
    return result.returncode == 0


def _tracker_unavailable_result(mode_name: str, tracker_error: str, refresh_ran: bool) -> dict[str, object]:
    return {
        "mode": "migration_dashboard",
        "scope": {
            "mode_name": mode_name,
            "tracker_available": False,
            "refresh_ran": refresh_ran,
        },
        "summary": {
            "state": "tracker_unavailable",
            "refresh_ran": refresh_ran,
        },
        "items": [],
        "blockers": [
            {
                "severity": "high",
                "type": "tracker",
                "detail": tracker_error,
            }
        ],
        "next_actions": [
            "Run `python3 tools/migration_support/tracker.py --write` to rebuild or repair the tracker."
        ],
    }


def _status_next_actions(drifted: list[dict]) -> list[str]:
    if drifted:
        return ["Re-run the relevant migration flow for drifted artifacts before expanding the next batch."]
    return ["Use plan mode to choose the next batch or validate migrated artifacts."]


def build_status_result(
    tracker_data: dict,
    drifted: list[dict],
    velocity: dict,
    *,
    refresh_ran: bool = False,
    tracker_integrity: dict[str, object] | None = None,
) -> dict[str, object]:
    tracker_integrity = _normalized_tracker_integrity(tracker_integrity)
    pending_review_total = _pending_review_total(tracker_data)
    if drifted:
        recommended_action = _recommended_action(
            key="reconcile_drift",
            label="Reconcile drifted artifacts",
            reason="Tracked migrated files changed since the last tracker write.",
        )
        next_actions = _status_next_actions(drifted)
    elif tracker_integrity.get("actionability") == "blocked":
        recommended_action = _recommended_action(
            key="repair_tracker",
            label="Repair tracker state",
            reason="Archived review recovery is ambiguous and nativeness queues are blocked until the live tracker is refreshed.",
            command="python3 tools/migration_support/tracker.py --write",
        )
        next_actions = _tracker_warning_lines(tracker_integrity)
    elif _review_backlog_is_primary_action(tracker_data):
        recommended_action = _recommended_action(
            key="review_backlog",
            label="Review nativeness backlog",
            reason="Migration backlog is clear, but nativeness reviews are still pending.",
            command="python3 .codex/skills/migration-dashboard/scripts/analyze_migration.py --review-backlog",
        )
        next_actions = [
            "Review nativeness backlog next; migration backlog is already clear."
        ]
    else:
        recommended_action = _recommended_action(
            key="plan",
            label="Inspect migration backlog",
            reason="Migration backlog still has actionable work.",
            command="python3 .codex/skills/migration-dashboard/scripts/analyze_migration.py --plan",
        )
        next_actions = _status_next_actions(drifted)
    return {
        "mode": "migration_dashboard",
        "scope": {
            "mode_name": "status",
            "tracker_available": True,
            "refresh_ran": refresh_ran,
        },
        "summary": {
            "state": "ok",
            "tracker_summary": tracker_data.get("summary", {}),
            "drift_count": len(drifted),
            "velocity": velocity,
            "pending_review_total": pending_review_total,
            "actionable_pending_total": _actionable_pending_total(tracker_data),
        },
        "tracker_integrity": tracker_integrity,
        "items": drifted,
        "blockers": _tracker_integrity_blockers(tracker_integrity),
        "next_actions": next_actions,
        "recommended_action": recommended_action,
    }


def build_plan_result(
    tracker_data: dict,
    plan: dict,
    *,
    batch_size: int,
) -> dict[str, object]:
    ready_items = [
        {
            "type": "ready",
            **item,
        }
        for item in plan["ready"]
    ]
    blocked_items = [
        {
            "type": "blocked",
            **item,
        }
        for item in plan["blocked"]
    ]
    ignored_items = [
        {
            "type": "ignored",
            **item,
        }
        for item in plan["ignored"]
    ]
    pending_review_total = _pending_review_total(tracker_data)
    if ready_items:
        top_ready = ready_items[0]
        recommended_action = _recommended_action(
            key="migrate_top_ready",
            label=f"Migrate {top_ready['artifact_type']}:{top_ready['name']}",
            reason="This is the highest-priority ready item from the current dependency graph.",
            artifact_id=top_ready["artifact_id"],
        )
        next_actions = [
            "Migrate the top ready item first, then rerun planning to confirm the dependency graph changed as expected."
        ]
    elif blocked_items:
        recommended_action = _recommended_action(
            key="resolve_blocker",
            label="Resolve first dependency blocker",
            reason="No ready items remain until at least one blocker is cleared.",
        )
        next_actions = ["Resolve the first dependency blocker, then rerun planning."]
    elif pending_review_total:
        recommended_action = _recommended_action(
            key="review_backlog",
            label="Review nativeness backlog",
            reason="No actionable migration backlog remains, but nativeness reviews are still pending.",
            command="python3 .codex/skills/migration-dashboard/scripts/analyze_migration.py --review-backlog",
        )
        next_actions = [
            "No actionable pending items remain; review nativeness backlog next."
        ]
    else:
        recommended_action = _recommended_action(
            key="no_actionable_work",
            label="No actionable migration work remains",
            reason="Only ignored items remain in the migration dashboard.",
        )
        next_actions = [
            "No actionable pending items remain; ignored items are intentionally excluded from migration."
        ]
    return {
        "mode": "migration_dashboard",
        "scope": {
            "mode_name": "plan",
            "tracker_available": True,
            "batch_size": batch_size,
        },
        "summary": {
            "state": "ok",
            "ready_total": plan["ready_total"],
            "blocked_total": plan["blocked_total"],
            "ignored_total": plan["ignored_total"],
            "total_pending": plan["total_pending"],
            "pending_review_total": pending_review_total,
            "artifact_summary": tracker_data.get("summary", {}),
        },
        "items": ready_items + blocked_items + ignored_items,
        "blockers": [
            {
                "severity": "medium",
                "type": "dependency",
                "detail": f"{item['name']} waits on {item['blocking_dep']}",
            }
            for item in plan["blocked"]
        ],
        "next_actions": next_actions,
        "recommended_action": recommended_action,
    }


def build_validate_result(
    tracker_data: dict,
    results: list[dict],
    *,
    tracker_integrity: dict[str, object] | None = None,
    environment_readiness: dict[str, object] | None = None,
) -> dict[str, object]:
    tracker_integrity = _normalized_tracker_integrity(tracker_integrity)
    environment_readiness = environment_readiness or {
        "state": "not_applicable",
        "output": "",
    }
    blockers = [
        {
            "severity": "high",
            "type": "validation",
            "detail": f"{result['name']} failed validation",
        }
        for result in results
        if result["passed"] is False
    ]
    pending_review_total = _pending_review_total(tracker_data)
    blockers.extend(_tracker_integrity_blockers(tracker_integrity))
    if environment_readiness.get("state") == "failed":
        blockers.append(
            {
                "severity": "medium",
                "type": "environment_readiness",
                "detail": "Environment readiness check failed.",
            }
        )
    if blockers and any(blocker["type"] == "validation" for blocker in blockers):
        recommended_action = _recommended_action(
            key="fix_validation_failures",
            label="Fix validation failures",
            reason="At least one migrated skill failed validation.",
        )
        next_actions = ["Patch or re-migrate the failing skills before further rollout."]
    elif environment_readiness.get("state") == "failed":
        recommended_action = _recommended_action(
            key="fix_environment_readiness",
            label="Fix environment readiness",
            reason="Skill validation passed, but the Codex runtime readiness check failed.",
            command="python3 tools/migration_support/validate_names.py --check environment-readiness --codex-home .codex",
        )
        next_actions = [
            "Fix the failed environment readiness checks before relying on migrated artifacts operationally."
        ]
    elif tracker_integrity.get("actionability") == "blocked":
        recommended_action = _recommended_action(
            key="repair_tracker",
            label="Repair tracker state",
            reason="Archived review recovery is ambiguous and nativeness queues are blocked until the live tracker is refreshed.",
            command="python3 tools/migration_support/tracker.py --write",
        )
        next_actions = _tracker_warning_lines(tracker_integrity)
    elif pending_review_total:
        recommended_action = _recommended_action(
            key="review_backlog",
            label="Review nativeness backlog",
            reason="Validation passed, and the remaining migration work is nativeness review.",
            command="python3 .codex/skills/migration-dashboard/scripts/analyze_migration.py --review-backlog",
        )
        next_actions = [
            "Validation passed; nativeness review backlog is the next highest-signal action."
        ]
    else:
        recommended_action = _recommended_action(
            key="plan",
            label="Inspect migration backlog",
            reason="Validation passed and no nativeness review backlog was detected.",
            command="python3 .codex/skills/migration-dashboard/scripts/analyze_migration.py --plan",
        )
        next_actions = ["Validation passed for the scanned artifacts; continue with nativeness review or the next batch."]
    return {
        "mode": "migration_dashboard",
        "scope": {
            "mode_name": "validate",
            "tracker_available": True,
        },
        "summary": {
            "state": "ok",
            "validated_total": len(results),
            "failed": sum(1 for result in results if result["passed"] is False),
            "passed": sum(1 for result in results if result["passed"] is True),
            "skipped": sum(1 for result in results if result["passed"] is None),
            "pending_review_total": pending_review_total,
            "environment_readiness_state": environment_readiness.get(
                "state", "not_applicable"
            ),
            "artifact_summary": tracker_data.get("summary", {}),
        },
        "tracker_integrity": tracker_integrity,
        "environment_readiness": environment_readiness,
        "items": results,
        "blockers": blockers,
        "next_actions": next_actions,
        "recommended_action": recommended_action,
    }


def _build_nativeness_summary(items: list[dict]) -> dict[str, int]:
    agent_total = sum(1 for item in items if item["artifact_type"] == "agent")
    skill_total = sum(1 for item in items if item["artifact_type"] == "skill")
    return {
        "pending_review_total": len(items),
        "agent_total": agent_total,
        "skill_total": skill_total,
    }


def _build_queue_result(
    *,
    tracker_data: dict,
    mode_name: str,
    items: list[dict],
    recommended_item: dict | None,
    next_actions: list[str],
    tracker_integrity: dict[str, object] | None = None,
) -> dict[str, object]:
    tracker_integrity = _normalized_tracker_integrity(tracker_integrity)
    displayed_items = _annotate_display_indices(_queue_window(items))
    recommended_action = None
    if (
        recommended_item is not None
        and tracker_integrity.get("actionability") != "blocked"
    ):
        recommended_action = _recommended_action(
            key="review_next",
            label=f"Review {recommended_item['artifact_type']}:{recommended_item['name']}",
            reason="This is the recommended next item from the currently displayed queue.",
            reply="review next",
            artifact_id=recommended_item["artifact_id"],
        )
    result = {
        "mode": "migration_dashboard",
        "scope": {
            "mode_name": mode_name,
            "tracker_available": True,
        },
        "summary": {
            "state": "ok",
            **_build_nativeness_summary(items),
            "displayed_count": len(displayed_items),
            "hidden_count": max(0, len(items) - len(displayed_items)),
            "artifact_summary": tracker_data.get("summary", {}),
        },
        "tracker_integrity": tracker_integrity,
        "items": displayed_items,
        "blockers": _tracker_integrity_blockers(tracker_integrity),
        "next_actions": next_actions,
    }
    if recommended_action is not None:
        result["recommended_action"] = recommended_action
    selection = _selection_payload(
        displayed_items,
        recommended_item=recommended_item,
        tracker_integrity=tracker_integrity,
    )
    if selection is not None:
        result["selection"] = selection
    return result


def build_review_backlog_result(
    tracker_data: dict,
    items: list[dict],
    *,
    tracker_integrity: dict[str, object] | None = None,
) -> dict[str, object]:
    tracker_integrity = _normalized_tracker_integrity(tracker_integrity)
    if tracker_integrity.get("actionability") == "blocked":
        recommended_item = None
        next_actions = _tracker_warning_lines(tracker_integrity)
    elif items:
        recommended_item = items[0]
        next_actions = [
            "Use `review next` to audit the recommended item, or `review <number>` / `review <name>` to choose another queued artifact."
        ]
    else:
        recommended_item = None
        next_actions = ["No nativeness-review backlog remains."]
    return _build_queue_result(
        tracker_data=tracker_data,
        mode_name="review_backlog",
        items=items,
        recommended_item=recommended_item,
        next_actions=next_actions,
        tracker_integrity=tracker_integrity,
    )


def build_unreviewed_result(
    tracker_data: dict,
    items: list[dict],
    *,
    tracker_integrity: dict[str, object] | None = None,
) -> dict[str, object]:
    tracker_integrity = _normalized_tracker_integrity(tracker_integrity)
    if tracker_integrity.get("actionability") == "blocked":
        recommended_item = None
        next_actions = _tracker_warning_lines(tracker_integrity)
    elif items:
        recommended_item = items[0]
        next_actions = [
            "Use `review next` for the first item in this list, or `review <number>` / `review <name>` to choose from this list."
        ]
    else:
        recommended_item = None
        next_actions = ["No unreviewed migrated artifacts remain."]
    return _build_queue_result(
        tracker_data=tracker_data,
        mode_name="unreviewed",
        items=items,
        recommended_item=recommended_item,
        next_actions=next_actions,
        tracker_integrity=tracker_integrity,
    )


def build_agent_nativeness_result(
    tracker_data: dict,
    items: list[dict],
    *,
    tracker_integrity: dict[str, object] | None = None,
) -> dict[str, object]:
    tracker_integrity = _normalized_tracker_integrity(tracker_integrity)
    if tracker_integrity.get("actionability") == "blocked":
        recommended_item = None
        next_actions = _tracker_warning_lines(tracker_integrity)
    elif items:
        recommended_item = items[0]
        next_actions = [
            "Use `review next` for the first queued agent, or `review <number>` / `review <name>` to pick a specific agent."
        ]
    else:
        recommended_item = None
        next_actions = ["No migrated agents are waiting on nativeness review."]
    result = _build_queue_result(
        tracker_data=tracker_data,
        mode_name="agent_nativeness",
        items=items,
        recommended_item=recommended_item,
        next_actions=next_actions,
        tracker_integrity=tracker_integrity,
    )
    result["summary"].pop("skill_total", None)
    return result


def build_skill_nativeness_result(
    tracker_data: dict,
    items: list[dict],
    *,
    tracker_integrity: dict[str, object] | None = None,
) -> dict[str, object]:
    tracker_integrity = _normalized_tracker_integrity(tracker_integrity)
    if tracker_integrity.get("actionability") == "blocked":
        recommended_item = None
        next_actions = _tracker_warning_lines(tracker_integrity)
    elif items:
        recommended_item = items[0]
        next_actions = [
            "Use `review next` for the first queued skill, or `review <number>` / `review <name>` to pick a specific skill."
        ]
    else:
        recommended_item = None
        next_actions = ["No migrated skills are waiting on nativeness review."]
    result = _build_queue_result(
        tracker_data=tracker_data,
        mode_name="skill_nativeness",
        items=items,
        recommended_item=recommended_item,
        next_actions=next_actions,
        tracker_integrity=tracker_integrity,
    )
    result["summary"].pop("agent_total", None)
    return result


# ── Main ───────────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Intelligent migration dashboard for Claude→Codex migration",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--status", action="store_true", default=False, help="Show status overview (default)")
    mode.add_argument("--plan", action="store_true", help="Show next batch recommendation")
    mode.add_argument("--review-backlog", action="store_true", help="Show prioritized nativeness review backlog")
    mode.add_argument("--unreviewed", action="store_true", help="Show all migrated artifacts pending nativeness review")
    mode.add_argument("--agent-nativeness", action="store_true", help="Show migrated agents pending nativeness review")
    mode.add_argument("--skill-nativeness", action="store_true", help="Show migrated skills pending nativeness review")
    mode.add_argument("--validate", action="store_true", help="Run validators on migrated skills")
    mode.add_argument("--refresh", action="store_true", help="Re-run tracker --write then show status")
    parser.add_argument("--batch", type=int, default=8, metavar="N", help="Batch size for --plan (default: 8)")
    parser.add_argument(
        "--all",
        dest="show_all",
        action="store_true",
        help="Show all blocked items in --plan; ignored items are always shown",
    )
    parser.add_argument("--no-color", action="store_true", help="Disable ANSI color codes")
    parser.add_argument("--json", action="store_true", dest="json_output", help="Emit structured JSON.")
    args = parser.parse_args()

    if args.no_color:
        global _BOLD, _RESET, _YELLOW, _GREEN, _RED, _DIM
        _BOLD = _RESET = _YELLOW = _GREEN = _RED = _DIM = ""

    refresh_ran = False
    if args.refresh:
        if not args.json_output:
            print("Updating tracker...")
        if not run_tracker_write():
            print("ERROR: Tracker update failed.", file=sys.stderr)
            return 1
        refresh_ran = True

    tracker_data, tracker_integrity, tracker_error = load_tracker_state()
    if args.validate:
        mode_name = "validate"
    elif args.plan:
        mode_name = "plan"
    elif args.review_backlog:
        mode_name = "review_backlog"
    elif args.unreviewed:
        mode_name = "unreviewed"
    elif args.agent_nativeness:
        mode_name = "agent_nativeness"
    elif args.skill_nativeness:
        mode_name = "skill_nativeness"
    else:
        mode_name = "status"
    if tracker_data is None:
        result = _tracker_unavailable_result(mode_name, tracker_error or "Tracker unavailable.", refresh_ran)
        if args.json_output:
            print(json.dumps(result, indent=2))
        else:
            print(
                "\n".join(
                    [
                        "Migration Dashboard",
                        "===================",
                        "",
                        f"Tracker unavailable: {tracker_error}",
                        "Repair: python3 tools/migration_support/tracker.py --write",
                    ]
                )
            )
        return 0

    if args.validate:
        if not args.json_output:
            print("Running validators on migrated skills...")
        results = run_validators(tracker_data)
        environment_readiness = run_environment_readiness_validation()
        result = build_validate_result(
            tracker_data,
            results,
            tracker_integrity=tracker_integrity,
            environment_readiness=environment_readiness,
        )
        if args.json_output:
            print(json.dumps(result, indent=2))
        else:
            print(
                format_validate(
                    results,
                    pending_review_total=result["summary"]["pending_review_total"],
                    tracker_integrity=tracker_integrity,
                    environment_readiness=environment_readiness,
                )
            )
        return 0

    if args.plan:
        plan = build_batch_plan(tracker_data, args.batch, show_all_blocked=args.show_all)
        result = build_plan_result(tracker_data, plan, batch_size=args.batch)
        if args.json_output:
            print(json.dumps(result, indent=2))
        else:
            print(
                format_plan(
                    plan,
                    args.batch,
                    pending_review_total=result["summary"]["pending_review_total"],
                )
            )
        return 0

    if args.review_backlog:
        items = build_review_backlog(tracker_data)
        result = build_review_backlog_result(
            tracker_data,
            items,
            tracker_integrity=tracker_integrity,
        )
        if args.json_output:
            print(json.dumps(result, indent=2))
        else:
            recommended_item = result.get("selection", {}).get("recommended_item")
            print(
                format_review_backlog(
                    items,
                    recommended_item=recommended_item,
                    tracker_integrity=tracker_integrity,
                )
            )
        return 0

    if args.unreviewed:
        items = build_unreviewed_artifacts(tracker_data)
        result = build_unreviewed_result(
            tracker_data,
            items,
            tracker_integrity=tracker_integrity,
        )
        if args.json_output:
            print(json.dumps(result, indent=2))
        else:
            recommended_item = result.get("selection", {}).get("recommended_item")
            print(
                format_unreviewed(
                    items,
                    recommended_item=recommended_item,
                    tracker_integrity=tracker_integrity,
                )
            )
        return 0

    if args.agent_nativeness:
        items = build_agent_nativeness_queue(tracker_data)
        result = build_agent_nativeness_result(
            tracker_data,
            items,
            tracker_integrity=tracker_integrity,
        )
        if args.json_output:
            print(json.dumps(result, indent=2))
        else:
            recommended_item = result.get("selection", {}).get("recommended_item")
            print(
                format_agent_nativeness(
                    items,
                    recommended_item=recommended_item,
                    tracker_integrity=tracker_integrity,
                )
            )
        return 0

    if args.skill_nativeness:
        items = build_skill_nativeness_queue(tracker_data)
        result = build_skill_nativeness_result(
            tracker_data,
            items,
            tracker_integrity=tracker_integrity,
        )
        if args.json_output:
            print(json.dumps(result, indent=2))
        else:
            recommended_item = result.get("selection", {}).get("recommended_item")
            print(
                format_skill_nativeness(
                    items,
                    recommended_item=recommended_item,
                    tracker_integrity=tracker_integrity,
                )
            )
        return 0

    drifted = detect_drift(tracker_data.get("artifacts", []))
    velocity = compute_velocity(tracker_data.get("events", []))
    result = build_status_result(
        tracker_data,
        drifted,
        velocity,
        refresh_ran=refresh_ran,
        tracker_integrity=tracker_integrity,
    )
    if args.json_output:
        print(json.dumps(result, indent=2))
    else:
        print(
            format_status(
                tracker_data,
                drifted,
                velocity,
                tracker_integrity=tracker_integrity,
            )
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
